### ISSUE TITLE
Không xem được phimmoi.net

### ISSUE THREAD

**Issue by namhbnam** [bigdargon/hostsVN#107]
Sau khi áp dụng bộ lọc thì không xem được nữa. Mình dùng adway root. Chỉ áp dụng bộ lọc duy nhất bên b.
Http://phimmoi.net

**Comment by bigdargon** [comment]
Bạn có thể quay video màn hình và dẫn link phim mà bạn xem bị lỗi không? Vì mình xem vẫn bình thường
https://youtu.be/TObd0829x7Q

**Comment by namhbnam** [comment]
Mình xem được rồi nhé. Bị lỗi phải ấn vài lần mới được.

**Comment by bigdargon** [comment]
Vì mấy trang web phim chèn rất nhiều qc vào nên nhấn play nhiều lần sẽ load được! Rất vui khi bạn quan tâm tới hostsVN!
