### ISSUE TITLE
connect.facebook.net breaks websites login from facebook

### ISSUE THREAD

**Issue by asaddon** [bigdargon/hostsVN#114]
**connect.facebook.net** is blocked by your extended list and it breaks Facebook login in the websites.

**Comment by bigdargon** [comment]
Thank you for your interest in my github!

Expanded list to completely block domains that contain ads & tracking that can cause errors in some applications and some websites. This has been mentioned for each issue in the file https://github.com/bigdargon/hostsVN/blob/master/whitelist.txt

I have mentioned in the hosts file `Extended list block, which can cause errors in some applications`. Please use this hosts file https://github.com/bigdargon/hostsVN/blob/master/hosts without error when using!
