### ISSUE TITLE
Can’t block ad web comicvn.net

### ISSUE THREAD

**Issue by vudinhthai** [bigdargon/hostsVN#121]
![b2153966-59c7-45bb-a5a4-38b4f5b60638](https://user-images.githubusercontent.com/46418063/53650101-52889100-3c76-11e9-8288-ed8a4518738c.png)
![fb7a2306-1464-4be9-b127-55a1f0aa3f5a](https://user-images.githubusercontent.com/46418063/53650102-52889100-3c76-11e9-860e-bd8c79e1774c.png)
![b7a3a7ee-441c-4d7a-896b-e97bc250adee](https://user-images.githubusercontent.com/46418063/53650103-53212780-3c76-11e9-8a30-f06247e7c98d.png)

**Comment by bigdargon** [comment]
Với các web bạn vui lòng bật bộ lọc trên safari để chặn sạch sẽ hơn, mình đã report banner cho team adguard. Khi nào họ fix xong bạn cập nhật lại bộ lọc giúp mình!
https://github.com/AdguardTeam/AdguardFilters/issues/30349

**Comment by bigdargon** [comment]
@vudinhthai Adguard đã thêm vào bộ lọc, bạn cập nhật bộ lọc cho safari là được nhé!
