### ISSUE TITLE
Không vào được internet sau khi cop file host vào etc máy ios đã JB

### ISSUE THREAD

**Issue by mrtiger9x** [bigdargon/hostsVN#122]

**Comment by bigdargon** [comment]
Chào bạn!

Việc chép vào file hosts của iOS mình không khuyến cáo việc làm này, do mỗi lần truy vấn iOS sẽ phải tra cứu trong danh sách hosts trước rồi mới truy cập mạng, file hosts quá lớn sẽ gây quá tải và ngốn pin thiết bị!

Mình chỉ khuyên bạn nên thêm một số dòng hosts cơ bản để chặn thu hồi chứng chỉ, rồi sử dụng các apps VPN để chặn sẽ ổn định máy hơn. Máy mình sau khi JB chỉ thêm vài dòng để chặn thu hồi là đủ.

```
0 ocsp.apple.com
:: ocsp.apple.com
0 world-gen.g.aaplimg.com
:: world-gen.g.aaplimg.com
```

**Comment by mrtiger9x** [comment]
Mình cảm ơn ạ, nhưng mình nghĩ dùng VPN cũng tốn pin nhỉ @@

**Comment by bigdargon** [comment]
Apps Adguard Pro hay Surge đều cực nhanh và ít ăn pin lắm bạn, vì iOS giới hạn RAM cho tiến trình VPN. Bạn có thể tải Surge về dùng thử và cảm nhận kết quả!

**Comment by mrtiger9x** [comment]
Mình dùng surge thì nó báo lỗi như này: “Surge network extension failed to start”, dùng cái default của nó thì vẫN start bt

**Comment by bigdargon** [comment]
Bạn khởi động lại ở chế độ non-jb rồi thực hiện lại xem!

**Comment by mrtiger9x** [comment]
Okay để mình thử quantumult luôn

**Comment by mrtiger9x** [comment]
Cái Surge mình dùng ở non-jb thì đc, jb thì k thể dùng đc @@

**Comment by bigdargon** [comment]
Do quá trình JB bạn cài tweak nào đó đã làm xung đột với VPN nên dẫn đến lỗi sau khi JB
