### ISSUE TITLE
Đóng góp

### ISSUE THREAD

**Issue by ultimatevn** [bigdargon/hostsVN#125]
Mình thấy list này chưa đầy đủ lắm, nếu mình muốn thêm custom vào dựa trên list này thì sao bác nhỉ. Vào một số trang như 5giay.vn vẫn còn rất nhiều quảng cáo.

**Comment by bigdargon** [comment]
Có nhiều cách lắm bạn! Nếu bạn muốn tự phát triển dựa trên list của mình bạn có thể dùng chức năng Fork của Github, còn bạn chỉ muốn đóng góp 1 số tên miền thì bạn chỉ cần tạo issue ghi tên miền bạn muốn mình thêm, mình sẽ test và thêm những tên miền đó vào list!

**Comment by bigdargon** [comment]
Quảng cáo của `5giay.vn` nằm ở tên miền `banner.5giay.vn` mình sẽ thêm vào lần cập nhật kế tiếp! Thanks bạn đã báo cáo!
