### ISSUE TITLE
Báo lỗi vpnVN

### ISSUE THREAD

**Issue by hakhason** [bigdargon/hostsVN#13]
Mình mới thử
![dcc6568c-c983-429e-8d4b-b1c648ea5396](https://user-images.githubusercontent.com/42986428/45065754-32bc4a00-b0e5-11e8-88c2-e9073abf0784.png)
![7fcaa865-8d8e-4d88-83ba-9f436289ab29](https://user-images.githubusercontent.com/42986428/45065755-32bc4a00-b0e5-11e8-9fb3-bd949fe3a883.png)
![df83574e-fdb4-4f2e-95ea-cfadd79ee018](https://user-images.githubusercontent.com/42986428/45065756-32bc4a00-b0e5-11e8-9a76-00c5955af53a.png)
![4306732d-af02-42b0-b829-650cac52bd43](https://user-images.githubusercontent.com/42986428/45065757-3354e080-b0e5-11e8-8248-a707a7bda003.png)
![7cbb28bc-2300-4cf8-bd9f-ae96ee95d6a3](https://user-images.githubusercontent.com/42986428/45065758-3354e080-b0e5-11e8-977b-73b0d1400e2a.png)
![c73d4f83-310b-45e6-9c34-5f4a7678f1ba](https://user-images.githubusercontent.com/42986428/45065759-3354e080-b0e5-11e8-8cfa-360ecba45645.png)
![610e5721-94e0-4474-9794-5921dd19e877](https://user-images.githubusercontent.com/42986428/45065760-33ed7700-b0e5-11e8-9e6a-6da0e3edcaaf.png)
![b1e6fbbe-26cc-4fea-9d6f-8f3c784c2ce1](https://user-images.githubusercontent.com/42986428/45065761-33ed7700-b0e5-11e8-9c21-f926c585adcd.png)
![c1a752b9-6a9b-40df-a792-6bec502de4df](https://user-images.githubusercontent.com/42986428/45065762-33ed7700-b0e5-11e8-995e-b77ac94a1cb3.png)
![c7fcacda-80ec-4783-9134-436e991c7072](https://user-images.githubusercontent.com/42986428/45065763-34860d80-b0e5-11e8-9433-2bcbcfed3336.png)
![76880fac-5a4e-4d4c-81c9-d6e7e54e34d9](https://user-images.githubusercontent.com/42986428/45065765-34860d80-b0e5-11e8-9e4f-00fbf94888fa.png)
![2aae53f4-754a-4f5c-b402-5c4d345fdc33](https://user-images.githubusercontent.com/42986428/45065767-351ea400-b0e5-11e8-9ac6-ab8bde971aa0.png)
![77815e22-8012-4ef5-b66f-6b2fc00c0f4d](https://user-images.githubusercontent.com/42986428/45065768-351ea400-b0e5-11e8-8a19-2107c8b414e6.png)
![60919132-da55-4385-b909-3e9e86abfa63](https://user-images.githubusercontent.com/42986428/45065770-35b73a80-b0e5-11e8-99d3-5e0df68b1049.png)
![8dfe4bb2-ceb7-485d-8d3a-17139b13311d](https://user-images.githubusercontent.com/42986428/45065771-35b73a80-b0e5-11e8-9dbd-72474d11b5ed.png)
![8d79f49e-0e87-4b61-be98-4b8e47f4bad9](https://user-images.githubusercontent.com/42986428/45065772-364fd100-b0e5-11e8-9d60-b9177ffb44b4.png)

 và có 1 số lỗi gổ cho bạn đây. Thanks bạn đã chia sẽ

**Comment by bigdargon** [comment]
Những dòng màu đỏ là các tên miền nằm trong danh sách chặn, bạn báo lỗi ở ứng dụng nào?

**Comment by hakhason** [comment]
Mình báo những lỗi đó của ứng dụng AdGuard Pro đó bạn

**Comment by bigdargon** [comment]
Adguard Pro hiển thị màu đỏ nghĩa là tên miền đó nằm trong danh sách bị chặn lại nên có màu đỏ, những tên miền bị chặn tùy theo danh sách mà bạn thêm! Nếu bạn thêm danh sách Adguard và danh sách hostsVN của mình thì tên miền bị chặn là quảng cáo hoặc theo dõi người dùng!

Hiển thị như vậy là điều BÌNH THƯỜNG đó bạn! Bạn xem chi tiết tại đây https://github.com/AdguardTeam/AdguardForiOS/issues/455
