### ISSUE TITLE
Danh sách trắng cần thiết để tải về ứng dụng firestick

### ISSUE THREAD

**Issue by Thomas499** [bigdargon/hostsVN#132]
Xin chào, tôi chỉ nói tiếng Anh nhưng tôi sử dụng http://imtranslator.net/translation/english/to-vietnamese/translation/ để dịch. Tôi hy vọng bạn hiểu.
>>>> Hello, I only speak English but I used http://imtranslator.net/translation/english/to-vietnamese/translation/ to translate. I hope you understand. 

Yêu cầu danh sách trắng:
>>>>Whitelist Request:
mas-ext.amazon.com

Thiết bị thực hiện:
>>>>Devices effected:
All amazon firesticks

Tác dụng của việc có danh sách ở trên được kích hoạt mà không cần mas-ext.amazon.com vào danh sách trắng: khi người dùng cố gắng để tải về bất kỳ ứng dụng mới trên firestick từ cửa hàng chính thức của ứng dụng này sẽ bật lên
>>>>Effects of having list above enabled without mas-ext.amazon.com on whitelist:
When user tries to download any new app on firestick from official app store this will pop up
![image](https://user-images.githubusercontent.com/38442058/55558006-0333e700-56a0-11e9-84d0-80242dcb8eab.png)
Không thể tải về các ứng dụng trên firestick
>>>> Can not download apps on firestick

Tác dụng của whitelisting:
>>>>Effects of whitelisting:
![image](https://user-images.githubusercontent.com/38442058/55558026-0a5af500-56a0-11e9-979c-5ff25a608111.png)

Có thể tải ứng dụng trên firestick
>>>> Can download apps on firestick

Uy tín người khác đã xác nhận điều này:
>>>>Credibility others have verified this:
https://github.com/jerryn70/GoodbyeAds/issues/13
https://github.com/EnergizedProtection/block/issues/110

Tôi tìm thấy danh sách của bạn trên https://github.com/jerryn70/GoodbyeAds/issues/12
>>>>I found your list on https://github.com/jerryn70/GoodbyeAds/issues/12

**Comment by bigdargon** [comment]
Thanks you!
