### ISSUE TITLE
Không xem được Youtube

### ISSUE THREAD

**Issue by babygau** [bigdargon/hostsVN#133]
Sau khi cài đặt Qualtumult như hướng dẫn, mình không thể xem video trên Youtube app. Nếu để chế độ Direct thì xem lại được. Mình nghĩ có vấn đề với bộ lọc.

**Comment by bigdargon** [comment]
Chào bạn! Do Quantumult chặn mạnh mẽ quá nên GG đã fix API để hiện qc làm cho video k load được! Vấn đề gặp phải là máy của mình k dính qc đầu video nên khó test được.

**Comment by babygau** [comment]
Mình cũng đag xài Youtube Premium, mình nghĩ sẽ ko bị lọc quảng cáo, có cách nào truy vấn lỗi để bạn kiểm tra đc ko

**Comment by bigdargon** [comment]
Nếu bạn k muốn lọc qc của Youtube chỉ cần tắt tính năng HTTPS đi là được!

**Comment by babygau** [comment]
Tks bạn, tạm thời mình dùng Direct mode khi sử dụng Youtube. Hi vọng lỗi sẽ đc fix sớm.

**Comment by babygau** [comment]
Hình như lỗi đã đc sửa tạm thời sau khi mình cập nhật lại. Cảm ơn @bigdargon nhiều 👍

**Comment by bigdargon** [comment]
Đúng rồi bạn! Tạm thời mình đã gỡ bộ lọc liên quan đến chặn youtube để mọi người có thể sử dụng bình thường. Vấn đề chặn mình sẽ theo dõi và fix sau!

**Comment by bigdargon** [comment]
@babygau bạn cho mình xin ít thông tin sau khi cập nhật lại cấu hình nhé! Sau khi cập nhật ứng dụng Youtube có hiện quảng cáo đầu video không? Và quảng cáo giữa video khi đang xem có xuất hiện k?

**Comment by babygau** [comment]
@bigdargon, mình hiện đag xài Youtube Premium nên ads không hiển thị khi xem clips. Mình có thử sign out và sử dụng Youtube Free thì ads vẫn thỉnh thoảng xuất hiện ở đầu và cuối clips

**Comment by bigdargon** [comment]
Thanks bạn! Việc đầu và cuối clip thì lúc mình làm ban đầu đã chặn đc đoạn qc giữa clip, sau này mới bổ sung chặn đầu và cuối clip. Giờ chắc có vẻ gg đã fix nên k còn chặn như trước, nên tạm thời vậy đã khi nào đc mình update vào sau!
