### ISSUE TITLE
[BỔ SUNG] Tên miền chặn ads trên crunchyroll

### ISSUE THREAD

**Issue by babygau** [bigdargon/hostsVN#137]
App: Crunchyroll

OS: iOS

Location: Australia

Ads host:

```
5fd74.v.fwmrm.net
```

**Comment by bigdargon** [comment]
Thanks bạn! Có vẻ tên miền này hơi nhiều subdomain, mình sẽ cập nhật vào lần cập nhật kế tiếp nhé!

**Comment by babygau** [comment]
@bigdargon, thank you!
