### ISSUE TITLE
Hỗ trợ nextdns.io

### ISSUE THREAD

**Issue by babygau** [bigdargon/hostsVN#138]
@bigdargon bạn có thể yêu cầu nextdns.io hỗ trợ adhost list của bạn không?

**Comment by bigdargon** [comment]
Để mình thử liên hệ với họ! Dịch vụ này cũng hay nhỉ, thanks bạn đã chia sẻ

**Comment by babygau** [comment]
Tks @bigdargon!

**Comment by bigdargon** [comment]
nextdns.io đã thêm rồi @babygau 
![2D698726-E340-47E0-9B1C-0EF537F6AB39](https://user-images.githubusercontent.com/10969626/58751099-46ee7580-84c4-11e9-9a35-973a6cbe2378.png)

**Comment by babygau** [comment]
Tuyệt vời, tks heaps @bigdargon. Giờ có thể dùng dns chặn ads cho cả gia đình được rồi!
