### ISSUE TITLE
Siri broken!

### ISSUE THREAD

**Issue by babygau** [bigdargon/hostsVN#139]
@bigdargon, hiện tại mình không thể sử dụng Siri khi bật Quantulmult. Nếu tắt thì Siri hoatk động bình thường.

**Comment by bigdargon** [comment]
Để mình kiểm tra nha bạn!

**Comment by bigdargon** [comment]
Bạn chụp hay quay màn hình lỗi giúp mình để mình kiểm tra được k? Mình đã test và vẫn bình thường!
![BAC77089-F2EF-4E10-8DC7-DCEB49629704](https://user-images.githubusercontent.com/10969626/58747667-98810b00-8498-11e9-87ff-5ef438c85062.png)
![C9287697-C73F-46E6-811C-6402435F335C](https://user-images.githubusercontent.com/10969626/58747668-9919a180-8498-11e9-9f77-ff88db42a32e.png)
![D132C89B-3D2E-495B-84EA-DFFD652A16E7](https://user-images.githubusercontent.com/10969626/58747670-99b23800-8498-11e9-910e-b063d8cf0281.png)

**Comment by babygau** [comment]
Tks bạn, mình đã kiểm tra lại, bây giờ Siri lại hoạt động bình thường. 

Nhiều lúc đang lái xe dùng Siri để gọi điện thoại cho người thân thì không nhận diện được giọng nói 

![Image](https://i.imgur.com/5zUnp8R.jpg)

**Comment by bigdargon** [comment]
Có thể khi đang di chuyển, kết nối mạng bị yếu nên dữ liệu giọng nói k gửi được lên server phân tích, hoặc k có phản hồi từ máy chủ nên vậy.

**Comment by babygau** [comment]
Thank you!
