### ISSUE TITLE
Lỗi không xem camera được trên app ivideon!

### ISSUE THREAD

**Issue by quylnn** [bigdargon/hostsVN#141]
![Uploading 64371968_379851299547871_2093672677058281472_n.jpg…]()

**Comment by bigdargon** [comment]
Bạn dẫn link ứng dụng và cập nhật lại hình lỗi giúp mình

**Comment by bigdargon** [comment]
@quylnn bạn kiểm tra lại đường truyền mạng và thiết bị camera nhé! Mình đã test và k có vấn đề gì khi xem video
![48804E17-46D5-432F-8F9F-7B0D8A3B336A](https://user-images.githubusercontent.com/10969626/59361578-4a072280-8d5c-11e9-8378-2d5293bf0b8f.png)
![FC7AA9E2-F27B-4C59-A169-EB6FB77235B3](https://user-images.githubusercontent.com/10969626/59361580-4a072280-8d5c-11e9-8e4f-ed1f0bb88547.png)
![18738663-EF23-4A50-ACA8-3FBA331C37A8](https://user-images.githubusercontent.com/10969626/59361581-4a9fb900-8d5c-11e9-9dd8-9d774ab341d9.png)
![1EE212DB-22AF-466F-8A1D-CE73CCA6AA12](https://user-images.githubusercontent.com/10969626/59361582-4a9fb900-8d5c-11e9-8604-efc3aeb75e8d.png)

**Comment by quylnn** [comment]
Của e xài k được bro ơi! Tắt surge đi thì xem bình thường.

[Image]
[Image]
Tải Outlook for iOS<https://aka.ms/o0ukef>

________________________________
Từ: BigDargon <notifications@github.com>
Đã gửi: Thứ Tư, tháng 6 12, 2019 9:53 CH
Tới: bigdargon/hostsVN
Cc: quylnn; Mention
Chủ đề: Re: [bigdargon/hostsVN] Lỗi không xem camera được trên app ivideon! (#141)


@quylnn<https://github.com/quylnn> bạn kiểm tra lại đường truyền mạng và thiết bị camera nhé! Mình đã test và k có vấn đề gì khi xem video
[48804E17-46D5-432F-8F9F-7B0D8A3B336A]<https://user-images.githubusercontent.com/10969626/59361578-4a072280-8d5c-11e9-8378-2d5293bf0b8f.png>
[FC7AA9E2-F27B-4C59-A169-EB6FB77235B3]<https://user-images.githubusercontent.com/10969626/59361580-4a072280-8d5c-11e9-8e4f-ed1f0bb88547.png>
[18738663-EF23-4A50-ACA8-3FBA331C37A8]<https://user-images.githubusercontent.com/10969626/59361581-4a9fb900-8d5c-11e9-9dd8-9d774ab341d9.png>
[1EE212DB-22AF-466F-8A1D-CE73CCA6AA12]<https://user-images.githubusercontent.com/10969626/59361582-4a9fb900-8d5c-11e9-8604-efc3aeb75e8d.png>

**Comment by bigdargon** [comment]
@quylnn bạn vui lòng chụp log của ứng dụng surge khi apps bị lỗi giúp mình!

**Comment by quylnn** [comment]
Đây ạ!

[Image][Image][Image]
Tải Outlook for iOS<https://aka.ms/o0ukef>

________________________________
Từ: BigDargon <notifications@github.com>
Đã gửi: Thứ Sáu, tháng 6 14, 2019 8:41 CH
Tới: bigdargon/hostsVN
Cc: quylnn; Mention
Chủ đề: Re: [bigdargon/hostsVN] Lỗi không xem camera được trên app ivideon! (#141)


Reopened #141<https://github.com/bigdargon/hostsVN/issues/141>.

**Comment by quylnn** [comment]
Với mình vào app Google Home/Routine cũng bị lỗi này nữa. Tắt surge đi thì k lỗi.

[Image]
[Image]


Tải Outlook for iOS<https://aka.ms/o0ukef>

________________________________
Từ: Ngọc Quý <lnnquy1993@gmail.com>
Đã gửi: Thứ Bảy, tháng 6 15, 2019 12:35 SA
Tới: bigdargon/hostsVN; bigdargon/hostsVN
Cc: Mention
Chủ đề: Re: [bigdargon/hostsVN] Lỗi không xem camera được trên app ivideon! (#141)

Đây ạ!

[Image][Image][Image]
Tải Outlook for iOS<https://aka.ms/o0ukef>

________________________________
Từ: BigDargon <notifications@github.com>
Đã gửi: Thứ Sáu, tháng 6 14, 2019 8:41 CH
Tới: bigdargon/hostsVN
Cc: quylnn; Mention
Chủ đề: Re: [bigdargon/hostsVN] Lỗi không xem camera được trên app ivideon! (#141)


Reopened #141<https://github.com/bigdargon/hostsVN/issues/141>.

**Comment by bigdargon** [comment]
Không thấy được ảnh bạn ơi!

**Comment by bigdargon** [comment]
Do Surge chặn ngắt ngang kết nối nên khi chặn tên miền app-measurement.com dẫn đến apps k kết nối tiếp tục đến kết nối tiếp theo. Khi sử dụng ứng dụng bạn tắt vpn của Surge giúp mình vì do đây là tiên miền gắn mác theo dõi người dùng nên mình không gỡ!
