### ISSUE TITLE
Không đăng nhập Appstore được

### ISSUE THREAD

**Issue by zadezl** [bigdargon/hostsVN#145]
[//]: # (***Vui lòng nhập thông tin phía dưới dòng có dấu "[//]:" các dòng này sẽ bị ẩn khi đăng bài. Xin cám ơn!)

***Địa chỉ trang web/ứng dụng lỗi***: Appstore

* **Lỗi khi bật hosts**: Không đăng nhập tài khoản được

[//]: # (Thay thế %screenshot_url% bên dưới với địa chỉ hình ảnh báo lỗi. Ngoài ra, bạn có thể dán trực tiếp ảnh từ clipboard, chúng sẽ tự động được thêm vào.)

<details><summary>Ảnh chụp màn hình:</summary>

![image](https://i.imgur.com/qK0EID3.png)
</details><br/>

* **Khi không bật hosts**: đăng nhập bình thường

[//]: # (Thay thế %screenshot_url% bên dưới với địa chỉ hình ảnh khi không sử dụng hosts. Nếu cần, hãy cung cấp ảnh chụp màn hình bên dưới, giống như trên)

<details><summary>Ảnh chụp màn hình:</summary>

![image](%url_of_screenshot%)
</details><br/>

[//]: # (Mô tả chi tiết (nếu có) để lỗi được xử lý nhanh hơn!)
Mình dùng Quantumlt

**Comment by bigdargon** [comment]
Bạn vào chỗ edit > tìm dòng HOST,buy.itunes.apple.com,FakeIAP sau đó xoá đi! Và tạm thời đừng update mới, do sử dụng server để fake vip của một số apps!

**Comment by bigdargon** [comment]
@zadezl đã fix! Bạn update lại config kiểm tra còn lỗi không nhé!

**Comment by zadezl** [comment]
@bigdargon mấy hôm nay bận quá quên ko check mail, mình test không còn thấy lỗi gì nữa cảm ơn bạn nhé :D
