### ISSUE TITLE
Không vào được Netflix

### ISSUE THREAD

**Issue by heroes1412** [bigdargon/hostsVN#149]
[//]: # (***Vui lòng nhập thông tin phía dưới dòng có dấu "[//]:" các dòng này sẽ bị ẩn khi đăng bài. Xin cám ơn!)

***Địa chỉ trang web/ứng dụng lỗi***: netflix.com

* **Lỗi khi bật hosts**: Không xem phim được trên netflix trên ios và android khi chép đè file host

[//]: # (Thay thế %screenshot_url% bên dưới với địa chỉ hình ảnh báo lỗi. Ngoài ra, bạn có thể dán trực tiếp ảnh từ clipboard, chúng sẽ tự động được thêm vào.)

<details><summary>Ảnh chụp màn hình:</summary>

![image](%screenshot_url%)
</details><br/>

* **Khi không bật hosts**: 

[//]: # (Thay thế %screenshot_url% bên dưới với địa chỉ hình ảnh khi không sử dụng hosts. Nếu cần, hãy cung cấp ảnh chụp màn hình bên dưới, giống như trên)

<details><summary>Ảnh chụp màn hình:</summary>

![image](%url_of_screenshot%)
</details><br/>

[//]: # (Mô tả chi tiết (nếu có) để lỗi được xử lý nhanh hơn!)
***Chi tiết***:

**Comment by bigdargon** [comment]
@heroes1412 Chào bạn! Hiện tại mình không có tài khoản netflix nên không thể dò lỗi được!

**Comment by heroes1412** [comment]
Mình tự bỏ các domain .netlix.com đi thì xem ok r b, mà mình nghĩ netflix cũng k public quảng cáo đâu nên k cần chặn.

**Comment by bigdargon** [comment]
@heroes1412 Cám ơn bạn đã báo lỗi! Mình sẽ gỡ và update lại hosts :smiley:
