### ISSUE TITLE
Không tải được ứng dụng trên playstore khi apply host bằng Adaway

### ISSUE THREAD

**Issue by ryusica** [bigdargon/hostsVN#150]
[//]: # (***Vui lòng nhập thông tin phía dưới dòng có dấu "[//]:" các dòng này sẽ bị ẩn khi đăng bài. Xin cám ơn!)

***Địa chỉ trang web/ứng dụng lỗi***: Playstore

* **Lỗi khi bật hosts**: không tải được ứng dụng. Luôn hiển thị chờ tải xuống

[//]: # (Thay thế %screenshot_url% bên dưới với địa chỉ hình ảnh báo lỗi. Ngoài ra, bạn có thể dán trực tiếp ảnh từ clipboard, chúng sẽ tự động được thêm vào.)

<details><summary>Ảnh chụp màn hình:</summary>

![image](%screenshot_url%)
</details><br/>

* **Khi không bật hosts**: tải bình thường

[//]: # (Thay thế %screenshot_url% bên dưới với địa chỉ hình ảnh khi không sử dụng hosts. Nếu cần, hãy cung cấp ảnh chụp màn hình bên dưới, giống như trên)

<details><summary>Ảnh chụp màn hình:</summary>

![image](%url_of_screenshot%)
</details><br/>

***Chi tiết***:
Mình dùng adaway để apply host.

**Comment by bigdargon** [comment]
Bạn đang dùng link gốc github hay của abpvn?

**Comment by ryusica** [comment]
Mình dùng link trên abpvn. Trong hướng dẫn dùng adaway trên github mình thấy cũng giống trên abpvn

**Comment by bigdargon** [comment]
Ok! Mai mình sẽ update adway trên box android rồi kiểm tra.

**Comment by bigdargon** [comment]
@ryusica Bạn cập nhật lại list của adway và kiểm tra xem còn lỗi không?
