### ISSUE TITLE
web cá độ bóng đá

### ISSUE THREAD

**Issue by vhpcdpgl** [bigdargon/hostsVN#151]
[//]: # (***Vui lòng nhập thông tin phía dưới dòng có dấu "[//]:" các dòng này sẽ bị ẩn khi đăng bài. Xin cám ơn!)

[//]: # (Nếu bạn muốn thêm tên miền mới, vui lòng đưa tên miền vào thẻ bên dưới.)
Các trang web cá độ bóng đá. Mình đang test thử và thấy là những trang dưới đây chưa bị lọc bởi hostsVN
***Tên miền***:
```
8live.net
thethaofb88.com
fb88sports.com
mybookie.ag
oneday88.com
fabetvn.com
cadovn88.com
fblink88vn.com
w88clubvip.com
fb88blog.com
fb88en.com
fb88go.com
w88tel.com
fb88live.com
w88coid.com
ibet889.com
bong88net.com
fb88.blog
fun88gg.com
keocopa.com
88betting.net
vn88.biz
vlott88.com
cachvaom88.net
bettingtop10.com
fun88linkvao.com
cachvaom88.net
w88hn.vip
w88linkvao.com
w88vao.com
w88.vin
w88no1.com
w88vn.co
ww88club.com
w88club.com
cachvaom88.net
w88coid.com
sieubet.com
casinobillions.com
top10nhacaiviet.com
thethaobet.com
qq8878.org
```

**Comment by bigdargon** [comment]
Thanks bạn đã báo cáo! Mình sẽ cập nhật sớm nhất có thể

**Comment by vhpcdpgl** [comment]
> Thanks bạn đã báo cáo! Mình sẽ cập nhật sớm nhất có thể

Vâng bạn, mình cũng đã cập nhật danh sách ở trên rồi đó.

**Comment by vhpcdpgl** [comment]
Theo thiển ý của mình bạn nên tạo thêm một bộ lọc gambling chặn bọn website cá độ (tiếng Việt). Các website tiếng Anh thì hầu như bị chặn gần hết nhưng các website cá độ tiếng Việt thì hầu như ít ai quan tâm.

**Comment by bigdargon** [comment]
Các trang web dạng 1 phần có chèn quảng cáo từ tên miền đó, 1 phần cũng là các trang web cá độ. Do vậy tích hợp thằng vào hosts chứ tách ra thêm lựa chọn sẽ hơi rối!

**Comment by bigdargon** [comment]
Thanks bạn! Kiểu như nó là dạng blog tổng hợp link để né tránh luật và chỉ dẫn link. Mình sẽ theo dõi và thêm vào!

P/s: Làm sao bạn ẩn được thớt này được vậy? Cập nhật vừa rồi mình vào lại thì mất tiêu, giờ lại hiện ra!

**Comment by vhpcdpgl** [comment]
Mình không ẩn mà là không hiểu sao bị khóa tài khoản. Sau khi khiếu nại thì được mở lại tài khoản, có lẽ khi tk bị khóa thì bài bị ẩn đi. ;)
> P/s: Làm sao bạn ẩn được thớt này được vậy? Cập nhật vừa rồi mình vào lại thì mất tiêu, giờ lại hiện ra!
