### ISSUE TITLE
Cảm ơn bạn!

### ISSUE THREAD

**Issue by StevenBlack** [bigdargon/hostsVN#160]
Hey, I just want to say: THANK YOU!

@bigdargon you do amazing work curating this list.  Every time I release a new version, you have updates, too.  I scan all your changes, and I know you take this seriously.

Chúc sức khỏe cho bạn!

**Comment by bigdargon** [comment]
Hi @StevenBlack !

I am planning to add a list to block social networking and gambling in Vietnam.  The list is currently sketchy but I'll try to get it done!

**Comment by sonarypt** [comment]
@bigdargon May I join you? I am currently working on a list of porn sites from Vietnam. HostVN would be more comprehensive when we have porn lists too.

**Comment by bigdargon** [comment]
@sonarypt You seem to be Vietnamese?  Please join the discord to discuss with me  https://discord.gg/AaXNZJS
