### ISSUE TITLE
Chặn host QC trên các trang download.com.vn, quantrimang.com, gamevui.vn, vndoc.com

### ISSUE THREAD

**Issue by vhpcdpgl** [bigdargon/hostsVN#163]
[//]: # (***Vui lòng nhập thông tin phía dưới dòng có dấu "[//]:" các dòng này sẽ bị ẩn khi đăng bài. Xin cám ơn!)

[//]: # (Nếu bạn muốn thêm tên miền mới, vui lòng đưa tên miền vào thẻ bên dưới.)

***Tên miền***:
```
realclick.vn
www.realclick.vn
```
Các link quảng cáo trỏ về trang meta.vn

**Comment by vhpcdpgl** [comment]
Hình như nó còn có cái domain này nữa:
`s.adrealclick.com`

**Comment by bigdargon** [comment]
@vhpcdpgl đúng rồi bạn! Mình chuẩn bị update
