### ISSUE TITLE
Chặn host video QC trên motphim.net

### ISSUE THREAD

**Issue by vhpcdpgl** [bigdargon/hostsVN#168]
[//]: # (***Vui lòng nhập thông tin phía dưới dòng có dấu "[//]:" các dòng này sẽ bị ẩn khi đăng bài. Xin cám ơn!)

[//]: # (Nếu bạn muốn thêm tên miền mới, vui lòng đưa tên miền vào thẻ bên dưới.)

***Tên miền***:
```
an.motphim.net
```
Ví dụ: `https://an.motphim.net/cvast.xml?pub=motphim.net&origin=https://motphim.net/xem-phim/cong-tu-ta-cuoi-chang-chac-roi-tap-3-7860_99494.html`
Theo thiển ý của mình, **Cvast.xml** có thể là custom VAST XML (video ads serving template) đóng vai trò phân phối đoạn QC. Xem thêm: `https://developer.jwplayer.com/jwplayer/docs/jw8-create-a-custom-vast-xml-ad-tag`

**Comment by vhpcdpgl** [comment]
Vd khác: Phần Decoded results của source
một trang xem phim chứa cả đống QC: `http://ddecode.com/hexdecoder/?results=a0196ee03743bdaf4d44964286a06f39`

**Comment by bigdargon** [comment]
@vhpcdpgl thanks bạn! Mình cũng đang tìm mấy trang để giải mã, có một số script mã hoá mình k biết nó chứa gì.

**Comment by vhpcdpgl** [comment]
Vâng bạn, nhưng rule bộ lọc của ABPVN chắc không xài cho chặn domain bằng DNS được.

**Comment by bigdargon** [comment]
Hầu hết những máy chủ ở trên mình đã lọc đưa vào `hostsVN` rồi đó bạn!
