### ISSUE TITLE
Chặn QC trên hatde.tv

### ISSUE THREAD

**Issue by vhpcdpgl** [bigdargon/hostsVN#170]
[//]: # (***Vui lòng nhập thông tin phía dưới dòng có dấu "[//]:" các dòng này sẽ bị ẩn khi đăng bài. Xin cám ơn!)

[//]: # (Nếu bạn muốn thêm tên miền mới, vui lòng đưa tên miền vào thẻ bên dưới.)

***Tên miền***:
```
seaboblit.com
```
Cái này được Privacy Badger phát hiện là tracker. Mình dùng NextDNS để lọc nó thì trên trang xem phim hatde.tv không còn thấy video qc hoặc thông báo anti-adblock nữa.

**Comment by bigdargon** [comment]
Link chứa ads
```
https://seaboblit.com/1clkn/12909
```

**Comment by vhpcdpgl** [comment]
> Link chứa ads
> 
> ```
> https://seaboblit.com/1clkn/12909
> ```

Làm cách nào bạn tìm được cái này hay thế? ;)

**Comment by vhpcdpgl** [comment]
Cùng ổ của nó và bobvetgel.com còn có twokidjay.com nữa. 3 thằng sinh 3 cùng ngày, cùng IP (IP thay đổi 3 lần như nhau luôn). Thằng twokidjay.com hình như bị Adguard cho vào blacklist rồi.

**Comment by bigdargon** [comment]
> Cùng ổ của nó và bobvetgel.com còn có twokidjay.com nữa. 3 thằng sinh 3 cùng ngày, cùng IP (IP thay đổi 3 lần như nhau luôn). Thằng twokidjay.com hình như bị Adguard cho vào blacklist rồi.

Đã bổ sung thêm `twokidjay.com`
