### ISSUE TITLE
Chặn QC trên kingphim.net

### ISSUE THREAD

**Issue by vhpcdpgl** [bigdargon/hostsVN#174]
[//]: # (***Vui lòng nhập thông tin phía dưới dòng có dấu "[//]:" các dòng này sẽ bị ẩn khi đăng bài. Xin cám ơn!)

[//]: # (Nếu bạn muốn thêm tên miền mới, vui lòng đưa tên miền vào thẻ bên dưới.)

***Tên miền***:
```
iab.net
iab.com
iabtechlab.com
iabuk.com
iabseaindia.com
newfrontswest.com
iabeurope.eu
```
Script: `http://ssl.p.jwpcdn.com/player/plugins/googima/v/8.5.16/googima.js`

**Comment by bigdargon** [comment]
Trong list bạn đưa có `iab.net` và `iabtechlab.com` có thể có chứa quảng cáo do có tên miền con cdn và api. Còn lại chỉ là dạng trang giới thiệu.
