### ISSUE TITLE
Chặn host chứa sript QC trên hatde.tv

### ISSUE THREAD

**Issue by vhpcdpgl** [bigdargon/hostsVN#177]
[//]: # (***Vui lòng nhập thông tin phía dưới dòng có dấu "[//]:" các dòng này sẽ bị ẩn khi đăng bài. Xin cám ơn!)

[//]: # (Nếu bạn muốn thêm tên miền mới, vui lòng đưa tên miền vào thẻ bên dưới.)

***Tên miền***:
```
dimfarlow.com
```
Script:

```
<script type="text/javascript" src="//vn-platform.bidgear.com/ads.php?domainid=2809&sizeid=16&zoneid=4325&k=5e82fa3e602b4"></script>
<script data-cfasync="false" type="text/javascript" src="//dimfarlow.com/rsbzzlq7oG5Dh1/20102"></script>
<script data-cfasync="false" async type="text/javascript" src="//seaboblit.com/1clkn/12909"></script>
<script>SmartPopunder.make('https://bit.ly/2TOGGsX', {cookieExpires: 60 * 2});</script>
<script>SmartPopunder.make('https://bit.ly/2vcZat6', {cookieExpires: 60 * 2});</script>
```

**Comment by bigdargon** [comment]
@vhpcdpgl tên miền bit.ly chặn thì link rút gọn sẽ k truy cập được, chặn bằng bộ lọc sẽ hiệu quả hơn.
```
https://hatde.tv/assets/popup.js
```

**Comment by vhpcdpgl** [comment]
Giờ lại gặp cái anti-adblock này mà chưa có cách trị nó:
`https://www.upsieutoc.com/images/2020/04/17/Hatde.tv.png`

**Comment by bigdargon** [comment]
cái này do player của web nhúng vào thay đổi cách chặn, giờ phải report cho bộ lọc fix mới đc
