### ISSUE TITLE
Chặn QC trên App Tin Mới 24h

### ISSUE THREAD

**Issue by vhpcdpgl** [bigdargon/hostsVN#179]
[//]: # (***Vui lòng nhập thông tin phía dưới dòng có dấu "[//]:" các dòng này sẽ bị ẩn khi đăng bài. Xin cám ơn!)

[//]: # (Nếu bạn muốn thêm tên miền mới, vui lòng đưa tên miền vào thẻ bên dưới.)

***Tên miền***:
```
r.tinmoi24.vn
cdn24hmoney.24hstatic.com
24hmoney.24hstatic.com
eva-m-ad.24hstatic.com
24h-ad.24hstatic.com
nv-ad.24hstatic.com
```
***Địa chỉ app Tin Mới 24h trên Google Play***:
```
https://play.google.com/store/apps/details?id=mobi.fiveplay.tinmoi24h
```

**Comment by bigdargon** [comment]
Mình k có máy android sao test đây 😄

**Comment by vhpcdpgl** [comment]
Cái `r.tinmoi24.vn` có tác dụng mở các trang _tin tài trợ_, gồm các loại thực phẩm chức năng, thuốc tăng cường sinh lực hầm bà lằng...
