### ISSUE TITLE
Chặn QC trên kenh14.vn

### ISSUE THREAD

**Issue by vhpcdpgl** [bigdargon/hostsVN#182]
[//]: # (***Vui lòng nhập thông tin phía dưới dòng có dấu "[//]:" các dòng này sẽ bị ẩn khi đăng bài. Xin cám ơn!)

[//]: # (Nếu bạn muốn thêm tên miền mới, vui lòng đưa tên miền vào thẻ bên dưới.)

***Tên miền***:
```
`kenh14s.cnnd.vn`
`lg.nanda.vn`
```
Script:
`https://kenh14s.cnnd.vn/Handler/GetExtendParamSocial.ashx?c=adtechviewcountgetlist&from=Home+k14Flat&lstNewsIds=20191207082133035%253B20191206102924332%253B20191206090254223`

`https://kenh14s.cnnd.vn/Handler/GetExtendParamSocial.ashx?c=adtechviewcountgetlist&from=.trendAd-left&lstNewsIds=20191207082133035%253B20191206102924332%253B20191206090254223`

`http://lg.nanda.vn/mapid?src=admicro&dguid=e02f6d2b559e92c3105447591363cc42&3guid=`

Tham khảo: `https://cdn.osano.com/hubfs/visitor_files/audits/b99e425d7678515569e11b34db9d5eed1a7795de-ff68a12a4870c9f2adda63f9928a7f36100a8311.pdf`

_Updating..._

**Comment by bigdargon** [comment]
Cái `cnnd.vn` bạn check xem sub domain ở trang khác khác chặn có lỗi gì k? Mình thấy có thể nên chặn cả dãy, đọc báo mà tracking nhiều quá

**Comment by vhpcdpgl** [comment]
Domain `cnnd.vn` có tới 110 subdomains, tạm thời chặn thử thì chưa thấy lỗi. Cần test thêm trên các trang khác nữa.
List domains:
`https://securitytrails.com/list/apex_domain/cnnd.vn`

**Comment by vhpcdpgl** [comment]
Chặn cả dãy `cnnd.vn` là OK đó bạn.
Mình test mấy báo khác thì ko thấy ảnh hưởng gì phần nội dung tin/hình ảnh.
`https://www.upsieutoc.com/images/2020/04/30/20200430_145721.jpg`

**Comment by vhpcdpgl** [comment]
Riêng thằng nanda.vn dường như mới xuất hiện, mở  baomoi cũng thấy truy vấn tới nó. Có lẽ nó là domain của admicro.
