### ISSUE TITLE
Chặn QC trên baomoi.com

### ISSUE THREAD

**Issue by vhpcdpgl** [bigdargon/hostsVN#183]
[//]: # (***Vui lòng nhập thông tin phía dưới dòng có dấu "[//]:" các dòng này sẽ bị ẩn khi đăng bài. Xin cám ơn!)

[//]: # (Nếu bạn muốn thêm tên miền mới, vui lòng đưa tên miền vào thẻ bên dưới.)

***Tên miền***:
```
`invite.baomoi.com`
```
Script:
Ex: `https://invite.baomoi.com/share?redirect=https%3A%2F%2Fbaomoi.onelink.me%2FDfp0%2F22e3360f`

`wg.zaloapp.com`

Script:
Ex: `https://wg.zaloapp.com/m/sdk/adtima/follow/token`

`lp.baomoi.com`
Cái này đi kèm với `log.baomoi.com`

_Updating..._

**Comment by vhpcdpgl** [comment]
Thêm cái `wg.zaloapp.com` nữa bạn nhé.

**Comment by bigdargon** [comment]
K thấy bạn để trong ô nên k để ý
