### ISSUE TITLE
Chặn QC trên m.thethao247.vn

### ISSUE THREAD

**Issue by vhpcdpgl** [bigdargon/hostsVN#184]
[//]: # (***Vui lòng nhập thông tin phía dưới dòng có dấu "[//]:" các dòng này sẽ bị ẩn khi đăng bài. Xin cám ơn!)

[//]: # (Nếu bạn muốn thêm tên miền mới, vui lòng đưa tên miền vào thẻ bên dưới.)

***Tên miền***:
```
game.hotngay.vn
```
_QC này cũng xuất hiện trên app VNNGAYNAY.VN_

**Comment by bigdargon** [comment]
Cái qc của vnngaynay này lắm tên miền thật 😠

**Comment by vhpcdpgl** [comment]
> Cái qc của vnngaynay này lắm tên miền thật 😠 

Thằng này có quỹ nước ngoài đầu tư hẳn hoi. Mã nguồn thì nhiều đoạn viết bằng tiếng Tàu.
