### ISSUE TITLE
Chặn tracker/QC trên thethaovanhoa.vn

### ISSUE THREAD

**Issue by vhpcdpgl** [bigdargon/hostsVN#185]
[//]: # (***Vui lòng nhập thông tin phía dưới dòng có dấu "[//]:" các dòng này sẽ bị ẩn khi đăng bài. Xin cám ơn!)

[//]: # (Nếu bạn muốn thêm tên miền mới, vui lòng đưa tên miền vào thẻ bên dưới.)

***Tên miền***:
```
logs.thethaovanhoa.vn
v3.thethaovanhoa.vn
api.kinghub.vn
agroupadx.com
```
Thằng `api.kinghub.vn` bị xếp vào loại đáng ngờ vì nó load file của winrar về để thực thi cái gì đó. Nguồn: `https://any.run/report/7e76eefdad6a6e5a0d3e9fc5fea6c3b07de116042e69f2d158cdc98a6cf1cbd8/ef2adebd-8a37-481f-9607-f4fad874a7c9`
Nó cũng xuất hiện khi mở các trang trên kenh14.vn

**Comment by bigdargon** [comment]
Cái `api.kinghub.vn ` này k chặn được, nó để load video. Lúc trước mình có theo dõi nó rồi

**Comment by vhpcdpgl** [comment]
> Cái `api.kinghub.vn ` này k chặn được, nó để load video. Lúc trước mình có theo dõi nó rồi

Mình thử chặn nó thì video trên thethaovanhoa.vn và kenh14.vn vẫn chạy bình thường. Có vẻ như trước kia kinghub.vn là server chứa video, nhưng cái api.kinghub.vn này thì rất đáng ngờ.

**Comment by bigdargon** [comment]
> Mình thử chặn nó thì video trên thethaovanhoa.vn và kenh14.vn vẫn chạy bình thường. Có vẻ như trước kia kinghub.vn là server chứa video, nhưng cái api.kinghub.vn này thì rất đáng ngờ.

Nó dẫn thông tin như hình thumb và link video, chắc cần theo dõi thêm.

Về tên miền `v3.thethaovanhoa.vn` bạn dẫn mình thêm file js chứa quảng cáo, mình chỉ tìm được 1 số link chứa bình luận thôi

```
​https://v3.thethaovanhoa.vn/Minify/comment.js?t=637240423999194767
https://v3.thethaovanhoa.vn/Minify/comment.css?t=%3C%=DateTime.Now.Ticks%20%%3E
​https://v3.thethaovanhoa.vn/Minify/comment.js?t=637240423992632161
https://v3.thethaovanhoa.vn/comment2.htm?objId=6128&objType=2&objZoneId=575&domain=https://video.thethaovanhoa.vn&objUrl=https://video.thethaovanhoa.vn/nang-mi-hoang-thuy-linh-va-chang-duong-10-nam-hoi-sinh-manh-me-6128.htm&objTitle=JTIyTiVDMyVBMG5nJTIwTSVFMSVCQiU4QiUyMiUyMEhvJUMzJUEwbmclMjBUaCVDMyVCOXklMjBMaW5oJTIwdiVDMyVBMCUyMGNoJUUxJUJBJUI3bmclMjAlQzQlOTElQzYlQjAlRTElQkIlOURuZyUyMDEwJTIwbiVDNCU4M20lMjBoJUUxJUJCJTkzaSUyMHNpbmglMjBtJUUxJUJBJUExbmglMjBtJUUxJUJBJUJE
https://v3.thethaovanhoa.vn/captcha.htm?1588420409079
https://v3.thethaovanhoa.vn/comment2.htm?objId=6128&objType=2&objZoneId=575&domain=https://video.thethaovanhoa.vn&objUrl=https://video.thethaovanhoa.vn/nang-mi-hoang-thuy-linh-va-chang-duong-10-nam-hoi-sinh-manh-me-6128.htm&objTitle=JTIyTiVDMyVBMG5nJTIwTSVFMSVCQiU4QiUyMiUyMEhvJUMzJUEwbmclMjBUaCVDMyVCOXklMjBMaW5oJTIwdiVDMyVBMCUyMGNoJUUxJUJBJUI3bmclMjAlQzQlOTElQzYlQjAlRTElQkIlOURuZyUyMDEwJTIwbiVDNCU4M20lMjBoJUUxJUJCJTkzaSUyMHNpbmglMjBtJUUxJUJBJUExbmglMjBtJUUxJUJBJUJE
​https://v3.thethaovanhoa.vn/user-icon.htm
```

**Comment by vhpcdpgl** [comment]
> Về tên miền `v3.thethaovanhoa.vn` bạn dẫn mình thêm file js chứa quảng cáo, mình chỉ tìm được 1 số link chứa bình luận thôi

Cái này thì mình nhầm khi xem đoạn code trang video của nó:

```
<script type="text/javascript">
    var appSettings = {
        domain: "https://video.thethaovanhoa.vn",    
        ajaxDomain: "https://v3.thethaovanhoa.vn",
        
        videoplayer:"https://vcplayer.mediacdn.vn",
        imageStorage:"https://thethaovanhoa.mediacdn.vn",
        videoImageDomain: "https://video-thumbs.mediacdn.vn",
        sportApi: "http://s1.channelvn.net",
        allowAds: true
    };
    Object.freeze(appSettings);
</script>
```

**Comment by vhpcdpgl** [comment]
P/s: Bạn kiểm tra thử cái này có phải QC hay không:
`https://cdn.serving1.net/general.js`
Nguồn: `https://xepassion.thethaovanhoa.vn/`

**Comment by bigdargon** [comment]
> P/s: Bạn kiểm tra thử cái này có phải QC hay không:
> `https://cdn.serving1.net/general.js`
> Nguồn: `https://xepassion.thethaovanhoa.vn/`

Nó là tên miền quảng cáo, mình thấy tài liệu ở 2 địa chỉ này
```
http://developers.bucksense.com/
https://knowledgebase.mobileads.com/
```
