### ISSUE TITLE
Chặn QC/tracker trên kienthuc.net.vn

### ISSUE THREAD

**Issue by vhpcdpgl** [bigdargon/hostsVN#187]
[//]: # (***Vui lòng nhập thông tin phía dưới dòng có dấu "[//]:" các dòng này sẽ bị ẩn khi đăng bài. Xin cám ơn!)

[//]: # (Nếu bạn muốn thêm tên miền mới, vui lòng đưa tên miền vào thẻ bên dưới.)

***Tên miền***:
```
||moatads.com^
||addthisedge.com^
```

URL:
```
https://z.moatads.com/addthismoatframe568911941483/moatframe.js
https://v1.addthisedge.com/live/boost/pika_rock/_ate.track.config_resp
```

**Comment by bigdargon** [comment]
Tên miền `moatads.com` đã có rồi nha bạn!
