### ISSUE TITLE
Chặn tracker trên doisongphapluat.com

### ISSUE THREAD

**Issue by vhpcdpgl** [bigdargon/hostsVN#189]
[//]: # (***Vui lòng nhập thông tin phía dưới dòng có dấu "[//]:" các dòng này sẽ bị ẩn khi đăng bài. Xin cám ơn!)

[//]: # (Nếu bạn muốn thêm tên miền mới, vui lòng đưa tên miền vào thẻ bên dưới.)

***Tên miền***:
```
ipify.org
api.ipify.org
www.ipify.org

```
Hiện đang bị chặn bởi Easyprivacy và Lightswitch05-tracking-aggressive.

**Comment by bigdargon** [comment]
Tên miền `ipify.org` này mình sẽ không chặn với lý do:
- Trang web giới thiệu, api của họ chỉ để hiển thị IP và không lưu trữ thông tin đó. Và các dev sử dụng IP để lấy vị trí quốc gia nhằm tối ưu đến các CDN tăng trải nghiệm người dùng mà thôi. Nên không đáng lo ngại, nếu chúng ta duyệt web đã có bộ lọc chặn đi rồi!

- Tên miền nằm trong bộ hosts `Tracking Aggressive` tác giả cũng nói rõ khi sử dụng sẽ làm hỏng 1 số dịch vụ, trang web. Hiện tại mình chỉ sử dụng bộ hosts `Ads & Tracking`
Nguồn: https://github.com/lightswitch05/hosts#hosts
```
A very aggressive block list for tracking, geo-targeting, & ads. This list will likely break functionality, so do not use it unless you are willing to maintain your own whitelist. If you find something in this list that you think is a mistake, please open a ticket and we can discuss it. Keep in mind that this is an aggressive list.
```
