### ISSUE TITLE
False Positive: ocsp.apple.com

### ISSUE THREAD

**Issue by p1r473** [bigdargon/hostsVN#191]
This is the certificate validation server for apple
https://support.apple.com/en-us/HT210060

**Comment by bigdargon** [comment]
Most users in Vietnam install apps outside the Appstore and want to block certificate revocation. You can add whitelist to ignore. Thank you!

**Comment by bigdargon** [comment]
@p1r473 Fixed in PR #197. Sorry, blocking this domain may cause some Apple applications to not function properly (rather than blocking certificate revocation).
