### ISSUE TITLE
Không sử dụng dc internet khi sử dụng file host cho ios đã jailbreak

### ISSUE THREAD

**Issue by heroes1412** [bigdargon/hostsVN#195]
Đường dẫn tập tin hosts-iOS dành cho iOS (đã jailbreak):
https://raw.githubusercontent.com/bigdargon/hostsVN/master/option/hosts-iOS

Không sử dụng dc internet khi sử dụng file host cho ios đã jailbreak, hình như có vẻ là do file host quá dài và nặng thì phải, mình thử khôi phục lại file hosts với 300 domain thì lại vào mạng bình thường, mình dùng iphone 6s, ios 12.4

**Comment by bigdargon** [comment]
@heroes1412 Với iOS 12 trở lên bạn cần cập nhật tweak `LetMeBlock` lên bản mới nhất từ repo http://poomsmart.github.io/repo/ mới sử dụng được file hosts của iOS. hostsVN chỉ mới có 20k thôi bạn, trong khi tweak Mega UHB tới hơn 63k vẫn sử dụng bình thường!

**Comment by heroes1412** [comment]
thanks b, trước mình có cài LetMeBlock rồi, mà là bản cũ, update lên từ repo bạn chỉ thì ok rồi, bạn note lại trên trang chủ cho đỡ có ng bị như mình :D
