### ISSUE TITLE
Chặn trang web designervn.com

### ISSUE THREAD

**Issue by vhpcdpgl** [bigdargon/hostsVN#201]
[//]: # (***Vui lòng nhập thông tin phía dưới dòng có dấu "[//]:" các dòng này sẽ bị ẩn khi đăng bài. Xin cám ơn!)

[//]: # (Nếu bạn muốn thêm tên miền mới, vui lòng đưa tên miền vào thẻ bên dưới.)

***Tên miền***:
```
designervn.com
```
Trang này redirect tới trang `www.027copy.com` là trang cá cược tiếng Trung

**Comment by bigdargon** [comment]
@vhpcdpgl tên miền `designervn.com` hết hạn đăng ký nên bị TQ mua lại rồi chèn vào, nên mình chặn tên miền `027copy.com` này nhé
