### ISSUE TITLE
Chặn tracker trên baogiaothong.vn

### ISSUE THREAD

**Issue by vhpcdpgl** [bigdargon/hostsVN#204]
[//]: # (***Vui lòng nhập thông tin phía dưới dòng có dấu "[//]:" các dòng này sẽ bị ẩn khi đăng bài. Xin cám ơn!)

[//]: # (Nếu bạn muốn thêm tên miền mới, vui lòng đưa tên miền vào thẻ bên dưới.)

***Tên miền***:
```
thongke99.baogiaothong.vn
```

**Comment by bigdargon** [comment]
@vhpcdpgl Bạn đề xuất thêm rule này để chặn banner qc luôn
```
||cdn.baogiaothong.vn/upload/images/*ad_image/
```
