### ISSUE TITLE
Chặn QC/tracking trên webtruyen.com

### ISSUE THREAD

**Issue by vhpcdpgl** [bigdargon/hostsVN#209]
[//]: # (***Vui lòng nhập thông tin phía dưới dòng có dấu "[//]:" các dòng này sẽ bị ẩn khi đăng bài. Xin cám ơn!)

[//]: # (Nếu bạn muốn thêm tên miền mới, vui lòng đưa tên miền vào thẻ bên dưới.)

***Tên miền***:
```
media.cachlammoi.com
streaming.yeutre.vn
streaming.webnauan.vn
streaming.hervietnam.com.vn
```
**Links:**
```
media.cachlammoi.com/player/jwplayer/ads.php?b&pc&pre
media.cachlammoi.com/player/jwplayer/ads.php?l&pc&pre
streaming.yeutre.vn/media/ads.php?b&pc&pre
streaming.yeutre.vn/media/ads.php?l&pc&pre
streaming.yeutre.vn/tracking_yt.php
streaming.yeutre.vn/tracking_new.php
streaming.webnauan.vn/media/ads.php?y&pc&pre
streaming.webnauan.vn/media/ads.php?l&pc&pre
streaming.hervietnam.com.vn/media/ads.php

```
Sau khi test thử, mình thấy:
- Các domain chính `cachlammoi.com, yeutre.vn, webnauan.vn` đều không sử dụng các subdomain nêu trên,  ngoại trừ `hervietnam.com.vn` còn dùng subdomain `streaming.hervietnam.com.vn` để load video QC: `streaming.hervietnam.com.vn/media/jwp722/7.2.2/vast.js`
- Cả 4 subdomain đều load QC dạng frame và load tracking, riêng cái cuối cùng còn load QC dạng VAST.
- Ngoài ra, webtruyen.com cũng load QC/tracking từ `blueadss.com` và `adi.tuiiu.com` (đã bị chặn theo issue trước đây).
_Mình nghi ngờ rằng 4 subdomain và 4 domain chính nói trên đều thuộc 1 chủ sở hữu, và các subdomain đó chỉ dùng để load QC/tracking mà thôi._

**Comment by vhpcdpgl** [comment]
`streaming.yeutre.vn/tracking.php` còn xuất hiện trong page source của `santruyen.com`

**Comment by bigdargon** [comment]
Các tên miền này ở #207 mình đã check rồi, nếu chặn sẽ k load được video ở những bài có video. Với lại trong mã nguồn bạn để ý đầu dòng`//` là dòng code đó k có tác dụng, hiện tại trang đó dùng blueadss để hiện quảng cáo đó.
