### ISSUE TITLE
Chặn QC trên nghenhinvietnam.vn

### ISSUE THREAD

**Issue by vhpcdpgl** [bigdargon/hostsVN#212]
[//]: # (***Vui lòng nhập thông tin phía dưới dòng có dấu "[//]:" các dòng này sẽ bị ẩn khi đăng bài. Xin cám ơn!)

[//]: # (Nếu bạn muốn thêm tên miền mới, vui lòng đưa tên miền vào thẻ bên dưới.)

***Tên miền***:
```
ads.nghenhinvietnam.vn
s0.2mdn.net
```
_Cái thứ hai được nạp từ cái thứ nhất._

**Comment by bigdargon** [comment]
@vhpcdpgl Tên miền `s0.2mdn.net` đã có chặn rồi đó bạn!
