### ISSUE TITLE
shop.zalo.me

### ISSUE THREAD

**Issue by Alex-302** [bigdargon/hostsVN#214]
Hello
Why this domain is blocked?
One user says that it is incorrect blocking https://github.com/AdguardTeam/AdguardFilters/issues/57934

**Comment by bigdargon** [comment]
Hi @Alex-302 

Previously, Zalo used this domain to show ads for stores.  Now, perhaps learning from facebook, they have displayed both sales and advertising of the store.  Thanks for the announcement, I'll remove it!

**Comment by bigdargon** [comment]
Mentioned
https://github.com/AdAway/adaway.github.io/issues/89
https://github.com/notracking/hosts-blocklists/issues/382

**Comment by Alex-302** [comment]
Thanks!
