### ISSUE TITLE
Chặn tracker trên thoibao.com

### ISSUE THREAD

**Issue by vhpcdpgl** [bigdargon/hostsVN#223]
[//]: # (***Vui lòng nhập thông tin phía dưới dòng có dấu "[//]:" các dòng này sẽ bị ẩn khi đăng bài. Xin cám ơn!)

[//]: # (Nếu bạn muốn thêm tên miền mới, vui lòng đưa tên miền vào thẻ bên dưới.)

***Tên miền***:
```
infolinks.com
```

**Comment by bigdargon** [comment]
@vhpcdpgl Tên miền đã có trong bộ lọc rồi nha bạn!
