### ISSUE TITLE
cnnd.vn

### ISSUE THREAD

**Issue by S-a-l-a-d** [bigdargon/hostsVN#224]
Đào mộ #182 

Mình xem thử dữ liệu gửi đi và trả về của vài requests ở 2-3 trang báo thì thấy chỉ là dữ liệu để thống kê lượt xem, thích, không thích hoặc bình luận,... của bài đăng, clip.

Ngoài ra còn có trang sử dụng subdomain cho chức năng như Dân Việt dùng cho phần bình luận, Kenh14 hiện tại đang lấy dữ liệu Corona dùng cho widget.

**Ví dụ**
* https://danviet.vn/sinh-vien-my-dua-nhau-to-chuc-tiec-covid-19-xem-ai-bi-nhiem-virus-truoc-5020203721131787.htm
![Dân Việt](https://puu.sh/G3jUi/8495c85b71.png)
* https://kenh14.vn
![Kenh14 không chặn](https://puu.sh/G3jFC/71b31fec87.png)
![Kenh14 chặn](https://puu.sh/G3k58/446a6ff5c0.png)

Trên là subdomain có tên báo như danviets.cnnd.vn, kenh14s.cnnd.vn.

Còn đây là phần tracking:
```
logg4u.cnnd.vn
```
Một file script sẽ được lấy từ địa chỉ này theo đường dẫn: `https://logg4u.cnnd.vn/js/log.js`
Sau đó script này sẽ gửi request tới `https://logg4u.cnnd.vn/collect` gồm các thông tin như ngôn ngữ trình duyệt đang sử dụng, độ phân giải màn hình, tin đang đọc, chuyên mục, thẻ, GA Tracking ID.

### Kết luận
Như vậy trang cnnd.vn có vẻ là một trang thử nghiệm các giải pháp công nghệ, và các trang khác sử dụng giải pháp công nghệ của cnnd.vn có subdomain của cnnd.vn, có thể dùng cho chức năng trong trang và vô hại vì không gửi đi thông tin người dùng. Mình thấy hostsVN chặn Google Analytics nên có thể chặn `logg4u.cnnd.vn` là hợp lý, chặn nguyên domain thì sẽ ảnh hưởng chức năng.

**Comment by bigdargon** [comment]
@S-a-l-a-d Cám ơn bài phân tích chi tiết của bạn rất nhiều!
@vhpcdpgl Sẽ chặn subdomain chứ k chặn cả domain như đề xuất trước đây nha bạn!

**Comment by S-a-l-a-d** [comment]
Mình mới thấy live TV của VTV cũng dùng cho chức năng :D
https://vtv.vn/truyen-hinh-truc-tuyen.htm

**Comment by bigdargon** [comment]
Giờ tên miền này chèn API để load luôn video, nên sẽ chỉ chặn subdomain ở trên bạn đề xuất chắc là đủ rồi

**Comment by vhpcdpgl** [comment]
Vtv xài cái này:

```
vtvapi3.cnnd.vn
```

**Comment by bigdargon** [comment]
@vhpcdpgl Nếu chặn luôn cả tên miền chính thì chặn cả tên miền này => k load được player video trên trang vtv
