### ISSUE TITLE
Chặn tracker/QC trên phunuvagiadinh.vn

### ISSUE THREAD

**Issue by vhpcdpgl** [bigdargon/hostsVN#225]
[//]: # (***Vui lòng nhập thông tin phía dưới dòng có dấu "[//]:" các dòng này sẽ bị ẩn khi đăng bài. Xin cám ơn!)

[//]: # (Nếu bạn muốn thêm tên miền mới, vui lòng đưa tên miền vào thẻ bên dưới.)

***Tên miền***:
```
tracker.phunuvagiadinh.vn
adm.phunuvagiadinh.vn
```

**Comment by bigdargon** [comment]
Bổ sung tên miền này nữa `ads.phunuvagiadinh.vn`
