### ISSUE TITLE
Chặn tracker trên 24h.com.vn

### ISSUE THREAD

**Issue by vhpcdpgl** [bigdargon/hostsVN#226]
[//]: # (***Vui lòng nhập thông tin phía dưới dòng có dấu "[//]:" các dòng này sẽ bị ẩn khi đăng bài. Xin cám ơn!)

[//]: # (Nếu bạn muốn thêm tên miền mới, vui lòng đưa tên miền vào thẻ bên dưới.)

***Tên miền***:
```
track.kichmen1h.net
```

**Comment by bigdargon** [comment]
Trang này dạng landing quảng cáo nhưng mà đã xóa nội dung rồi, nên không có gì đáng ngại đâu bạn!
