### ISSUE TITLE
Chặn QC, tracker trên voz.vn

### ISSUE THREAD

**Issue by vhpcdpgl** [bigdargon/hostsVN#228]
[//]: # (***Vui lòng nhập thông tin phía dưới dòng có dấu "[//]:" các dòng này sẽ bị ẩn khi đăng bài. Xin cám ơn!)

[//]: # (Nếu bạn muốn thêm tên miền mới, vui lòng đưa tên miền vào thẻ bên dưới.)

***Tên miền***:
```
rekmob.com
advangelists.com
s3xified.com
quantumdex.io
```

**Comment by bigdargon** [comment]
voz dạo này nghỉ chơi qc của gg rồi nhỉ =))
