### ISSUE TITLE
Danh mục báo, tạp chí VN

### ISSUE THREAD

**Issue by vhpcdpgl** [bigdargon/hostsVN#229]
[//]: # (***Vui lòng nhập thông tin phía dưới dòng có dấu "[//]:" các dòng này sẽ bị ẩn khi đăng bài. Xin cám ơn!)

[//]: # (Hãy nhập nội dung mà bạn muốn thảo luận, rất cám ơn mọi ý kiến đóng góp của bạn!)

***Nội dung***:
```
https://mic.gov.vn/solieubaocao/Pages/TinTuc/142418/Ton-chi-muc-dich-cac-co-quan-bao-chi.html
```

**Comment by bigdargon** [comment]
Dò hết nhiêu tên miền đây chắc mệt à :D

**Comment by vhpcdpgl** [comment]
Danh sách URL:

```
https://raw.githubusercontent.com/vhpcdpgl/tabilu/master/VN_Newspaper_Magazine_Domain.txt
```

**Comment by beelyhot5** [comment]
Anh ơi em đang dùng file hostVN của anh trên Adguard Pro bản 4.0.2 mọi thứ đều chặn rất tốt nhưng file DNS khi bật chặn truy cập của 4G mobifone ạ. Lúc dùng được lúc không, nhưng tắt mục DNS lại dùng 4G bth, bật lên vào safari báo lỗi không tìm thấy máy chủ

**Comment by bigdargon** [comment]
@beelyhot5 Chào bạn! Hiện tại bản beta dev đã fix lỗi IPv6, các mạng 4G hiện nay đang sử dụng IPv6 là chủ yếu nên có thể đã dẫn đến lỗi. Tạm thời bạn chờ cập nhật bản 5.0.3 rồi kiểm tra xem có lỗi tương tự hay không? Nếu có mình sẽ hướng dẫn và hỗ trợ để bạn giúp mình báo cáo vấn đề cho Adguard nhé!

**Comment by beelyhot5** [comment]
> @beelyhot5 Chào bạn! Hiện tại bản beta dev đã fix lỗi IPv6, các mạng 4G hiện nay đang sử dụng IPv6 là chủ yếu nên có thể đã dẫn đến lỗi. Tạm thời bạn chờ cập nhật bản 5.0.3 rồi kiểm tra xem có lỗi tương tự hay không? Nếu có mình sẽ hướng dẫn và hỗ trợ để bạn giúp mình báo cáo vấn đề cho Adguard nhé!
> 
> P/s: Bạn cứ thoải mái tạo vấn đề mới nhé, mỗi issue như một task để mình theo dõi để tránh quên

Em cảm ơn ạ, do em chưa biết dùng github nên không biết làm thế nào để thông báo lỗi, anh thông cảm ạ. Anh cho em hỏi làm sao để biết version của file host và làm sao để biết nó đã cập nhập chưa ạ? E để ứng dụng tự động cập nhập chạy nền ạ
