### ISSUE TITLE
YouTube can't get rid of ads

### ISSUE THREAD

**Issue by Gollum916** [bigdargon/hostsVN#232]
YouTube can't get rid of ads

**Comment by Gollum916** [comment]
https://raw.githubusercontent.com/bigdargon/hostsVN/master/option/hostsVN-quantumultX-rewrite.conf
YouTube can't get rid of ads

**Comment by bigdargon** [comment]
You need to follow the instructions in the wiki article https://github.com/bigdargon/hostsVN/wiki/Quantumult-X
All the devices I'm using are still blocking ads!  Please follow the instructions, or record your screen and share the application log for me to check.
