### ISSUE TITLE
Chặn adsloads.com

### ISSUE THREAD

**Issue by vhpcdpgl** [bigdargon/hostsVN#233]
[//]: # (***Vui lòng nhập thông tin phía dưới dòng có dấu "[//]:" các dòng này sẽ bị ẩn khi đăng bài. Xin cám ơn!)

[//]: # (Nếu bạn muốn thêm tên miền mới, vui lòng đưa tên miền vào thẻ bên dưới.)

***Tên miền***:
```
adsloads.com
vn.adsloads.com
...
```
Bọn này có ít nhất 246 subdomain.

**Comment by bigdargon** [comment]
Đa số subdomain chủ yếu theo quốc gia, nên mình chỉ cần thêm vài sub chính. Thêm nhiều nặng file host không cần thiết lắm, xài rule thì chặn nhanh hơn!
