### ISSUE TITLE
QC chèn trong nhật ký của app Zalo

### ISSUE THREAD

**Issue by vhpcdpgl** [bigdargon/hostsVN#234]
[//]: # (***Vui lòng nhập thông tin phía dưới dòng có dấu "[//]:" các dòng này sẽ bị ẩn khi đăng bài. Xin cám ơn!)

[//]: # (Nếu bạn muốn thêm tên miền mới, vui lòng đưa tên miền vào thẻ bên dưới.)

***Tên miền***:
```
adtima-common.zadn.vn
broadcast.api.zaloapp.com
getpage.api.zaloapp.com
```

**Comment by bigdargon** [comment]
Tên miền `adtima-common.zadn.vn` mình sẽ thêm trước, còn 2 tên miền kia mình dùng MiTM để ktra lại rồi mới thêm sau!

**Comment by bigdargon** [comment]
@vhpcdpgl sau khi dùng MiTM kiểm tra được tên miền `getpage.api.zaloapp.com` được dùng để lấy danh sách bạn bè không có trong danh bạ

![image](https://user-images.githubusercontent.com/10969626/92087077-434b4c00-edf5-11ea-8f28-e8eab6145e0d.jpeg)

Còn về tên miền `broadcast.api.zaloapp.com` trong tài liệu hướng dẫn lập trình viên zalo dùng nó để đẩy bài viết đến client theo dõi (hoặc không theo dõi)

Do vậy chặn 2 tên miền này có thể gây lỗi truy cập tính năng của ứng dụng, nên mình chỉ thêm tên miền `adtima-common.zadn.vn`

**Comment by bigdargon** [comment]
@vhpcdpgl MiTM là can thiệp vào quá trình trao đổi dữ liệu mã hóa trên HTTPS, cái này bạn dùng Adguard trên android sau khi cài chứng chỉ chính là dùng MiTM để phân giải https để xem url có gì rồi lọc. iOS cũng vậy nhưng phải dùng app riêng
