### ISSUE TITLE
[Bug] Lỗi trên mạng 4G Mobifone

### ISSUE THREAD

**Issue by beelyhot5** [bigdargon/hostsVN#239]
> @beelyhot5 Chào bạn! Hiện tại bản beta dev đã fix lỗi IPv6, các mạng 4G hiện nay đang sử dụng IPv6 là chủ yếu nên có thể đã dẫn đến lỗi. Tạm thời bạn chờ cập nhật bản 5.0.3 rồi kiểm tra xem có lỗi tương tự hay không? Nếu có mình sẽ hướng dẫn và hỗ trợ để bạn giúp mình báo cáo vấn đề cho Adguard nhé!
> 
> P/s: Bạn cứ thoải mái tạo vấn đề mới nhé, mỗi issue như một task để mình theo dõi để tránh quên

Em cảm ơn ạ, do em chưa biết dùng github nên không biết làm thế nào để thông báo lỗi, anh thông cảm ạ. Anh cho em hỏi làm sao để biết version của file host và làm sao để biết nó đã cập nhập chưa ạ? E để ứng dụng tự động cập nhập chạy nền ạ

__Originally posted by @beelyhot5 in https://github.com/bigdargon/hostsVN/issues/229#issuecomment-689888844__

**Comment by bigdargon** [comment]
@beelyhot5 Hiện tại phiên bản beta v4.0.3 vẫn chưa được phát hành chính thức, để xem phiên bản bạn vào cài đặt của ứng dụng > chọn About sẽ thấy phiên bản bạn đang dùng

Về phần ứng dụng lỗi, bạn có đang sử dụng Adguard Pro chính chủ của bạn không? Nếu có bạn hãy xóa hoàn toàn ứng dụng, và thực hiện theo các bước trong bài wiki hướng dẫn https://github.com/bigdargon/hostsVN/wiki/Adguard-Pro. Đừng thêm bộ lọc nào khác rồi bạn bật VPN trên 4G Mobifone kiểm tra xem ứng dụng có lỗi hay k?

**Comment by beelyhot5** [comment]
@bigdargon e dùng bản Adguard chính chủ và làm như wiki hướng dẫn không hề thêm gì ạ

**Comment by bigdargon** [comment]
@beelyhot5 Bạn đang chọn chế độ Split-Tunnel hay Full-Tunnel trong cài đặt?

**Comment by beelyhot5** [comment]
@bigdargon  e chọn split ạ

**Comment by bigdargon** [comment]
@beelyhot5 Ok. Mình sẽ đăng ký gói 4G để kiểm tra trên bản beta nếu không có lỗi bạn chờ dev cập nhật bản chính thức trên store nhé!

**Comment by beelyhot5** [comment]
@bigdargon  vâng e cảm ơn ạ

**Comment by bigdargon** [comment]
@beelyhot5 Bạn vào phần cài đặt > mạng di động và kiểm tra chỗ này có đang bật không? Nếu có bạn tắt và thử lại xem!

 ![image](https://user-images.githubusercontent.com/10969626/92681307-83f81780-f357-11ea-8910-ddb4a16051f9.jpg)

**Comment by beelyhot5** [comment]
@bigdargon vâng để e thử lại ạ, nếu k được chắc e restore lại máy rồi cài lại xem sao ạ. Có gì e sẽ cmt thêm ạ

**Comment by bigdargon** [comment]
@beelyhot5 Không cần đến mức restore lại đâu bạn, mình đoán do lỗi kết nối IPv6 của ứng dụng Adguard thôi

**Comment by bigdargon** [comment]
@beelyhot5 Adguard Pro đã cập nhật bản 4.0.3 rồi. Bạn cập nhật apps rồi test lại xem còn lỗi k nhé!

**Comment by bigdargon** [comment]
@beelyhot5 Vì không có phản hồi nên mình đóng issue này, nếu gặp vấn đề lỗi ở phiên bản mới nhất bạn report lại nhé!
