### ISSUE TITLE
Chặn QC trên plo.vn

### ISSUE THREAD

**Issue by vhpcdpgl** [bigdargon/hostsVN#240]
[//]: # (***Vui lòng nhập thông tin phía dưới dòng có dấu "[//]:" các dòng này sẽ bị ẩn khi đăng bài. Xin cám ơn!)

[//]: # (Nếu bạn muốn thêm tên miền mới, vui lòng đưa tên miền vào thẻ bên dưới.)

***Tên miền***:
```
rtbcdn.andbeyond.media
```

**Comment by bigdargon** [comment]
@vhpcdpgl có thể bạn xem log nhầm tên miền này từ trang nào chứ k phải từ trang `plo.vn` nhưng nó là tên miền quảng cáo chưa có trong hosts nên mình vẫn thêm vào. Thanks bạn!

**Comment by vhpcdpgl** [comment]
> @vhpcdpgl có thể bạn xem log nhầm tên miền này từ trang nào chứ k phải từ trang `plo.vn` nhưng nó là tên miền quảng cáo chưa có trong hosts nên mình vẫn thêm vào. Thanks bạn!

Mình để ý nó lâu rồi, cứ mở 'plo.vn' là có nó trên log NextDNS.

**Comment by vhpcdpgl** [comment]
Bổ sung thêm domain này nữa:
`services.vlitag.com`
Mình test trên PC thì có cái này, dựa trên log của unbound, trên mobile thì ko có. Adguard có chặn nó.
