### ISSUE TITLE
Chặn QC trên tienphong.vn

### ISSUE THREAD

**Issue by vhpcdpgl** [bigdargon/hostsVN#241]
[//]: # (***Vui lòng nhập thông tin phía dưới dòng có dấu "[//]:" các dòng này sẽ bị ẩn khi đăng bài. Xin cám ơn!)

[//]: # (Nếu bạn muốn thêm tên miền mới, vui lòng đưa tên miền vào thẻ bên dưới.)

***Tên miền***:
```
g.jp.miaozhen.com
```

**Comment by bigdargon** [comment]
Mình mới tạo PR bên ABPVN để chặn trang này xong mà k thấy tên miền này luôn đó :laughing:

**Comment by vhpcdpgl** [comment]
Thêm domain này nữa bạn:
`sync.bumlam.com`

![Screenshot_20200916-193056_Chrome.jpg](https://user-images.githubusercontent.com/59459998/93337309-2c741300-f853-11ea-9820-1109dbea46be.jpg)

**Comment by vhpcdpgl** [comment]
`green.erne.co`

![Screenshot_20200916-222135_Chrome.jpg](https://user-images.githubusercontent.com/59459998/93358052-39046580-f86b-11ea-94af-26fe713d4b78.jpg)
