### ISSUE TITLE
Kiểm tra statictuoitre.mediacdn.vn trên tuoitre.vn

### ISSUE THREAD

**Issue by vhpcdpgl** [bigdargon/hostsVN#243]
[//]: # (***Vui lòng nhập thông tin phía dưới dòng có dấu "[//]:" các dòng này sẽ bị ẩn khi đăng bài. Xin cám ơn!)

[//]: # (Hãy nhập nội dung mà bạn muốn thảo luận, rất cám ơn mọi ý kiến đóng góp của bạn!)

***Nội dung***:
Nhờ bigdargon kiểm tra tên miền `statictuoitre.mediacdn.vn` trên `tuoitre.vn` xem có phải là tracker không?
Cái này bị Privacy Badger phát hiện.

**Comment by bigdargon** [comment]
@vhpcdpgl Chắc bạn nhìn nhầm đó hoặc tiện ích chưa cập nhật database đó. Thường tên miền static ít dùng để tracking, đa số để chứa script để load cho trang web!

<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +47 |  |  | tuoitre.vn | 3 | script | `https://statictuoitre.mediacdn.vn/web_js/kcb.plugin.min.20190520.1.js` |
| +42 |  |  | tuoitre.vn | 3 | image | `https://statictuoitre.mediacdn.vn/web_images/favicon.ico` |
| +15 |  |  | tuoitre.vn | 3 | script | `https://statictuoitre.mediacdn.vn/web_js/kcb.plugin.min.20190520.1.js` |
| +11 |  |  | cuoituan.tuoitre.vn | 3 | font | `https://statictuoitre.mediacdn.vn/web_font/Roboto.woff2` |
| +11 |  |  | cuoituan.tuoitre.vn | 3 | font | `https://statictuoitre.mediacdn.vn/web_font/Roboto-Medium.woff2` |
| +11 |  |  | cuoituan.tuoitre.vn | 3 | font | `https://statictuoitre.mediacdn.vn/web_font/Roboto-Bold.woff2` |
| +7 |  |  | tuoitre.vn | 3 | image | `https://statictuoitre.mediacdn.vn/web_images/favicon.ico` |
| +1 |  |  | tuoitre.vn | 3 | css | `https://statictuoitre.mediacdn.vn/web_css/font.2017.11.28.1.min.css` |

![Screenshot (76)](https://user-images.githubusercontent.com/10969626/93288369-e93f8300-f805-11ea-9ac2-f1083fc7032a.png)

</details>
