### ISSUE TITLE
Kiểm tra tên miền static.vietnamplus.vn trên vietnamplus.vn

### ISSUE THREAD

**Issue by vhpcdpgl** [bigdargon/hostsVN#244]
[//]: # (***Vui lòng nhập thông tin phía dưới dòng có dấu "[//]:" các dòng này sẽ bị ẩn khi đăng bài. Xin cám ơn!)

[//]: # (Hãy nhập nội dung mà bạn muốn thảo luận, rất cám ơn mọi ý kiến đóng góp của bạn!)

***Nội dung***:
Cũng như issue trước, nhờ bạn kiểm tra tên miền này:
`static.vietnamplus.vn`

**Comment by bigdargon** [comment]
@vhpcdpgl Cũng giống issue trước mình giải thích, tên miền này chủ yếu chứa script để load cho trang web

<details><summary>Logger output</summary>

| | | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +39 |  |  | `www.vietnamplus.vn` | 3 | image | `https://cdnstaticobj.6e4ec01b.cdnviet.com/` | `aliasURL=https://cdnstatic.vietnamplus.vn/assets/web/img/svg-icon.svg` |
| +39 |  |  | `www.vietnamplus.vn` | 1 | image | `https://cdnstatic.vietnamplus.vn/assets/web/img/svg-icon.svg` |
| +38 |  |  | `www.vietnamplus.vn` | 3 | script | `https://cdnstaticobj.6e4ec01b.cdnviet.com/` | `aliasURL=https://cdnstatic.vietnamplus.vn/assets/js/vnp-web.min.js?v=1.9.1.0.7542.25533` |
| +38 |  |  | `www.vietnamplus.vn` | 1 | script | `https://cdnstatic.vietnamplus.vn/assets/js/vnp-web.min.js?v=1.9.1.0.7542.25533` |
| +38 |  |  | `www.vietnamplus.vn` | 3 | script | `https://cdnstaticobj.6e4ec01b.cdnviet.com/` | `aliasURL=https://cdnstatic.vietnamplus.vn/assets/js/jquery.min.js` |
| +38 |  |  | `www.vietnamplus.vn` | 1 | script | `https://cdnstatic.vietnamplus.vn/assets/js/jquery.min.js` |
| +5 |  |  | `www.vietnamplus.vn` | 3 | font | `https://cdnstaticobj.6e4ec01b.cdnviet.com/` | `aliasURL=https://cdnstatic.vietnamplus.vn/assets/web/fonts/Roboto-Medium.woff` |
| +5 |  |  | `www.vietnamplus.vn` | 1 | font | `https://cdnstatic.vietnamplus.vn/assets/web/fonts/Roboto-Medium.woff` |
| +5 |  |  | `www.vietnamplus.vn` | 3 | font | `https://cdnstaticobj.6e4ec01b.cdnviet.com/` | `aliasURL=https://cdnstatic.vietnamplus.vn/assets/web/fonts/fa-brands-400.woff2` |
| +5 |  |  | `www.vietnamplus.vn` | 1 | font | `https://cdnstatic.vietnamplus.vn/assets/web/fonts/fa-brands-400.woff2` |
| +4 |  |  | `www.vietnamplus.vn` | 3 | font | `https://cdnstaticobj.6e4ec01b.cdnviet.com/` | `aliasURL=https://cdnstatic.vietnamplus.vn/assets/web/fonts/PlayfairDisplay-Bold.woff` |
| +4 |  |  | `www.vietnamplus.vn` | 1 | font | `https://cdnstatic.vietnamplus.vn/assets/web/fonts/PlayfairDisplay-Bold.woff` |
| +4 |  |  | `www.vietnamplus.vn` | 3 | font | `https://cdnstaticobj.6e4ec01b.cdnviet.com/` | `aliasURL=https://cdnstatic.vietnamplus.vn/assets/web/fonts/fa-regular-400.woff2` |
| +4 |  |  | `www.vietnamplus.vn` | 1 | font | `https://cdnstatic.vietnamplus.vn/assets/web/fonts/fa-regular-400.woff2` |
| +4 |  |  | `www.vietnamplus.vn` | 3 | font | `https://cdnstaticobj.6e4ec01b.cdnviet.com/` | `aliasURL=https://cdnstatic.vietnamplus.vn/assets/web/fonts/Roboto-Bold.woff` |
| +4 |  |  | `www.vietnamplus.vn` | 1 | font | `https://cdnstatic.vietnamplus.vn/assets/web/fonts/Roboto-Bold.woff` |
| +4 |  |  | `www.vietnamplus.vn` | 3 | font | `https://cdnstaticobj.6e4ec01b.cdnviet.com/` | `aliasURL=https://cdnstatic.vietnamplus.vn/assets/web/fonts/fa-solid-900.woff2` |
| +4 |  |  | `www.vietnamplus.vn` | 1 | font | `https://cdnstatic.vietnamplus.vn/assets/web/fonts/fa-solid-900.woff2` |
| +4 |  |  | `www.vietnamplus.vn` | 3 | image | `https://cdnstaticobj.6e4ec01b.cdnviet.com/` | `aliasURL=https://cdnstatic.vietnamplus.vn/assets/web/img/sprites.png` |
| +4 |  |  | `www.vietnamplus.vn` | 1 | image | `https://cdnstatic.vietnamplus.vn/assets/web/img/sprites.png` |
| +4 |  |  | `www.vietnamplus.vn` | 3 | image | `https://cdnstaticobj.6e4ec01b.cdnviet.com/` | `aliasURL=https://cdnstatic.vietnamplus.vn/assets/web/img/75nam/ttxvn75-bg-1.png` |
| +4 |  |  | `www.vietnamplus.vn` | 1 | image | `https://cdnstatic.vietnamplus.vn/assets/web/img/75nam/ttxvn75-bg-1.png` |
| +4 |  |  | `www.vietnamplus.vn` | 3 | font | `https://cdnstaticobj.6e4ec01b.cdnviet.com/` | `aliasURL=https://cdnstatic.vietnamplus.vn/assets/web/fonts/Roboto-Regular.woff` |
| +4 |  |  | `www.vietnamplus.vn` | 1 | font | `https://cdnstatic.vietnamplus.vn/assets/web/fonts/Roboto-Regular.woff` |
| +2 |  |  | `www.vietnamplus.vn` | 3 | script | `https://cdnstaticobj.6e4ec01b.cdnviet.com/` | `aliasURL=https://cdnstatic.vietnamplus.vn/assets/js/vnp-web.min.js?v=1.9.1.0.7542.25533` |
| +2 |  |  | `www.vietnamplus.vn` | 1 | script | `https://cdnstatic.vietnamplus.vn/assets/js/vnp-web.min.js?v=1.9.1.0.7542.25533` |
| +2 |  |  | `www.vietnamplus.vn` | 3 | image | `https://cdnstaticobj.6e4ec01b.cdnviet.com/` | `aliasURL=https://cdnstatic.vietnamplus.vn/assets/web/img/network/laobanner.png` |
| +2 |  |  | `www.vietnamplus.vn` | 1 | image | `https://cdnstatic.vietnamplus.vn/assets/web/img/network/laobanner.png` |
| +2 |  |  | `www.vietnamplus.vn` | 3 | image | `https://cdnstaticobj.6e4ec01b.cdnviet.com/` | `aliasURL=https://cdnstatic.vietnamplus.vn/assets/web/img/network/thaibanner.png` |
| +2 |  |  | `www.vietnamplus.vn` | 1 | image | `https://cdnstatic.vietnamplus.vn/assets/web/img/network/thaibanner.png` |
| +2 |  |  | `www.vietnamplus.vn` | 3 | image | `https://cdnstaticobj.6e4ec01b.cdnviet.com/` | `aliasURL=https://cdnstatic.vietnamplus.vn/assets/web/img/network/logo-bizhub.png` |
| +2 |  |  | `www.vietnamplus.vn` | 1 | image | `https://cdnstatic.vietnamplus.vn/assets/web/img/network/logo-bizhub.png` |
| +2 |  |  | `www.vietnamplus.vn` | 3 | image | `https://cdnstaticobj.6e4ec01b.cdnviet.com/` | `aliasURL=https://cdnstatic.vietnamplus.vn/assets/web/img/network/logo-bnews.jpg` |
| +2 |  |  | `www.vietnamplus.vn` | 1 | image | `https://cdnstatic.vietnamplus.vn/assets/web/img/network/logo-bnews.jpg` |
| +2 |  |  | `www.vietnamplus.vn` | 3 | image | `https://cdnstaticobj.6e4ec01b.cdnviet.com/` | `aliasURL=https://cdnstatic.vietnamplus.vn/assets/web/img/network/LogoBADTMN.jpg` |
| +2 |  |  | `www.vietnamplus.vn` | 1 | image | `https://cdnstatic.vietnamplus.vn/assets/web/img/network/LogoBADTMN.jpg` |
| +2 |  |  | `www.vietnamplus.vn` | 3 | image | `https://cdnstaticobj.6e4ec01b.cdnviet.com/` | `aliasURL=https://cdnstatic.vietnamplus.vn/assets/web/img/network/LOGO-TINTUC-50PX.png` |
| +2 |  |  | `www.vietnamplus.vn` | 1 | image | `https://cdnstatic.vietnamplus.vn/assets/web/img/network/LOGO-TINTUC-50PX.png` |
| +2 |  |  | `www.vietnamplus.vn` | 3 | image | `https://cdnstaticobj.6e4ec01b.cdnviet.com/` | `aliasURL=https://cdnstatic.vietnamplus.vn/assets/web/img/network/VIETNAMLAW-50PX.png` |
| +2 |  |  | `www.vietnamplus.vn` | 1 | image | `https://cdnstatic.vietnamplus.vn/assets/web/img/network/VIETNAMLAW-50PX.png` |
| +2 |  |  | `www.vietnamplus.vn` | 3 | image | `https://cdnstaticobj.6e4ec01b.cdnviet.com/` | `aliasURL=https://cdnstatic.vietnamplus.vn/assets/web/img/network/LOGO-TTXVN-50PX.png` |
| +2 |  |  | `www.vietnamplus.vn` | 1 | image | `https://cdnstatic.vietnamplus.vn/assets/web/img/network/LOGO-TTXVN-50PX.png` |
| +2 |  |  | `www.vietnamplus.vn` | 3 | image | `https://cdnstaticobj.6e4ec01b.cdnviet.com/` | `aliasURL=https://cdnstatic.vietnamplus.vn/assets/web/img/network/LOGO-VNEWS-50PX.png` |
| +2 |  |  | `www.vietnamplus.vn` | 1 | image | `https://cdnstatic.vietnamplus.vn/assets/web/img/network/LOGO-VNEWS-50PX.png` |
| +2 |  |  | `www.vietnamplus.vn` | 3 | image | `https://cdnstaticobj.6e4ec01b.cdnviet.com/` | `aliasURL=https://cdnstatic.vietnamplus.vn/assets/web/img/network/LOGO-THETHAOVH-50PX.png` |
| +2 |  |  | `www.vietnamplus.vn` | 1 | image | `https://cdnstatic.vietnamplus.vn/assets/web/img/network/LOGO-THETHAOVH-50PX.png` |
| +2 |  |  | `www.vietnamplus.vn` | 3 | image | `https://cdnstaticobj.6e4ec01b.cdnviet.com/` | `aliasURL=https://cdnstatic.vietnamplus.vn/assets/web/img/network/logo-ba.png` |
| +2 |  |  | `www.vietnamplus.vn` | 1 | image | `https://cdnstatic.vietnamplus.vn/assets/web/img/network/logo-ba.png` |
| +2 |  |  | `www.vietnamplus.vn` | 3 | image | `https://cdnstaticobj.6e4ec01b.cdnviet.com/` | `aliasURL=https://cdnstatic.vietnamplus.vn/assets/web/img/network/LOGO-LECOURRIER-50PX.png` |
| +2 |  |  | `www.vietnamplus.vn` | 1 | image | `https://cdnstatic.vietnamplus.vn/assets/web/img/network/LOGO-LECOURRIER-50PX.png` |
| +2 |  |  | `www.vietnamplus.vn` | 3 | image | `https://cdnstaticobj.6e4ec01b.cdnviet.com/` | `aliasURL=https://cdnstatic.vietnamplus.vn/assets/web/img/network/LOGO-VIETNAMNEWS-50PX.png` |
| +2 |  |  | `www.vietnamplus.vn` | 1 | image | `https://cdnstatic.vietnamplus.vn/assets/web/img/network/LOGO-VIETNAMNEWS-50PX.png` |
| +1 |  |  | `www.vietnamplus.vn` | 3 | image | `https://cdnstaticobj.6e4ec01b.cdnviet.com/` | `aliasURL=https://cdnstatic.vietnamplus.vn/assets/web/img/75nam/ttxvn75-logo.png` |
| +1 |  |  | `www.vietnamplus.vn` | 3 | script | `https://cdnstaticobj.6e4ec01b.cdnviet.com/` | `aliasURL=https://cdnstatic.vietnamplus.vn/assets/js/jquery.min.js` |
| +1 |  |  | `www.vietnamplus.vn` | 3 | css | `https://cdnstaticobj.6e4ec01b.cdnviet.com/` | `aliasURL=https://cdnstatic.vietnamplus.vn/assets/web/css/vnp.min.css?v=1.7.1.0.7542.25533` |
| +1 |  |  | `www.vietnamplus.vn` | 1 | image | `https://cdnstatic.vietnamplus.vn/assets/web/img/75nam/ttxvn75-logo.png` |
| +1 |  |  | `www.vietnamplus.vn` | 1 | script | `https://cdnstatic.vietnamplus.vn/assets/js/jquery.min.js` |
| +1 |  |  | `www.vietnamplus.vn` | 1 | css | `https://cdnstatic.vietnamplus.vn/assets/web/css/vnp.min.css?v=1.7.1.0.7542.25533` |
</details>
