### ISSUE TITLE
Chặn QC trên cafef.vn

### ISSUE THREAD

**Issue by vhpcdpgl** [bigdargon/hostsVN#245]
[//]: # (***Vui lòng nhập thông tin phía dưới dòng có dấu "[//]:" các dòng này sẽ bị ẩn khi đăng bài. Xin cám ơn!)

[//]: # (Nếu bạn muốn thêm tên miền mới, vui lòng đưa tên miền vào thẻ bên dưới.)

***Tên miền***:
```
boxpr.aiservice.vn
aiservice.vn
```

**Comment by bigdargon** [comment]
@vhpcdpgl mình chỉ chặn tên miền `boxpr.aiservice.vn` là chặn được bài tài trợ, chặn cả tên miền sẽ lỗi không được báo trên apps dưới link

https://tinhte.vn/thread/2844988#post-57518244
