### ISSUE TITLE
Chặn QC trên dantri.com.vn

### ISSUE THREAD

**Issue by vhpcdpgl** [bigdargon/hostsVN#246]
[//]: # (***Vui lòng nhập thông tin phía dưới dòng có dấu "[//]:" các dòng này sẽ bị ẩn khi đăng bài. Xin cám ơn!)

[//]: # (Nếu bạn muốn thêm tên miền mới, vui lòng đưa tên miền vào thẻ bên dưới.)

***Tên miền***:
```
cdnasset.dantri.com.vn
```
Domain này nhúng hẳn 1 frame (qc dạng carousel/quay vòng) để load QC từ bên thứ 3. Vị trí frame gần cuối trang web.

**Comment by bigdargon** [comment]
@vhpcdpgl Mình đã có theo dõi tên miền này rồi, nó dùng để chứa các đoạn script để load cho trang web (như gadget). Trong đó có 1 rule của `ABPVN` là `||cdnasset.dantri.com.vn/fe/asset-dtms.html` đã chặn địa chỉ `https://cdnasset.dantri.com.vn/fe/asset-dtms.html?dtms=wss-prod&cat=20&count=3&v=12e71890&font=1&aid=20200918114634497&type=1&script=1&color=rgb(26%2C%20121%2C%200)`

Theo mình bạn nên chặn bằng rule sẽ không gây lỗi khi load trang, bạn tham khảo một số script mình bắt được từ trang web.

<details><summary>Logger output</summary>

| | | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +8 | \|\|cdnasset.dantri.com.vn/fe/asset-dtms.html | -- | dantri.com.vn | 1 | frame | `https://cdnasset.dantri.com.vn/fe/asset-dtms.html?dtms=wss-prod&cat=20&count=3&v=12e71890&font=1&aid=20200918114634497&type=1&script=1&color=rgb(26%2C%20121%2C%200)` |
| +7 |  |  | dantri.com.vn | 3 | script | `https://static.vegadns.vn/` | `aliasURL=https://cdnasset.dantri.com.vn/fe/12-12e71890.min.js?v=12e71890` |
| +7 |  |  | dantri.com.vn | 1 | script | `https://cdnasset.dantri.com.vn/fe/12-12e71890.min.js?v=12e71890` |
| +7 |  |  | dantri.com.vn | 3 | script | `https://static.vegadns.vn/` | `aliasURL=https://cdnasset.dantri.com.vn/fe/11-12e71890.min.js?v=12e71890` |
| +7 |  |  | dantri.com.vn | 1 | script | `https://cdnasset.dantri.com.vn/fe/11-12e71890.min.js?v=12e71890` |
| +7 |  |  | dantri.com.vn | 3 | script | `https://static.vegadns.vn/` | `aliasURL=https://cdnasset.dantri.com.vn/fe/20-12e71890.min.js?v=12e71890` |
| +7 |  |  | dantri.com.vn | 1 | script | `https://cdnasset.dantri.com.vn/fe/20-12e71890.min.js?v=12e71890` |
| +5 |  |  | dantri.com.vn | 3 | script | `https://static.vegadns.vn/` | `aliasURL=https://cdnasset.dantri.com.vn/fe/1-12e71890.min.js?v=12e71890` |
| +5 |  |  | dantri.com.vn | 1 | script | `https://cdnasset.dantri.com.vn/fe/1-12e71890.min.js?v=12e71890` |
| +5 |  |  | dantri.com.vn | 3 | script | `https://static.vegadns.vn/` | `aliasURL=https://cdnasset.dantri.com.vn/fe/0-12e71890.min.js?v=12e71890` |
| +5 |  |  | dantri.com.vn | 1 | script | `https://cdnasset.dantri.com.vn/fe/0-12e71890.min.js?v=12e71890` |
| +5 |  |  | gadgets.dantri.com.vn | 3 | script | `https://static.vegadns.vn/` | `aliasURL=https://cdnasset.dantri.com.vn/gadgets/assets/app.0172861.js` |
| +5 |  |  | gadgets.dantri.com.vn | 1 | script | `https://cdnasset.dantri.com.vn/gadgets/assets/app.0172861.js` |
| +5 |  |  | gadgets.dantri.com.vn | 3 | script | `https://static.vegadns.vn/` | `aliasURL=https://cdnasset.dantri.com.vn/gadgets/assets/vendors/commons.8e65778.js` |
| +5 |  |  | gadgets.dantri.com.vn | 1 | script | `https://cdnasset.dantri.com.vn/gadgets/assets/vendors/commons.8e65778.js` |
| +5 |  |  | gadgets.dantri.com.vn | 3 | script | `https://static.vegadns.vn/` | `aliasURL=https://cdnasset.dantri.com.vn/gadgets/assets/pages/corona/mini.00d0422.js` |
| +5 |  |  | gadgets.dantri.com.vn | 1 | script | `https://cdnasset.dantri.com.vn/gadgets/assets/pages/corona/mini.00d0422.js` |
| +5 |  |  | gadgets.dantri.com.vn | 3 | script | `https://static.vegadns.vn/` | `aliasURL=https://cdnasset.dantri.com.vn/gadgets/assets/runtime.4ef28ee.js` |
| +5 |  |  | gadgets.dantri.com.vn | 1 | script | `https://cdnasset.dantri.com.vn/gadgets/assets/runtime.4ef28ee.js` |
| +5 |  |  | dantri.com.vn | 3 | script | `https://static.vegadns.vn/` | `aliasURL=https://cdnasset.dantri.com.vn/fe/process.min.js?v=12e71890` |
| +5 |  |  | dantri.com.vn | 1 | script | `https://cdnasset.dantri.com.vn/fe/process.min.js?v=12e71890` |
| +4 |  |  | dantri.com.vn | 3 | script | `https://static.vegadns.vn/` | `aliasURL=https://cdnasset.dantri.com.vn/fe/render.min.js` |
| +4 |  |  | dantri.com.vn | 1 | script | `https://cdnasset.dantri.com.vn/fe/render.min.js` |
| +3 |  |  | dantri.com.vn | 3 | script | `https://static.vegadns.vn/` | `aliasURL=https://cdnasset.dantri.com.vn/gadgets/embed.js?v=200406` |
| +3 |  |  | dantri.com.vn | 1 | script | `https://cdnasset.dantri.com.vn/gadgets/embed.js?v=200406` |
</details>

**Comment by bigdargon** [comment]
Mình theo dõi thì đoạn `asset-dtms.html` nằm trong script này `https://cdnasset.dantri.com.vn/fe/process.min.js?v=12e71890`

**Comment by vhpcdpgl** [comment]
Mình chặn nó rồi, sau đó test trên cả mobile và PC thì trang vẫn bình thường, chỉ có quảng cáo là mất thôi. PC thì mình test với DNSCrypt-proxy mà không dùng bất cứ addon nào, Chrome để nguyên xi, cũng ko dùng bất cứ program nào có xài ABPVN filter cả.

**Comment by bigdargon** [comment]
Mình có thử chặn rồi, mặc dù có mất khoảng trắng (vì mình có xài bộ lọc qc) nhưng nó sẽ làm hỏng cái cập nhật dịch bệnh corona ở các trang báo.

**Comment by bigdargon** [comment]
@vhpcdpgl Có vẻ chúng ta nên chặn nó, nếu dùng fb mở link bài viết sẽ có qc nhúng dưới cuối trang.
