### ISSUE TITLE
Tôi không thể đăng nhập vào tài khoản apple , phần quản lý thông tin , nó báo là không thể kết nối tới itune

### ISSUE THREAD

**Issue by nguyencuongkg** [bigdargon/hostsVN#248]
![68F08B49-9CB2-4CDC-8415-B94373DEA57A](https://user-images.githubusercontent.com/71514027/93611315-63375e00-f9f8-11ea-999b-dbd3c37b87b0.png)

**Comment by bigdargon** [comment]
Bạn đang sử dụng config nào? Và đang sử dụng iOS mấy? Mình đã kiểm tra vẫn xem thông tin tài khoản bình thường sau khi đăng nhập!

**Comment by nguyencuongkg** [comment]
tôi sài ...config này .... https://raw.githubusercontent.com/bigdargon/hostsVN/master/option/hostsVN-quantumultX.conf và ios 14 , đăng nhập vào phần kiểm soát thông tinh , và tải về bị xoay xoay hoài kiểu appstone không phản hồi , rồi tôi tắt quantumultX , thì đăng nhập và tải bình thường , mong bạn xem lại.
 
Được gửi từ iPad của tôi

**Comment by bigdargon** [comment]
@nguyencuongkg nghĩa là bạn đã đăng xuất khỏi store, giờ thì vào store để đăng nhập tài khoản trực tiếp từ app store nhưng không được?

**Comment by nguyencuongkg** [comment]
đúng vậy

Được gửi từ iPad của tôi

**Comment by bigdargon** [comment]
Lỗi này do VPN của các app proxy, dù có cấu hình hay k thì vẫn không đăng nhập được. Có 2 cách: 1 là bạn tắt vpn đi rồi đăng nhập, 2 là đăng nhập tài khoản app store trong phần cài đặt điện thoại (không đăng nhập trực tiếp trên app store)

**Comment by nguyencuongkg** [comment]
tôi hiểu rồi , cám ơn bạn

Vào 09:55, CN, 20 Th9, 2020 BigDargon <notifications@github.com> đã viết:
