### ISSUE TITLE
Lỗi văng nhaccuatui do rewrite reject-200

### ISSUE THREAD

**Issue by KD-MM2** [bigdargon/hostsVN#250]
[//]: # (***Vui lòng nhập thông tin phía dưới dòng có dấu "[//]:" các dòng này sẽ bị ẩn khi đăng bài. Xin cám ơn!)

***Địa chỉ trang web/ứng dụng lỗi***:  Nhaccuatui

* **Lỗi khi bật hosts**: văng ứng dụng do rewrite reject-200(quantumult x)

[//]: # (Thay thế %screenshot_url% bên dưới với địa chỉ hình ảnh báo lỗi. Ngoài ra, bạn có thể dán trực tiếp ảnh từ clipboard, chúng sẽ tự động được thêm vào.)

<details><summary>Ảnh chụp màn hình:</summary>

![image](%screenshot_url%)
</details><br/>

* **Khi không bật hosts**: 

[//]: # (Thay thế %screenshot_url% bên dưới với địa chỉ hình ảnh khi không sử dụng hosts. Nếu cần, hãy cung cấp ảnh chụp màn hình bên dưới, giống như trên)

<details><summary>Ảnh chụp màn hình:</summary>

![image](%url_of_screenshot%)
</details><br/>

***Chi tiết***: revert về sử dụng reject-img thay vì reject-200. Đã test bằng quantumult x

**Comment by bigdargon** [comment]
hmmm.. Dev ytb fix cái video ad nên giờ khá mệt vụ này :sob:

**Comment by KD-MM2** [comment]
![F06F008F-E2CA-4224-BFD5-D524F36DE392](https://user-images.githubusercontent.com/57068549/93957113-89f5eb80-fd8e-11ea-85a4-b260769c4b1e.png)
Vụ ytb do app version, hạ app về 15.26.4 là được bác ạ

**Comment by bigdargon** [comment]
@KD-MM2 Cám ơn thông tin của bạn nhiều!

**Comment by bigdargon** [comment]
@KD-MM2 hình như cách đăng xuất k có tác dụng, vẫn bị đơ như thường :sob:

**Comment by KD-MM2** [comment]
Bác tắt app bật lại vài lần xem sao ạ. Hôm nọ e thử có được rồi...

**Comment by KD-MM2** [comment]
Nếu không được nữa thì hạ ver về 15.26.4 đi ạ
![B1001030-D5B8-4F43-9C2C-2FBFEE177E2F](https://user-images.githubusercontent.com/57068549/93958872-6cc31c00-fd92-11ea-91be-9876fafc8c56.jpeg)

**Comment by bigdargon** [comment]
Chắc chỉ có nước hạ xuống bản thấp hơn may ra mới an toàn!

**Comment by KD-MM2** [comment]
Tắt ytb bật lại rồi các thứ blah blah chắc dc đó bác. 
Còn nếu bác làm hạ cấp thì có thể tham khảo plist của e, file ipa dùng charles compose http request, sửa lại build number rồi execute là tải được ipa
https://github.com/KD-MM2/KD-MM2.github.io/blob/master/qx/youtube-15.26.4-kd.kaotd.plist
![47F20D2A-C4FD-46DF-88CE-BD977D296C9E](https://user-images.githubusercontent.com/57068549/93961915-aeed5d00-fd94-11ea-88b4-1f0afde7eb5f.jpeg)

**Comment by bigdargon** [comment]
@KD-MM2 Ok! Thanks bạn!

**Comment by KD-MM2** [comment]
Vừa có update chặn quảng cáo ytb mới, bác test giúp e nhé!

QuanX
hostname = *.googlevideo.com, www.youtube.com, www.googleapis.com
(^https?:\/\/[\w-]+\.googlevideo\.com\/.+)(ctier=L)(&.+) url 302 $1$3
^https?:\/\/[\w-]+\.googlevideo\.com\/.+&(oad|ctier) url reject-200
^https?:\/\/.+\.googlevideo\.com\/ptracking url reject-200
^https?:\/\/.+\.googlevideo\.com\/videogoodput url reject-200
^https?:\/\/.+\.youtube\.com\/.+adformat url reject-200
^https?:\/\/.+\.youtube\.com\/.+get_ads url reject-200
^https?:\/\/.+\.youtube\.com\/api\/stats\/ads url reject-200
^https?:\/\/.+\.youtube\.com\/api\/stats\/atr url reject-200
^https?:\/\/.+\.youtube\.com\/api\/stats\/qoe url reject-200
^https?:\/\/.+\.youtube\.com\/csi_204 url reject-200
^https?:\/\/.+\.youtube\.com\/gen_204 url reject-200
^https?:\/\/.+\.youtube\.com\/generate_204 url reject-200
^https?:\/\/.+\.youtube\.com\/get_midroll url reject-200
^https?:\/\/.+\.youtube\.com\/pagead url reject-200
^https?:\/\/.+\.youtube\.com\/pcs url reject-200
^https?:\/\/.+\.youtube\.com\/ptracking url reject-200
^https?:\/\/.+\.googleapis.com/.+ad_break url reject-200
^https?:\/\/.+\.googleapis.com/adsmeasurement url reject-200

**Comment by bigdargon** [comment]
@KD-MM2 Cám ơn bạn đã chia sẻ! Mình đã test và đã vượt đc video QC, tuy nhiên cú pháp của rule có chút khác, nên mình sẽ cập nhật sau nhé!

**Comment by KD-MM2** [comment]
Rule surge bác dùng cái này nha
(^https?:\/\/[\w-]+\.googlevideo\.com\/.+)(ctier=L)(&.+) $1$3 302
^https?:\/\/[\w-]+\.googlevideo\.com\/.+&(oad|ctier) - reject

**Comment by KD-MM2** [comment]
Phân tích một chút:
(^https?://[\w-]+.googlevideo.com/.+) là $1
(ctier=L) là $2
(&.+) là $3
 url 302 chuyển hướng url kiểu 302
Url đích là $1$3 (^https?://[\w-]+.googlevideo.com/.+)(&.+)
