### ISSUE TITLE
Chặn QC trên zingnews.vn

### ISSUE THREAD

**Issue by vhpcdpgl** [bigdargon/hostsVN#251]
[//]: # (***Vui lòng nhập thông tin phía dưới dòng có dấu "[//]:" các dòng này sẽ bị ẩn khi đăng bài. Xin cám ơn!)

[//]: # (Nếu bạn muốn thêm tên miền mới, vui lòng đưa tên miền vào thẻ bên dưới.)

***Tên miền***:
```
stc.interactive.brand.zing.vn
```
Tên miền này có icon của Adtima, dưới đây là ảnh log ghi nhận của NextDNS:
![image](https://user-images.githubusercontent.com/59459998/94136076-99f4f480-fe8e-11ea-8f4e-e541b6c1fe59.png)

**Comment by bigdargon** [comment]
```
https://adtima.vn/hub/pr
https://adtima.vn/hub/games
```
