### ISSUE TITLE
Chặn video QC trên tienphong.vn

### ISSUE THREAD

**Issue by vhpcdpgl** [bigdargon/hostsVN#254]
[//]: # (***Vui lòng nhập thông tin phía dưới dòng có dấu "[//]:" các dòng này sẽ bị ẩn khi đăng bài. Xin cám ơn!)

[//]: # (Nếu bạn muốn thêm tên miền mới, vui lòng đưa tên miền vào thẻ bên dưới.)

***Tên miền***:
```
stg.truvidplayer.com
```

**Comment by bigdargon** [comment]
Bạn cho mình thêm thông tin như thiết bị (PC/Mobile), trình duyệt (Firefox/Chrome) và địa chỉ trang bạn phát hiện để mình kiểm tra. Vì đây là player nên nếu chặn hết k biết sẽ có ảnh hưởng đến trang web đang xem hay không? Mình chỉ tìm được JS liên quan địa chỉ này

```
https://stg.truvidplayer.com/index.php?sub_user_id=243&widget_id=1864&video_id=76ac079a2e57866c5f374e67e555e84b871f1605&m=a&cb=
```

**Comment by vhpcdpgl** [comment]
Mình duyệt trang video của tienphong.vn trên Google Chrome PC thì thấy trong log của NextDNS.
Cái này là domain của truvid.com.

![Screenshot_20200928-215152_Chrome.jpg](https://user-images.githubusercontent.com/59459998/94448781-87075a80-01d5-11eb-91cb-d55792b7cb61.jpg)
