### ISSUE TITLE
Lỗi không load được trang chủ cydia

### ISSUE THREAD

**Issue by beelyhot5** [bigdargon/hostsVN#257]
[//]: # (***Vui lòng nhập thông tin phía dưới dòng có dấu "[//]:" các dòng này sẽ bị ẩn khi đăng bài. Xin cám ơn!)

***Địa chỉ trang web/ứng dụng lỗi***:

* **Lỗi khi bật hosts**: 

[//]: # (Thay thế %screenshot_url% bên dưới với địa chỉ hình ảnh báo lỗi. Ngoài ra, bạn có thể dán trực tiếp ảnh từ clipboard, chúng sẽ tự động được thêm vào.)

<details><summary>Ảnh chụp màn hình:</summary>

</details><br/>

* **Khi không bật hosts**: 

[//]: # (Thay thế %screenshot_url% bên dưới với địa chỉ hình ảnh khi không sử dụng hosts. Nếu cần, hãy cung cấp ảnh chụp màn hình bên dưới, giống như trên)

<details><summary>Ảnh chụp màn hình:</summary>

</details><br/>

***Chi tiết***:
```suggestion

```
Em bị lỗi khi bật DNS sẽ không vào được cydia, khi vào trang chủ sẽ trắng xoá và không làm mới được nguồn không cài đặt được tweak. Sau khi e tắt DNS tắt hẳn cydia mở lại thì sẽ vào được, sau đó e lại bật DNS sử dụng bình thường ạ. Tức là sau khi mở cydia trước rồi mới bật DNS, nếu mở DNS sẽ không load được nguồn ạ

**Comment by bigdargon** [comment]
Bạn cần cung cấp danh sách nguồn mà bạn đã thêm vào mình mới kiểm tra được!

**Comment by beelyhot5** [comment]
> Bạn cần cung cấp danh sách nguồn mà bạn đã thêm vào mình mới kiểm tra được!

Là trang chủ của cydia luôn ấy ạ. Khi trang chủ load được thì các nguồn e cài cũng load được. Trang chủ là trang mà chào mừng bạn đến với cydia bởi jay freeman ấy a. Còn khi vào trang đó nó trắng xoá không load được thì các nguồn cũng không load được

**Comment by beelyhot5** [comment]
> Bạn cần cung cấp danh sách nguồn mà bạn đã thêm vào mình mới kiểm tra được!

Ảnh khi bật host bị lỗi đây ạ, nếu tắt host DNS sẽ load vào bth
![image](https://user-images.githubusercontent.com/52899715/95043967-7a6c9000-0708-11eb-9eba-8697e5dc8ad1.png)

**Comment by bigdargon** [comment]
@beelyhot5 Bạn đang sử dụng trình chặn qc nào? Bạn mở cydia để thao tác đến khi gặp lỗi, bạn quay lại apps chặn qc mở nhật ký chặn chụp lại và gửi mình kiểm tra

**Comment by beelyhot5** [comment]
> @beelyhot5 Bạn đang sử dụng trình chặn qc nào? Bạn mở cydia để thao tác đến khi gặp lỗi, bạn quay lại apps chặn qc mở nhật ký chặn chụp lại và gửi mình kiểm tra

Dạ hiện tại lỗi chưa xảy ra lại ạ

**Comment by bigdargon** [comment]
Hiện tại, mình dùng với máy JB thì k gặp lỗi như bạn nói. Có thể do lỗi mạng hay đâu đó, vì mình k chặn các nguồn trong cydia, chỉ chặn tên miền qc mà thôi! 

Nếu vấn đề tiếp tục xuất hiện, bạn cung cấp cho mình tên apps mà bạn dùng để chặn qc và phiên bản ios máy bạn JB. Mình đóng issue lại, nếu gặp trục trặc bạn mở issue nhé!

**Comment by beelyhot5** [comment]
> Hiện tại, mình dùng với máy JB thì k gặp lỗi như bạn nói. Có thể do lỗi mạng hay đâu đó, vì mình k chặn các nguồn trong cydia, chỉ chặn tên miền qc mà thôi! 
> 
> 
> 
> Nếu vấn đề tiếp tục xuất hiện, bạn cung cấp cho mình tên apps mà bạn dùng để chặn qc và phiên bản ios máy bạn JB. Mình đóng issue lại, nếu gặp trục trặc bạn mở issue nhé!

Đây là video lỗi đây ạ, e dùng iphone X ios 13.5 dùng bản adguard Pro chính chủ ạ![image](https://user-images.githubusercontent.com/52899715/95325286-2bbb2380-08cb-11eb-8f7d-74d05778e7d8.png)

**Comment by bigdargon** [comment]
Bạn up lên youtube rồi gửi link lên đây là nhanh nhất!

**Comment by beelyhot5** [comment]
> Bạn up lên youtube rồi gửi link lên đây là nhanh nhất!

Link đây ạ
https://youtu.be/Db70BAQA7DQ

**Comment by beelyhot5** [comment]
> Bạn up lên youtube rồi gửi link lên đây là nhanh nhất!

A đã xem được video chưa ạ ?

**Comment by bigdargon** [comment]
Mấy hôm nay mình bận quá nên chưa trả lời bạn. Giờ bạn làm theo cách này, vào phần bộ lọc DNS, xoá bộ lọc mà bạn đã thêm, nghĩa là bật VPN không có bộ lọc. Và thử lại xem khi app k có bộ lọc thì có bị lỗi hay k?

**Comment by beelyhot5** [comment]
> Mấy hôm nay mình bận quá nên chưa trả lời bạn. Giờ bạn làm theo cách này, vào phần bộ lọc DNS, xoá bộ lọc mà bạn đã thêm, nghĩa là bật VPN không có bộ lọc. Và thử lại xem khi app k có bộ lọc thì có bị lỗi hay k?

Vâng để e thử ạ, lỗi này thường sau khi e đã load được cydia thì không bị lại một thời gian sau đó mới bị lại ạ. E check vài ngày có gì e báo lại a sau ạ, a tạm close bài dùm e

**Comment by beelyhot5** [comment]
> Mấy hôm nay mình bận quá nên chưa trả lời bạn. Giờ bạn làm theo cách này, vào phần bộ lọc DNS, xoá bộ lọc mà bạn đã thêm, nghĩa là bật VPN không có bộ lọc. Và thử lại xem khi app k có bộ lọc thì có bị lỗi hay k?

Vâng e đã check vẫn bị ạ. Vậy là do app Adguard Pro ạ, app e bỏ tiền mua chính chủ trên appstore không phải hack ạ, giờ có cách khắc phục nào k a?

**Comment by bigdargon** [comment]
@beelyhot5 Cái này là do app xung đột với JB, bạn có thể liên hệ trực tiếp với dev bằng cách: thực hiện thao tác lỗi (có kèm quay màn hình càng tốt), sau đó vào phần cài đặt của adguard > chọn support > chọn report a bug và ghi mô tả lỗi (bằng tiếng anh) gửi cho dev và chờ họ phản hồi nhé! Vì là JB nên mình k hỗ trợ được, máy mình k có JB

**Comment by beelyhot5** [comment]
> @beelyhot5 Cái này là do app xung đột với JB, bạn có thể liên hệ trực tiếp với dev bằng cách: thực hiện thao tác lỗi (có kèm quay màn hình càng tốt), sau đó vào phần cài đặt của adguard > chọn support > chọn report a bug và ghi mô tả lỗi (bằng tiếng anh) gửi cho dev và chờ họ phản hồi nhé! Vì là JB nên mình k hỗ trợ được, máy mình k có JB

Tks a ạ, a có thể hướng dẫn e cài file host vào hệ thống cho máy đã Jb không ạ?

**Comment by bigdargon** [comment]
> 
> 
> > @beelyhot5 Cái này là do app xung đột với JB, bạn có thể liên hệ trực tiếp với dev bằng cách: thực hiện thao tác lỗi (có kèm quay màn hình càng tốt), sau đó vào phần cài đặt của adguard > chọn support > chọn report a bug và ghi mô tả lỗi (bằng tiếng anh) gửi cho dev và chờ họ phản hồi nhé! Vì là JB nên mình k hỗ trợ được, máy mình k có JB
> 
> Tks a ạ, a có thể hướng dẫn e cài file host vào hệ thống cho máy đã Jb không ạ?

Nếu bạn JB từ iOS 11 trở về sau, trước tiên bạn cần cài đặt `LetMeBlock` từ nguồn https://poomsmart.github.io/repo/

Sau đó vào đường dẫn https://raw.githubusercontent.com/bigdargon/hostsVN/master/option/hosts-iOS copy nội dung và dán vào file hosts ở đường dẫn `/etc/hosts` (lưu ý là bạn sao lưu file hosts của hệ thống lại trước nhé, đổi tên thêm đuôi .bak gì đó tùy bạn). Và respring lại thiết bị là xong!

Nếu trong quá trình sử dụng gặp lỗi mất mạng khi dùng hosts, bạn chỉ cần xóa file hosts đã chỉnh sửa và đổi tên file hosts đã backup là xong! Chúc bạn thành công!

**Comment by beelyhot5** [comment]
> > 
> 
> > 
> 
> > > @beelyhot5 Cái này là do app xung đột với JB, bạn có thể liên hệ trực tiếp với dev bằng cách: thực hiện thao tác lỗi (có kèm quay màn hình càng tốt), sau đó vào phần cài đặt của adguard > chọn support > chọn report a bug và ghi mô tả lỗi (bằng tiếng anh) gửi cho dev và chờ họ phản hồi nhé! Vì là JB nên mình k hỗ trợ được, máy mình k có JB
> 
> > 
> 
> > Tks a ạ, a có thể hướng dẫn e cài file host vào hệ thống cho máy đã Jb không ạ?
> 
> 
> 
> Nếu bạn JB từ iOS 11 trở về sau, trước tiên bạn cần cài đặt `LetMeBlock` từ nguồn https://poomsmart.github.io/repo/
> 
> 
> 
> Sau đó vào đường dẫn https://raw.githubusercontent.com/bigdargon/hostsVN/master/option/hosts-iOS copy nội dung và dán vào file hosts ở đường dẫn `/etc/hosts` (lưu ý là bạn sao lưu file hosts của hệ thống lại trước nhé, đổi tên thêm đuôi .bak gì đó tùy bạn). Và respring lại thiết bị là xong!
> 
> 
> 
> Nếu trong quá trình sử dụng gặp lỗi mất mạng khi dùng hosts, bạn chỉ cần xóa file hosts đã chỉnh sửa và đổi tên file hosts đã backup là xong! Chúc bạn thành công!

Có cách nào coppy tất cả ko ạ? Chứ e vào đường dẫn a đưa coppy kéo coppy từng khúc hoài dài quá ạ

**Comment by bigdargon** [comment]
Bạn có thể dùng deb mà mình đã đóng gói sẵn ở đây https://github.com/bigdargon/hostsVN-deb/raw/master/debs/vn.bigdargon.hostsvn_1.3_iphoneos-arm.deb

Nhưng bạn cần phải cài tweak `LetMeBlock` như trên và tweak `wget` trước để sử dụng câu lệnh tải về. Mỗi khi muốn cập nhật hosts bạn chỉ cần reinstall file deb là lấy về dữ liệu mới nhất!

**Comment by beelyhot5** [comment]
> Bạn có thể dùng deb mà mình đã đóng gói sẵn ở đây https://github.com/bigdargon/hostsVN-deb/raw/master/debs/vn.bigdargon.hostsvn_1.3_iphoneos-arm.deb
> 
> 
> 
> Nhưng bạn cần phải cài tweak `LetMeBlock` như trên và tweak `wget` trước để sử dụng câu lệnh tải về. Mỗi khi muốn cập nhật hosts bạn chỉ cần reinstall file deb là lấy về dữ liệu mới nhất!

Tks a ạ. E đã cài thành công ạ
