### ISSUE TITLE
Bạn có thể hỗ trợ Loon cho việc nhân bản boss không?

### ISSUE THREAD

**Issue by Tartarus2014** [bigdargon/hostsVN#259]
Bạn có thể hỗ trợ Loon cho việc nhân bản boss không?

**Comment by bigdargon** [comment]
Chào @Tartarus2014

Tôi sẽ thử. Cám ơn bạn đã quan tâm đến repo của tôi!

I will try. Thank you for your interest in my repo!

**Comment by Tartarus2014** [comment]
> à @ Tartarus2014
> 
> Tôisẽthử。Cámơnbạnđãquantâmđếnrepocủatôi！
> 
> 我会尝试。感谢您对我的回购感兴趣！



> Chào @Tartarus2014
> 
> Tôi sẽ thử. Cám ơn bạn đã quan tâm đến repo của tôi!
> 
> I will try. Thank you for your interest in my repo!


Ứng dụng này rất giống với Surge

**Comment by Tartarus2014** [comment]
> Chào @Tartarus2014
> 
> Tôi sẽ thử. Cám ơn bạn đã quan tâm đến repo của tôi!
> 
> I will try. Thank you for your interest in my repo!

https://apps.apple.com/us/app/loon/id1373567447    
Đây là liên kết tải xuống

**Comment by bigdargon** [comment]
@Tartarus2014 Loon can use this line for rule
```

https://github.com/bigdargon/hostsVN/raw/master/option/hostsVN-surge-rule.conf, policy=REJECT, tag=hostsVN, enabled=true

```

**Comment by bigdargon** [comment]
@Tartarus2014 This config for Loon

https://raw.githubusercontent.com/bigdargon/hostsVN/master/option/hostsVN-loon.conf
