### ISSUE TITLE
s.ss2.us

### ISSUE THREAD

**Issue by flobold83** [bigdargon/hostsVN#265]
Dear bigdargon, I'm new and discovering the possibilities with my pihole at the moment. So please forgive me if I give a meaningless feedback. 

s.ss2.us in your list is stopping my App Amazon Prime on my Sony Bravia. It is a older modell without android TV, so I'm not using an up to date app.

All the best and thank you very much for your work.

**Comment by bigdargon** [comment]
Thanks @flobold83
