### ISSUE TITLE
Chặn QC & popup trên dongphym.net

### ISSUE THREAD

**Issue by vhpcdpgl** [bigdargon/hostsVN#266]
[//]: # (***Vui lòng nhập thông tin phía dưới dòng có dấu "[//]:" các dòng này sẽ bị ẩn khi đăng bài. Xin cám ơn!)

[//]: # (Nếu bạn muốn thêm tên miền mới, vui lòng đưa tên miền vào thẻ bên dưới.)

***Tên miền***:
```
bluemaulpuffs.com
media.clhcdn.net
```

**Comment by bigdargon** [comment]
@vhpcdpgl Tên miền `media.clhcdn.net` bạn lấy từ link này đúng k? `https://dongphym.net/content/rest?t=img_ads_config` Tên miền này là dạng CDN để lưu trữ hình ảnh, ngoài ảnh hiện qc còn hiện ảnh ở 1 số trang báo nếu chặn sẽ k load được ảnh ở nhiều trang khác k liên quan qc. Nên mình chỉ chặn tên miền `bluemaulpuffs.com` thôi nhé!
