### ISSUE TITLE
App truyenyy không chặn quảng cáo được. Bác fix dùm em nha

### ISSUE THREAD

**Issue by ambrosw** [bigdargon/hostsVN#269]
![B921169C-7018-4DC6-9FE6-420633E4437F](https://user-images.githubusercontent.com/74933319/100013416-60495700-2e07-11eb-956b-fdf5be100623.png)
[//]: # (***Vui lòng nhập thông tin phía dưới dòng có dấu "[//]:" các dòng này sẽ bị ẩn khi đăng bài. Xin cám ơn!)

***Địa chỉ trang web/ứng dụng lỗi***:

* **Lỗi khi bật hosts**: 

[//]: # (Thay thế %screenshot_url% bên dưới với địa chỉ hình ảnh báo lỗi. Ngoài ra, bạn có thể dán trực tiếp ảnh từ clipboard, chúng sẽ tự động được thêm vào.)

<details><summary>Ảnh chụp màn hình:</summary>

![image](%screenshot_url%)
</details><br/>

* **Khi không bật hosts**: 

[//]: # (Thay thế %screenshot_url% bên dưới với địa chỉ hình ảnh khi không sử dụng hosts. Nếu cần, hãy cung cấp ảnh chụp màn hình bên dưới, giống như trên)

<details><summary>Ảnh chụp màn hình:</summary>

![image](%url_of_screenshot%)
</details><br/>

***Chi tiết***:

**Comment by bigdargon** [comment]
@ambrosw Chào bạn! Mình đã kiểm tra ứng dụng này và không có quảng cáo, qua kiểm tra mình thấy apps sử dụng quảng cáo của fb để hiển thị. Do vậy, 
- Bạn KHÔNG đăng nhập tk fb của bạn vào ứng dụng
- Thực hiện Opt-out quảng cáo ở bài này https://github.com/bigdargon/hostsVN/wiki/Opt-out
- Xóa ứng dụng và cache bằng cách vào Cài đặt > Cài đặt chung > Dung lượng iPhone > Tìm app và xóa trong đây. Sau đó khởi động lại
- Bật VPN chặn qc, cài đặt ứng dụng từ store và đăng ký tài khoản bằng email cá nhân

**Comment by ambrosw** [comment]
Surge ko chặn qc facebook đc à bác

**Comment by ambrosw** [comment]
> @ambrosw Chào bạn! Mình đã kiểm tra ứng dụng này và không có quảng cáo, qua kiểm tra mình thấy apps sử dụng quảng cáo của fb để hiển thị. Do vậy,
> 
> * Bạn KHÔNG đăng nhập tk fb của bạn vào ứng dụng
> * Thực hiện Opt-out quảng cáo ở bài này https://github.com/bigdargon/hostsVN/wiki/Opt-out
> * Xóa ứng dụng và cache bằng cách vào Cài đặt > Cài đặt chung > Dung lượng iPhone > Tìm app và xóa trong đây. Sau đó khởi động lại
> * Bật VPN chặn qc, cài đặt ứng dụng từ store và đăng ký tài khoản bằng email cá nhân

Tks mod. Surge ko chặn qc được từ Facebook à bác

**Comment by bigdargon** [comment]
@ambrosw Hầu hết các apps khó chặn được qc của fb, chỉ có thể giới hạn qc bằng hướng dẫn opt-out bên trên để hạn chế qc. Còn chặn hoàn toàn thì trừ khi bạn không dùng fb nữa mới k còn qc!
