### ISSUE TITLE
sp.zalo.me làm một số trang trong ZaloPay không tải được

### ISSUE THREAD

**Issue by S-a-l-a-d** [bigdargon/hostsVN#270]
1. Lỗi

Trước khi allow
![image](https://user-images.githubusercontent.com/5486625/100787233-e720b400-3445-11eb-8b2a-8a74968fe017.png)

Sau khi allow
![image](https://user-images.githubusercontent.com/5486625/100787241-ebe56800-3445-11eb-864f-8d26492aad86.png)

2. Đây cũng là SDK của Zalo: https://developers.zalo.me/docs/social/share
```
https://sp.zalo.me/plugins/sdk.js
```

**Comment by bigdargon** [comment]
Vì bộ SDK này chèn vào các trang báo để hiện nút chia sẻ nên mình đã chặn nó và chặn nguy cơ theo dõi từ zalo giống facebook
