### ISSUE TITLE
QC trên truyenqq.com

### ISSUE THREAD

**Issue by DiAnTTA** [bigdargon/hostsVN#272]
[//]: # (***Vui lòng nhập thông tin phía dưới dòng có dấu "[//]:" các dòng này sẽ bị ẩn khi đăng bài. Xin cám ơn!)

[//]: # (Nếu bạn muốn thêm tên miền mới, vui lòng đưa tên miền vào thẻ bên dưới.)

***Tên miền***:
```
||mangaqq.com^
@@||i.mangaqq.com^
```
- QC hiển thị trước khi bị chặn:

![IMG_20201209_082946](https://user-images.githubusercontent.com/74956696/101562964-faf68800-39fa-11eb-898a-17f24f5dcf74.jpg)
- QC biến mất sau khi chặn `||mangaqq.com^`,nhưng đồng thời ảnh bìa truyện cũng bị mất:

![IMG_20201209_083134](https://user-images.githubusercontent.com/74956696/101563091-398c4280-39fb-11eb-921a-01442ac216e9.jpg)
- Sau khi thêm ngoại lệ `@@||i.mangaqq.com^`, ảnh bìa truyện đã hiển thị trở lại:

![IMG_20201209_083217](https://user-images.githubusercontent.com/74956696/101563961-d00d3380-39fc-11eb-8050-68c66d2ef858.jpg)

**Comment by DiAnTTA** [comment]
@bigdargon "Khi nào thì bộ lọc sẽ hoạt động trên AdGuardSDNSFilter vậy ạ?"
- Với bác xem bộ lọc mới này có thể thay thế 2 cái trên không:

![IMG_20201209_133550](https://user-images.githubusercontent.com/74956696/101594178-d4007c00-3a23-11eb-9337-e53cd504b1e8.jpg)

**Comment by bigdargon** [comment]
@DiAnTTA Adguard DNS chỉ lọc tên miền, chứ không lọc bằng rule. Để chặn rule chính xác bạn phải sử dụng uBlock, Adblock hay Adguard mới được!

**Comment by DiAnTTA** [comment]
@bigdargon Sao em thấy các cú pháp bộ lọc này được hỗ trợ trong https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt mà, nên mới dám sử dụng theo: 
![IMG_20201209_150909](https://user-images.githubusercontent.com/74956696/101602671-0bc1f080-3a31-11eb-83dd-6da744935860.jpg)
![IMG_20201209_151715](https://user-images.githubusercontent.com/74956696/101603105-a4587080-3a31-11eb-906f-a74481e67b35.jpg)

**Comment by bigdargon** [comment]
@DiAnTTA Cái đó là những bộ lọc khác được kết hợp vào, nhưng chưa gỡ bỏ phần đuôi đó. Cơ bản DNS chỉ lọc cái tên miền, DNS không biết URL mà bạn vào nên k chặn được. Danh sách này là được chạy tự động mỗi ngày sẽ lấy từ nhiều bộ lọc bằng rule, rồi lọc lấy những adserver còn lại tất cả các rule sẽ bỏ đi.

**Comment by DiAnTTA** [comment]
@bigdargon Cảm ơn bác đã giải thích, vậy lọc DNS có hỗ trợ lọc cú pháp tên miền ngoại lệ này không ạ: `@@||domain.com^` hay chỉ lọc mỗi cú pháp `||domain.com^`

**Comment by bigdargon** [comment]
> 
> 
> @bigdargon Cảm ơn bác đã giải thích, vậy lọc DNS có hỗ trợ lọc cú pháp tên miền ngoại lệ `@@||domain.com^` không ạ, hay chỉ lọc mỗi cú pháp `||domain.com^` thôi

Vẫn hỗ trợ tên miền loại trừ, bộ lọc chỉ ở cấp độ lọc tên miền chứ không lọc được URL
