### ISSUE TITLE
Giao diện trên IOS 14.x cài đặt OPT-out đã thay đổi

### ISSUE THREAD

**Issue by khiemnd5** [bigdargon/hostsVN#276]
[//]: # (***Vui lòng nhập thông tin phía dưới dòng có dấu "[//]:" các dòng này sẽ bị ẩn khi đăng bài. Xin cám ơn!)
[//]: # (Hãy nhập nội dung mà bạn muốn thảo luận, rất cám ơn mọi ý kiến đóng góp của bạn!)

***Nội dung***:
https://github.com/bigdargon/hostsVN/wiki/Opt-out
Trên IOS bản 14.3 hiện tại (có thể từ 14.x, mình ko chắc) có giao diện thay đổi rồi.
Bạn update lại docs được không?
Hình theo ảnh bài viết giờ đã đổi.
https://prnt.sc/w8cr3c
https://prnt.sc/w8crcw
https://prnt.sc/w8cryk

**Comment by bigdargon** [comment]
Thanks bạn đã nhắc! Thay đổi từ iOS 14 luôn rồi, do mình bận quá chưa cập nhật wiki kịp!

**Comment by bigdargon** [comment]
@khiemnd5 đã cập nhật hình ảnh và bài viết wiki https://github.com/bigdargon/hostsVN/wiki/Opt-out

**Comment by khiemnd5** [comment]
Ok, đã thử và thành công. 
Cảm ơn bạn 👍
