### ISSUE TITLE
media.vodcdn.xyz

### ISSUE THREAD

**Issue by DiAnTTA** [bigdargon/hostsVN#281]
### Ngữ cảnh: [DongPhym.net](https://dongphym.net/)

<details><summary>Screenshot 1:</summary>

![IMG_20201231_000340](https://user-images.githubusercontent.com/74956696/103369288-57316100-4afc-11eb-8e61-f3eea5848754.jpg)

</details>

### Rule đề xuất: `||media.vodcdn.xyz^`
URL: https://media.vodcdn.xyz/media/image/id/5fdb1528acc3998cb98b456a.gif

<details><summary>Screenshot 2:</summary>

![IMG_20201231_001153](https://user-images.githubusercontent.com/74956696/103369519-ed658700-4afc-11eb-811e-2d1cfc2d31d2.jpg)

</details>

### Hành vi mong đợi:
Thêm rule vào [filters/adservers.txt](https://github.com/bigdargon/hostsVN/blob/master/filters/adservers.txt)

**Comment by bigdargon** [comment]
Tên miền này thuộc dạng CDN chứa ảnh, chặn tên miền CDN sẽ dẫn đến nhiều trang khác không hiện được ảnh nên mình không thêm vào nhé!
