### ISSUE TITLE
Tracker trên rever.vn

### ISSUE THREAD

**Issue by vhpcdpgl** [bigdargon/hostsVN#285]
[//]: # (***Vui lòng nhập thông tin phía dưới dòng có dấu "[//]:" các dòng này sẽ bị ẩn khi đăng bài. Xin cám ơn!)

[//]: # (Nếu bạn muốn thêm tên miền mới, vui lòng đưa tên miền vào thẻ bên dưới.)

***Tên miền***:
```
analytics.rever.vn
js.hscta.net
no-cache.hubspot.com
sentry.rever.vn
```
_Note: `sentry.rever.vn` là domain tracker thuộc `sentry.io`_

**Comment by bigdargon** [comment]
Tên miền `no-cache.hubspot.com` để chứa ảnh, bạn xem trong google search phía dưới link https://www.virustotal.com/gui/domain/no-cache.hubspot.com/details

`sentry.rever.vn` thì mình chưa tìm ra script, tên miền này trỏ về cloudflare nên cùng địa chỉ IP
