### ISSUE TITLE
Host chặn ứng dụng Line

### ISSUE THREAD

**Issue by duc2025** [bigdargon/hostsVN#289]
Mục tìm kiếm danh bạ trong ứng dụng Line không load ra được danh bạ , load được cũng rất lâu do bị chặn host

thời gian gần đây mới bị, trước đó dùng không thấy lỗi này

kho tắt mục Dns protection đi thì tìm danh bạ trên line load rất nhanh

**Comment by bigdargon** [comment]
Hầu hết ở các ứng dụng nhắn tin nước ngoài mình rất ít chặn, cụ thể Line mình k có chặn gì cả (đính kèm hình). Hiện tại mình có sử dụng Line và tìm kiếm hoàn toàn bình thường, bạn kiểm tra xem đang dùng những bộ lọc nào? Và chế độ tunnel là full hay split? Bạn thử thao tác lỗi như mô tả, rồi chụp lại nhật ký của ứng dụng (như hình mình chụp) để mình kiểm tra lại!

![E482FB7D-D115-4925-9D5C-D79E2CA92A9D](https://user-images.githubusercontent.com/10969626/108942713-141de500-768a-11eb-9872-34191d6fb0ab.png)
![DF8E9067-2847-412A-867A-4C04A50E1606](https://user-images.githubusercontent.com/10969626/108942728-1a13c600-768a-11eb-9095-4e5653643ec6.png)

**Comment by duc2025** [comment]
![image](https://user-images.githubusercontent.com/79556018/108944353-26e5e900-768d-11eb-8dd9-24b65d173aa5.png)![image](https://user-images.githubusercontent.com/79556018/108944379-2fd6ba80-768d-11eb-807c-0e2a06aab3f3.png)

Mình để Split đổi lại Ful tunnel lại được bạn nhé

**Comment by bigdargon** [comment]
@duc2025 Mình thấy máy bạn đã JB đúng k? Khi JB cài 1 số tweak nào đó sẽ ảnh hưởng đển VPN, nên vì vậy mà bạn gặp lỗi load chậm. Máy mình để Split vẫn hoạt động bình thường. Rất vui vì bạn đã tin tưởng và sử dụng bộ lọc của bên mình! Thanks!
