### ISSUE TITLE
Linking with Chongluadao.vn

### ISSUE THREAD

**Issue by htridn** [bigdargon/hostsVN#290]
Is it possible to link the list with Chongluadao.vn source
I found the API here https://api.chongluadao.vn/v1/blacklist?fbclid=IwAR3rPB58qOCGKXIu-zInNZHS0iPGLFttliKJLqcpf-hGyUzqxHsHqhMLDFo

**Comment by bigdargon** [comment]
@htridn The above path contains url address, not hosts format.

**Comment by nkoc6a15** [comment]
@htridn trong trường hợp bạn vẫn muốn dùng thì đây: https://gitlab.com/curben/vn-badsite-filter
