### ISSUE TITLE
api.getblueshift.com

### ISSUE THREAD

**Issue by aravindvnair99** [bigdargon/hostsVN#291]
This is a false positive. This domain doesn't serve ads. Blocking this breaks websites such as `mclick.udacity.com` which is used by [Udacity](https://udacity.com) and many other companies for links within emails.

Blueshift is a SmartHub Customer Data Platform (CDP) that combines customer data, AI and omnichannel orchestration in an easy-to-use platform.

Refer: https://blueshift.com

The domain is blocked at 3 places:
https://github.com/bigdargon/hostsVN/blob/f6912c4bc6cadef776ff0fafb930d097532db925/source/hosts-group.txt#L5179
https://github.com/bigdargon/hostsVN/blob/f6912c4bc6cadef776ff0fafb930d097532db925/option/domain.txt#L4836
https://github.com/bigdargon/hostsVN/blob/f6912c4bc6cadef776ff0fafb930d097532db925/option/hosts-iOS#L4852

**Comment by bigdargon** [comment]
Removed. Thank you @aravindvnair99 ! I refer to this domain from the Adguard DNS filter!
