### ISSUE TITLE
mình góp ý thôi!!!

### ISSUE THREAD

**Issue by taolatho** [bigdargon/hostsVN#297]
rule này viết sai bạn ạ
[https://github.com/bigdargon/hostsVN/blob/14e82987b0d0535d562d1ea763b964f54fb412b4/filters/adservers-all.txt#L6519](https://github.com/bigdargon/hostsVN/blob/14e82987b0d0535d562d1ea763b964f54fb412b4/filters/adservers-all.txt#L6519)
`@@||app.appsflyer.com^`

mà rules chặn QC, mà bạn chặn luôn cả trang (bài bạc, cá độ) (gambling)

[https://github.com/bigdargon/hostsVN/blob/14e82987b0d0535d562d1ea763b964f54fb412b4/filters/adservers-all.txt#L798-L803](https://github.com/bigdargon/hostsVN/blob/14e82987b0d0535d562d1ea763b964f54fb412b4/filters/adservers-all.txt#L798-L803)

bạn rút gọn như này

`||one88.*^`

mình nghĩ bạn đi sai với mục đích của tiêu đề r : ([Hosts chặn quảng cáo của người Việt](https://github.com/bigdargon/hostsVN#hostsvn-))

**Cảm ơn bạn!**

**Comment by bigdargon** [comment]
Chào bạn @taolatho 

Rất vui khi bạn quan tâm và góp ý cho github của mình, mình trả lời bạn 2 vấn đề của bạn

> rule này viết sai bạn ạ

Định dạng rule này dùng cho Adguard DNS nói riêng và các ứng dụng của Adguard nói chung như Adguard iOS, Adguard Android... Bởi vì `ABPVN` hiện tại đang làm rule cho bộ lọc rất tốt nên mình đi theo hướng khác tránh trùng lặp. Tham khảo về bộ lọc loại Adguard DNS bạn xem ở đây https://github.com/AdguardTeam/AdGuardSDNSFilter/blob/master/Filters/exceptions.txt

> mà rules chặn QC, mà bạn chặn luôn cả trang (bài bạc, cá độ) (gambling)

Đúng! Nó là quảng cáo ở trên các trang phim, trực tiếp đá bóng, một số tên miền đề chèn hình quảng cáo và theo pháp luật Việt Nam hành vi cá độ, bài bạc là vi phạm pháp luật. Hiện tại, với các tên miền dạng này chỉ mới đưa vào để chặn trên các ứng dụng của Adguard (và Adguard DNS) chứ chưa đưa vào hosts và sắp tới sẽ được thêm vào các nguồn hosts như Steven Black và NextDNS để chặn.

**Comment by taolatho** [comment]
Chào bạn @bigdargon

1. Lỗi mình bạn ạ, kiến thức không vững mà trứng chọi đá :)
2. Còn vấn đề các trang (bài bạc, cá độ) mà bạn bỏ vào danh sách chặn
là do bạn có ác cảm, chứ thật ra trên nguyên tắc thì các trang xem phim, nghe và tải nhạc **(lậu)**, etc cũng **vi phạm pháp luật** đấy thôi (bản quyền).

> Vô tình bạn bắt người khác theo suy nghĩ của bạn, không nên này nọ lọ chai :)

3. Bạn có thể tham khảo [ở đây](https://github.com/StevenBlack/hosts#list-of-all-hosts-file-variants) để xem họ phân chia "rules" như thế nào? họ tách riêng ra từng phần, chứ không gộp chung như bạn.

- Dễ quản lý
- Nhiều lựa chọn hơn cho người dùng (cuối)
- Chuyên nghiệp nữa

Một lần nữa, cảm ơn bạn @bigdargon đã phản hồi!

**Comment by bigdargon** [comment]
> Còn vấn đề các trang (bài bạc, cá độ) mà bạn cho vào danh sách chặn

Như mình có nói ở trên, các trang web nhúng tên miền hoặc popup bật lên khi nhấn vào nên mình phân loại nó vừa là qc vừa là cờ bạc. Hiện tại, mình không đưa vào link hosts mà chỉ đưa vào dạng bộ lọc để lọc trên DNS.

Lý do là vì trên thiết bị di động như Safari bị giới hạn bộ lọc nên k phát huy tác dụng của các rule. Do vậy chặn bằng DNS sẽ có tác dụng khi popup bật lên.

> Bạn có thể tham khảo ở đây để xem họ phân chia "rules" như thế nào? họ tách riêng ra từng phần, chứ không gộp chung.

Link bộ hosts mình tách riêng chứ không gộp chung phần cờ bạc vào giống như bên Steven Black, sau khi bộ lọc đủ nhiều mình sẽ merge phần cờ bạc riêng (có thể sẽ có thêm phần mạng xã hội) để người dùng dễ lựa chọn như bạn nói.

Xây dựng danh sách chặn cũng không tránh khỏi phần "cảm tính" như bạn nói, nhưng mình sẽ cố gắng để dự án có tính "trung lập" nhất có thể!

**Comment by taolatho** [comment]
Mình rất thích cách suy nghĩ của bạn, chúc dự án của bạn ngày càng phát triển ^^

Chào bạn!
