### ISSUE TITLE
Thêm list chặn porn

### ISSUE THREAD

**Issue by diepnt90** [bigdargon/hostsVN#301]
[//]: # (***Vui lòng nhập thông tin phía dưới dòng có dấu "[//]:" các dòng này sẽ bị ẩn khi đăng bài. Xin cám ơn!)

[//]: # (Hãy nhập nội dung mà bạn muốn thảo luận, rất cám ơn mọi ý kiến đóng góp của bạn!)

***Nội dung***:
Cảm ơn các bác về list chặn quảng cáo. Các bác phát triển thêm list porn ở vn thì tốt quá :D

**Comment by bigdargon** [comment]
@diepnt90 Sau thời gian dài đi nằm vùng, tìm kiếm và xây dựng. hostsVN giờ đã cập nhật thêm các phần mở rộng và trong đó có mục `nội dung người lớn` mà bạn yêu cầu! Hy vọng sẽ giúp ích cho bạn

Link: https://github.com/bigdargon/hostsVN/tree/master/extensions
