### ISSUE TITLE
unable to open mixpanel

### ISSUE THREAD

**Issue by helloworldkr** [bigdargon/hostsVN#304]
unable to open mixpanel.com

**Comment by bigdargon** [comment]
@helloworldkr `mixpanel.com` is a web and mobile product tracking tool. Domains blocked from lists `Peter Lowe's Blocklist` `StevenBlack's list` , please see here: https://urlfilter.adtidy.org/v1/checkDomain?domain=mixpanel.com

Please manually whitelist if you want to access this site. Thank you!
