### ISSUE TITLE
Chặn quảng cáo trên truyenqqtop.com

### ISSUE THREAD

**Issue by beelyhot5** [bigdargon/hostsVN#306]
Tên miền cũ là truyenqq.net chặn qc rất tốt nhưng giờ qua tên miền mới này qc nhiều quá bác ạ, bác xem dùm e với ạ

![image](https://user-images.githubusercontent.com/52899715/142770922-00d6cd60-ff37-484e-b400-a215b29fceae.png)

**Comment by bigdargon** [comment]
@beelyhot5  Trên điện thoại bạn có cài đặt Adguard/Pro chưa? Nếu có bạn cập nhật lại bộ lọc cho Safari rồi thử lại xem. Hiện tại mình truy cập hầu hết các banner đều đã bị chặn![image](https://user-images.githubusercontent.com/10969626/142824877-64de0071-456a-4f13-b701-153c56cf6aac.png)

**Comment by beelyhot5** [comment]
> @beelyhot5  Trên điện thoại bạn có cài đặt Adguard/Pro chưa? Nếu có bạn cập nhật lại bộ lọc cho Safari rồi thử lại xem. Hiện tại mình truy cập hầu hết các banner đều đã bị chặn![image](https://user-images.githubusercontent.com/10969626/142824877-64de0071-456a-4f13-b701-153c56cf6aac.png)

Trên điện thoại e có cài đặt Adguard Pro rồi ạ, e vừa vào cập nhập lại bộ lọc thì vào đã chặn được rồi ạ, còn tối qua thì lại như hình e chụp 😂 e cảm ơn ạ

**Comment by bigdargon** [comment]
@beelyhot5 Ok bạn! Thỉnh thoảng bạn mở Adguard để cập nhật (nếu tắt tính năng làm mới trong nền của iOS). Mình có tạo issue bên ABPVN để xóa hết các đoạn banner đã bị chặn còn trống chiếm màn hình.
