### ISSUE TITLE
Whitelist domain 

### ISSUE THREAD

**Issue by phamleduy04** [bigdargon/hostsVN#308]
[//]: # (***Vui lòng nhập thông tin phía dưới dòng có dấu "[//]:" các dòng này sẽ bị ẩn khi đăng bài. Xin cám ơn!)

***Địa chỉ trang web/ứng dụng lỗi***: `aax-us-iad.amazon.com` (Amazon app)

* **Lỗi khi bật hosts**: App amazon báo lỗi (page not found)

<details><summary>Ảnh chụp màn hình:</summary>

![image](https://i.imgur.com/De42hmF.png)
</details><br/>

* **Khi không bật hosts**: App amazon hoạt động bình thường (sau khi whitelist domain trên)
<details><summary>Ảnh chụp màn hình:</summary>

![image](https://i.imgur.com/i37wDXZ.png)
</details><br/>

***Chi tiết***: Có 1 [bài reddit](https://www.reddit.com/r/pfBlockerNG/comments/n2nfid/dnsbl_whitelist_request/) nói về domain này.

![image](https://user-images.githubusercontent.com/32657584/149648708-e3a4d66a-2683-4dc6-bd94-4f9fbeea7106.png)

**Comment by bigdargon** [comment]
@phamleduy04 Cám ơn bạn đã báo cáo! Pull fix sẽ đẩy lên trong lát nữa, phiền bạn cập nhật lại bộ lọc giúp mình!
