### ISSUE TITLE
Dù tôi đã chỉnh rất kĩ nhưng vẫn ko chặn được ipa , xin hãy giải thích giúp tôi

### ISSUE THREAD

**Issue by Galaxygaming281** [bigdargon/hostsVN#309]
![95FA86C7-03CA-46A5-93E1-0951FA48582C](https://user-images.githubusercontent.com/96166136/150968167-f447ce11-91f8-42e6-846b-abdd031184e1.png)
![5EA9C2DC-7CE5-41F8-B90D-09CAE0C09E24](https://user-images.githubusercontent.com/96166136/150968181-478474db-61c7-4853-b88c-6796dfe0c6d5.png)
![1E3B0C2C-8A5E-47A0-88DC-2C72D43078A6](https://user-images.githubusercontent.com/96166136/150968187-15054fc9-7099-47a1-8bb2-c21b55146179.png)
![D6B33B5F-1269-4862-A391-BB94B8FBE063](https://user-images.githubusercontent.com/96166136/150968195-f6bdeac8-0729-46b8-a333-854dea097cf1.png)
![D5765015-FEE7-40F2-BA5F-3BEBD0156431](https://user-images.githubusercontent.com/96166136/150968198-9837c8d9-265f-44c3-bbbe-5fbc54235ee9.png)
![EC11FADD-CE84-4606-A4B2-D8C75F05E482](https://user-images.githubusercontent.com/96166136/150968205-549fd482-e698-44f1-9b43-da686fb4c4c5.png)
[//]: # (***Vui lòng nhập thông tin phía dưới dòng có dấu "[//]:" các dòng này sẽ bị ẩn khi đăng bài. Xin cám ơn!)

***Địa chỉ trang web/ứng dụng lỗi***:

* **Lỗi khi bật hosts**: 

[//]: # (Thay thế %screenshot_url% bên dưới với địa chỉ hình ảnh báo lỗi. Ngoài ra, bạn có thể dán trực tiếp ảnh từ clipboard, chúng sẽ tự động được thêm vào.)

<details><summary>Ảnh chụp màn hình:</summary>

![image](%screenshot_url%)
</details><br/>

* **Khi không bật hosts**: 

[//]: # (Thay thế %screenshot_url% bên dưới với địa chỉ hình ảnh khi không sử dụng hosts. Nếu cần, hãy cung cấp ảnh chụp màn hình bên dưới, giống như trên)

<details><summary>Ảnh chụp màn hình:</summary>

![image](%url_of_screenshot%)
</details><br/>

***Chi tiết***:

**Comment by bigdargon** [comment]
@Galaxygaming281 bạn ghi tiêu đề `vẫn ko chặn được ipa` nhưng trong ảnh chụp là không cài được IPA từ nguồn ngoài. Có phải ý bạn là khi bật Surge thì không cài đặt được IPA đúng không?
