### ISSUE TITLE
Vẫn không chặn được quảng cáo trong youtube app trên IPhone

### ISSUE THREAD

**Issue by NgKhanh** [bigdargon/hostsVN#312]
[//]: # (***Vui lòng nhập thông tin phía dưới dòng có dấu "[//]:" các dòng này sẽ bị ẩn khi đăng bài. Xin cám ơn!)

mình cài cho adblock trên iphone thì khi mở youtube app xem video vẫn thấy quảng cáo như thường, không khác gì hết

***Địa chỉ trang web/ứng dụng lỗi***:

* **Lỗi khi bật hosts**: 

[//]: # (Thay thế %screenshot_url% bên dưới với địa chỉ hình ảnh báo lỗi. Ngoài ra, bạn có thể dán trực tiếp ảnh từ clipboard, chúng sẽ tự động được thêm vào.)

<details><summary>Ảnh chụp màn hình:</summary>

![image](%screenshot_url%)
</details><br/>

* **Khi không bật hosts**: 

[//]: # (Thay thế %screenshot_url% bên dưới với địa chỉ hình ảnh khi không sử dụng hosts. Nếu cần, hãy cung cấp ảnh chụp màn hình bên dưới, giống như trên)

<details><summary>Ảnh chụp màn hình:</summary>

![image](%url_of_screenshot%)
</details><br/>

***Chi tiết***:

**Comment by bigdargon** [comment]
@NgKhanh Chào bạn! Hiện tại chỉ có các ứng dụng dạng proxy lọc https như Surge, Quantumult X, Shadowrocket.. mới chặn được, còn các ứng dụng chặn bằng DNS không thể chặn được!

**Comment by bigdargon** [comment]
Bạn xem các hướng dẫn cài đặt ứng dụng trong các bài viết ở đây:
- https://github.com/bigdargon/hostsVN/wiki/Quantumult-X
- https://github.com/bigdargon/hostsVN/wiki/Shadowrocket

Thân!
