### ISSUE TITLE
Chặn qc trên ytb

### ISSUE THREAD

**Issue by qkswwkr777** [bigdargon/hostsVN#314]
[//]: # (***Vui lòng nhập thông tin phía dưới dòng có dấu "[//]:" các dòng này sẽ bị ẩn khi đăng bài. Xin cám ơn!)

***Địa chỉ trang web/ứng dụng lỗi***:
 YouTube App
* **Lỗi khi bật hosts**: 
ứng dụng YTB không kết nối được mạng khi dùng config này thông qua Shadowrocket. Mình dùng ios 15.4.1
Mình đã thử trên 2 máy đều không được. Tình trạng xảy ra đã được khoảng 2 ngày. Trước đó vẫn dùng bình thường.

[//]: # (Thay thế %screenshot_url% bên dưới với địa chỉ hình ảnh báo lỗi. Ngoài ra, bạn có thể dán trực tiếp ảnh từ clipboard, chúng sẽ tự động được thêm vào.)

<details><summary>Ảnh chụp màn hình:</summary>

![image](%screenshot_url%)
</details><br/>

* **Khi không bật hosts**: 

[//]: # (Thay thế %screenshot_url% bên dưới với địa chỉ hình ảnh khi không sử dụng hosts. Nếu cần, hãy cung cấp ảnh chụp màn hình bên dưới, giống như trên)

<details><summary>Ảnh chụp màn hình:</summary>

![image](%url_of_screenshot%)
</details><br/>

***Chi tiết***:

**Comment by Jeffeditae** [comment]
Bật MITM chưa ạ

**Comment by qkswwkr777** [comment]
> Bật MITM chưa ạ

Shadowrocket có mục này ko nhỉ? Mình ko tìm thấy.
Mình làm theo hướng dẫn trên này ấy. Trước giờ vẫn dùng bình thường.

**Comment by qkswwkr777** [comment]
Mình tìm được vấn đề rồi. Có vẻ như là mình vừa đổi đt nên chứng nhận trong phần About chưa được bật 😅 mình đã bật lên và dùng ytb được rồi. Cám ơn các bạn!
