### ISSUE TITLE
Không truy cập được NimoTv

### ISSUE THREAD

**Issue by TypicalShavonne** [bigdargon/hostsVN#315]
[//]: # (***Vui lòng nhập thông tin phía dưới dòng có dấu "[//]:" các dòng này sẽ bị ẩn khi đăng bài. Xin cám ơn!)

***Địa chỉ trang web/ứng dụng lỗi***:

* **Lỗi khi bật hosts**: 

[//]: # (Thay thế %screenshot_url% bên dưới với địa chỉ hình ảnh báo lỗi. Ngoài ra, bạn có thể dán trực tiếp ảnh từ clipboard, chúng sẽ tự động được thêm vào.)

<details><summary>Ảnh chụp màn hình:</summary>

![image](![image](https://user-images.githubusercontent.com/53472591/169666174-91570b08-ab26-4be9-b600-a9a9d1a7db1d.png))
</details><br/>

* **Khi không bật hosts**: 

[//]: # (Thay thế %screenshot_url% bên dưới với địa chỉ hình ảnh khi không sử dụng hosts. Nếu cần, hãy cung cấp ảnh chụp màn hình bên dưới, giống như trên)

<details><summary>Ảnh chụp màn hình:</summary>

![image](![image](https://user-images.githubusercontent.com/53472591/169666218-17e7b70d-86a7-4c3d-b701-01566140df24.png))
</details><br/>

***Chi tiết***:
Không thể truy cập app NimoTV khi bật hosts, ![image](https://user-images.githubusercontent.com/53472591/169666206-ec6f8eac-829e-41b3-8a2a-54269cdd02e0.p

**Comment by bigdargon** [comment]
@TypicalShavonne Bạn đang sử dụng trình chặn qc nào? Hệ điều hành gì? Hiện tại mình dùng trên iOS mọi thứ vẫn hoạt động xem livestream bình thường 
![88FE00D3-363F-4F46-B4B5-95D0B5F68F4A](https://user-images.githubusercontent.com/10969626/169676039-3f3356cb-6559-4f84-834e-1fbfca984f7c.png)
![DE22C6B6-AEF1-4F46-AFDE-A13EA3011617](https://user-images.githubusercontent.com/10969626/169676051-008f3efe-c599-430f-ab59-4ab998a812f6.png)

**Comment by TypicalShavonne** [comment]
mình dùng ios, quantumult x á b

**Comment by TypicalShavonne** [comment]
![image](https://user-images.githubusercontent.com/53472591/169697487-b7d7f457-f182-4ba0-a35b-d0dde6d9c46a.png)

**Comment by bigdargon** [comment]
@TypicalShavonne Đã fix! Bạn cập nhật lại bộ lọc nhé!
