### ISSUE TITLE
Support uBlock Origin?

### ISSUE THREAD

**Issue by haunt98** [bigdargon/hostsVN#316]
[//]: # (***Vui lòng nhập thông tin phía dưới dòng có dấu "[//]:" các dòng này sẽ bị ẩn khi đăng bài. Xin cám ơn!)

[//]: # (Hãy nhập nội dung mà bạn muốn thảo luận, rất cám ơn mọi ý kiến đóng góp của bạn!)

***Nội dung***:

As I see in README, there are too many options for Android, iOS with host and domains. But which one should I use for uBlock Origin? Thanks.

**Comment by hagezi** [comment]
Hi,

for uBlock you can also use lists in host format, so:

https://raw.githubusercontent.com/bigdargon/hostsVN/master/hosts

Cheers,
Gerd

**Comment by haunt98** [comment]
Thank you!

**Comment by bigdargon** [comment]
Hi @haunt98 

You can use the filter format supported on all Adguard apps, and it is also compatible with uBlock https://raw.githubusercontent.com/bigdargon/hostsVN/master/filters/adservers-all.txt

**Comment by haunt98** [comment]
Hi @bigdargon, thanks for suggest. But uBlock orion seems to accept both 0.0.0.0 format and adservers format.
