### ISSUE TITLE
gocmod.com - popup

### ISSUE THREAD

**Issue by DiAnTTA** [bigdargon/hostsVN#318]
***Nội dung***:
Trang web `gocmod.com` hiện popup “Vui lòng tắt chặn quảng cáo để xem trang.” khi mình sử dụng AdGuard's DNS-over-HTTPS (DoH) trong Chrome (Android). 
**Cho hỏi là có giải pháp nào khác ngoài việc tắt DNS không ạ?** 

![IMG_20220623_110740](https://user-images.githubusercontent.com/74956696/175207041-c83246a0-b8b3-4771-a962-6a4dc2101fec.jpg)

**Comment by bigdargon** [comment]
@DiAnTTA Bạn cần sử dụng DNS có tùy chỉnh được bộ lọc như nextdns, sau đó whitelist tên miền `pagead2.googlesyndication.com`. Do trang web check ping đến tên miền này, khi bị chặn bằng DNS vẫn bị phát hiện vì lý do này!

Khuyến khích bạn chuyển sang dùng Firefox sử dụng được addon uBlock hỗ trợ để chặn như trên PC luôn.

**Comment by DiAnTTA** [comment]
> whitelist tên miền pagead2.googlesyndication.com

Cảm ơn @bigdargon 
Popup đã biến mất, và quảng cáo vẫn được chặn.👍

![IMG_20220623_142841](https://user-images.githubusercontent.com/74956696/175241553-b0279392-a66f-4d4d-859f-12b0a7df5c14.jpg)
