### ISSUE TITLE
Lỗi youtube

### ISSUE THREAD

**Issue by tawayaka** [bigdargon/hostsVN#321]
[//]: # (***Vui lòng nhập thông tin phía dưới dòng có dấu "[//]:" các dòng này sẽ bị ẩn khi đăng bài. Xin cám ơn!)

***Địa chỉ trang web/ứng dụng lỗi***:
app/web: Youtube

* **Lỗi khi bật hosts**: 
không tải được trang.

<details><summary>Ảnh chụp màn hình:</summary>

![image](https://user-images.githubusercontent.com/30314539/185733820-fa2447cf-f858-45b0-8ae4-d56fd0f0f62f.png)

![image](https://user-images.githubusercontent.com/30314539/185733830-8414f0c5-7f91-4a69-a3e0-813e65899d81.png)

</details><br/>

* **Khi không bật hosts**: 

[//]: # (Thay thế %screenshot_url% bên dưới với địa chỉ hình ảnh khi không sử dụng hosts. Nếu cần, hãy cung cấp ảnh chụp màn hình bên dưới, giống như trên)

<details><summary>Ảnh chụp màn hình:</summary>

![image](https://user-images.githubusercontent.com/30314539/185733839-6fdf827c-cf3c-4fd4-9f4d-2bda9fa0b948.png)
![image](https://user-images.githubusercontent.com/30314539/185733849-c7ee8c83-4880-4e53-95d0-3c88f19f2574.png)

</details><br/>

***Chi tiết***:
Ứng dụng sử dụng host: shadowrocket,
link config: https://raw.githubusercontent.com/bigdargon/hostsVN/master/option/hostsVN-shadowrocket.conf

**Comment by bigdargon** [comment]
@tawayaka bạn cần phải tin cậy chứng chỉ được cài đặt từ Shadowrocket mới phân giải được HTTPS

**Comment by tawayaka** [comment]
> @tawayaka bạn cần phải tin cậy chứng chỉ được cài đặt từ Shadowrocket mới phân giải được HTT
mình nhầm, xin lỗi bạn.
