### ISSUE TITLE
cdn-settings.appsflyersdk.com

### ISSUE THREAD

**Issue by FadeMind** [bigdargon/hostsVN#323]
[//]: # (***Vui lòng nhập thông tin phía dưới dòng có dấu "[//]:" các dòng này sẽ bị ẩn khi đăng bài. Xin cám ơn!)

***Địa chỉ trang web/ứng dụng lỗi***:

* **Lỗi khi bật hosts**:  cdn-settings.appsflyersdk.com

[//]: # (Thay thế %screenshot_url% bên dưới với địa chỉ hình ảnh báo lỗi. Ngoài ra, bạn có thể dán trực tiếp ảnh từ clipboard, chúng sẽ tự động được thêm vào.)

<details><summary>Ảnh chụp màn hình:</summary>

![Screenshot_20220902_121417](https://user-images.githubusercontent.com/9846948/188127285-dbaaf54b-8899-4c0f-af82-841be7dfaed7.jpg)

</details><br/>

* **Khi không bật hosts**: 

<details><summary>Ảnh chụp màn hình:</summary>

</details><br/>

***Chi tiết***:

żabka (frog in english) store app need this domain for management card payment options (add, delete from account). Otherwise show up error and unable delete/add payment option. Regards

App Store https://play.google.com/store/apps/details?id=pl.zabka.apb2c&hl=pl&gl=US

Screenshot: 

![sf](https://i.imgur.com/K2bwDuT.jpg)

![20220902-1662117166](https://user-images.githubusercontent.com/9846948/188127628-b57880ba-0978-4475-a390-a4832e636f73.png)

CC @StevenBlack

**Comment by bigdargon** [comment]
This domain does not affect Steven Black's hosts. Because, I only merge domains that are registered/hosted in Vietnam. Merged address: https://raw.githubusercontent.com/bigdargon/hostsVN/master/option/hosts-VN

This domain is also blocked in Adaway, I will create an issue there.

Thank you for reporting!
