### ISSUE TITLE
Có thể xem xét tích hợp ở những ứng dụng khác trên Android không ạ?

### ISSUE THREAD

**Issue by kingsman9413** [bigdargon/hostsVN#325]
[//]: # (***Vui lòng nhập thông tin phía dưới dòng có dấu "[//]:" các dòng này sẽ bị ẩn khi đăng bài. Xin cám ơn!)

[//]: # (Hãy nhập nội dung mà bạn muốn thảo luận, rất cám ơn mọi ý kiến đóng góp của bạn!)

***Nội dung***:
Tác giả có thể nghiên cứu cách tích hợp vào những ứng dụng trên Android như : Clash for Android, Surfboard, v2flyNG, ... được không ạ 😊

**Comment by bigdargon** [comment]
@kingsman9413 Hiện tại, mình có hỗ trợ rule của app Clash for Android bạn có thể tích hợp vào config https://raw.githubusercontent.com/bigdargon/hostsVN/master/option/hostsVN-clash-rule.yaml

Còn các app khác mình k có máy android và cũng k biết config của app như thế nào nên k thể hỗ trợ/test hết được!

**Comment by kingsman9413** [comment]
@bigdargon Cho em hỏi thêm ngay vào trên app Clash được không ạ (local ngay trên máy android) hay phải chỉnh trong config ạ (config này là config remote em kéo trên web kéo về, nên nếu chỉ chỉnh được trên config thì khi cập nhật lại phải tạo bản sao để cài lại cục bộ mới chỉnh được).

**Comment by bigdargon** [comment]
@kingsman9413 clash có chức năng update remote bộ lọc theo link mình đính kèm ở trên. Thêm vào tự động app sẽ update theo thời gian chứ k cần làm thủ công!

**Comment by kingsman9413** [comment]
@bigdargon Em đang sử dụng config remote khác nhưng muốn tích hợp thêm chặn quảng cáo ý ạ

**Comment by bigdargon** [comment]
@kingsman9413 bạn tham khảo hướng dẫn ở wiki của app https://github.com/Dreamacro/clash/wiki/Clash-Premium-Features

Mình thấy có rule load được url của mình bên trên để chèn vào config bạn đang xài, bạn thử xem. Nhưng hình như tính năng này chỉ dùng cho Premium

```
rule-providers:
  apple:
    behavior: "domain"
    type: http
    url: "url"
    interval: 3600
    path: ./apple.yaml
  microsoft:
    behavior: "domain"
    type: file
    path: /microsoft.yaml
```
https://raw.githubusercontent.com/bigdargon/hostsVN/master/option/hostsVN-clash-rule.yaml

**Comment by kingsman9413** [comment]
@bigdargon Vâng em cảm ơn anh với cách này em đã làm được nhưng có cách nào thêm mà vẫn update được link config remote kia mà không bị mất chặn qc này không ạ
Em thử trong cái đặt có cái host của app Clash nó có chặn được nhưng chỉ cho phép ghi thủ công mà không import file hay copy paste vào được tận 18k domain nên em đang tìm giải pháp nào tối ưu hơn đỡ mất công hơn ạ

**Comment by bigdargon** [comment]
@kingsman9413 Cái này bạn cần tìm người am hiểu về app mới được, hoặc bạn lên group telegram tìm hỗ trợ. Mình chỉ hỗ trợ phần nguồn remote để thêm vào config chứ mình k sử dụng app này!

**Comment by kingsman9413** [comment]
@bigdargon Cho em xin link group ạ

**Comment by bigdargon** [comment]
@kingsman9413 link group telegram đây bạn https://t.me/+rOFJhD3NGqBhMGE9. Mình sẽ đóng issue này ở đây nhé!
