### ISSUE TITLE
sdk-02.moengage.com false positive

### ISSUE THREAD

**Issue by FadeMind** [bigdargon/hostsVN#327]
[//]: # (***Vui lòng nhập thông tin phía dưới dòng có dấu "[//]:" các dòng này sẽ bị ẩn khi đăng bài. Xin cám ơn!)

***Địa chỉ trang web/ứng dụng lỗi***:

* **Lỗi khi bật hosts**: 

[//]: # (Thay thế %screenshot_url% bên dưới với địa chỉ hình ảnh báo lỗi. Ngoài ra, bạn có thể dán trực tiếp ảnh từ clipboard, chúng sẽ tự động được thêm vào.)

<details><summary>Ảnh chụp màn hình:</summary>

![image](%screenshot_url%)
</details><br/>

* **Khi không bật hosts**: 

[//]: # (Thay thế %screenshot_url% bên dưới với địa chỉ hình ảnh khi không sử dụng hosts. Nếu cần, hãy cung cấp ảnh chụp màn hình bên dưới, giống như trên)

<details><summary>Ảnh chụp màn hình:</summary>

![image](%url_of_screenshot%)
</details><br/>

***Chi tiết***:

DOMAIN `sdk-02.moengage.com` 
ISSUE
App management for T-Mobile need this domain for properly loading content
https://play.google.com/store/apps/details?id=pl.tmobile.miboa&hl=pl&gl=US

![20220907-1662573808](https://user-images.githubusercontent.com/9846948/188947690-34414c16-c8a7-4a66-a9d3-3d31299d957b.png)

**Comment by bigdargon** [comment]
@FadeMind Thank you! I will remove it. By the way, Adaway and Adguard DNS are also blocking this domain.
