### ISSUE TITLE
[FALSE-POSITIVE] tag.aticdn.net

### ISSUE THREAD

**Issue by smed79** [bigdargon/hostsVN#329]
Hi,

blocking `tag.aticdn.net` lead to break the video at `information.tv5monde.com`

e.g. `https://information.tv5monde.com/video/etats-unis-bataille-politique-autour-de-l-immigration`

Thank you.

**Comment by bigdargon** [comment]
@smed79 This domain is also available on Steven Black's hosts from upstream MVPS HOSTS https://winhelp2002.mvps.org/

**Comment by smed79** [comment]
Reported `https://github.com/StevenBlack/hosts/issues/2090`

Thank you.
