### ISSUE TITLE
za.zdn.vn

### ISSUE THREAD

**Issue by hlqviet** [bigdargon/hostsVN#334]
[//]: # (***Vui lòng nhập thông tin phía dưới dòng có dấu "[//]:" các dòng này sẽ bị ẩn khi đăng bài. Xin cám ơn!)

***Địa chỉ trang web/ứng dụng lỗi***: ZaloPay

* **Lỗi khi bật hosts**: 

[//]: # (Thay thế %screenshot_url% bên dưới với địa chỉ hình ảnh báo lỗi. Ngoài ra, bạn có thể dán trực tiếp ảnh từ clipboard, chúng sẽ tự động được thêm vào.)

<details><summary>Ảnh chụp màn hình:</summary>

![Screenshot_20221112-052345](https://user-images.githubusercontent.com/5486625/201439273-0f9b5d50-e5b1-46d2-b4bc-da78320efec2.png)
</details><br/>

* **Khi không bật hosts**: 

[//]: # (Thay thế %screenshot_url% bên dưới với địa chỉ hình ảnh khi không sử dụng hosts. Nếu cần, hãy cung cấp ảnh chụp màn hình bên dưới, giống như trên)

<details><summary>Ảnh chụp màn hình:</summary>

![Screenshot_20221112-052302](https://user-images.githubusercontent.com/5486625/201439298-03420965-52dc-4a6f-a520-53ffd132d472.png)
</details><br/>

***Chi tiết***:
Không vào được một số trang trong ZaloPay như nạp tiền ĐT, đặt vé phim

**Comment by bigdargon** [comment]
Bạn đang sử dụng app hay dịch vụ nào để lọc vậy? Hiện tại, mình kiểm tra thì app Zalo Pay đều mở bình thường. Và mình đang dùng NextDNS để lọc DNS

![image](https://user-images.githubusercontent.com/10969626/201480085-d3b70219-95e4-41ed-9002-d2ffbee43658.png)
![image](https://user-images.githubusercontent.com/10969626/201480089-3ed47c87-49ab-40f9-81d5-bfc56d85ce39.png)
![image](https://user-images.githubusercontent.com/10969626/201480091-5bc05b20-227f-4571-8402-1ee10ff2d186.png)
![image](https://user-images.githubusercontent.com/10969626/201480097-9f409023-980b-4d22-a6a2-bf46b5fab468.png)

**Comment by hlqviet** [comment]
Lạ vậy ta. Mình cũng xài NextDNS, whitelist cái đó mới vào được, không là màn hình vừa hiện ra thì lập tức trắng trơn.
Mình xài ZaloPay trên Android.

**Comment by bigdargon** [comment]
@hlqviet Theo như hình chụp mình thấy bạn đang dùng Adguard để lọc qc bằng VPN để lọc bằng rule nữa. Nên bạn thử tắt VPN của Adguard, điền DoT trong cài đặt Private DNS rồi kiểm tra lại. Hoặc nếu android của bạn k có DoT, hãy thử cài đặt app NextDNS trên CH Play rồi kiểm tra lại giúp mình!

**Comment by bigdargon** [comment]
@hlqviet Adguard đã fix trên bộ lọc DNS rồi! Bạn kiểm tra, cập nhật các bộ lọc trên điện thoại là được.
