### ISSUE TITLE
please add with tvhai domain

### ISSUE THREAD

**Issue by ithungphat** [bigdargon/hostsVN#340]
[//]: # (***Vui lòng nhập thông tin phía dưới dòng có dấu "[//]:" các dòng này sẽ bị ẩn khi đăng bài. Xin cám ơn!)

[//]: # (Nếu bạn muốn thêm tên miền mới, vui lòng đưa tên miền vào thẻ bên dưới.)

***Tên miền***:
```
please add filter for
tvhay2.org
```

**Comment by bigdargon** [comment]
@ithungphat Mình kiểm tra thấy web này sạch rồi mà bạn?
![Screenshot 2023-03-29 at 09-38-58 TVHAY ORG xem phim mới thuyết minh lồng tiếng](https://user-images.githubusercontent.com/10969626/228412408-9340bd0c-bc85-41c9-a843-fc41c74d53a8.png)
