### ISSUE TITLE
đường dẫn không dùng được cho surge free

### ISSUE THREAD

**Issue by trunqhieu14** [bigdargon/hostsVN#353]
[//]: # (***Vui lòng nhập thông tin phía dưới dòng có dấu "[//]:" các dòng này sẽ bị ẩn khi đăng bài. Xin cám ơn!)

***Địa chỉ trang web/ứng dụng lỗi***:

* **Lỗi khi bật hosts**: 

[//]: # (Thay thế %screenshot_url% bên dưới với địa chỉ hình ảnh báo lỗi. Ngoài ra, bạn có thể dán trực tiếp ảnh từ clipboard, chúng sẽ tự động được thêm vào.)

<details><summary>Ảnh chụp màn hình:</summary>

![image](%screenshot_url%)
</details><br/>

* **Khi không bật hosts**: 

[//]: # (Thay thế %screenshot_url% bên dưới với địa chỉ hình ảnh khi không sử dụng hosts. Nếu cần, hãy cung cấp ảnh chụp màn hình bên dưới, giống như trên)

<details><summary>Ảnh chụp màn hình:</summary>

![image](%url_of_screenshot%)
</details><br/>

***Chi tiết***:

**Comment by bigdargon** [comment]
@trunqhieu14 Surge free bạn sử dụng đường dẫn có ghi ở trang chính repo

```
https://raw.githubusercontent.com/bigdargon/hostsVN/master/option/hostsVN-surge.conf
```

Còn Surge pro thì sử dụng đường dẫn riêng

```
https://raw.githubusercontent.com/bigdargon/hostsVN/master/option/hostsVN-surge-pro.conf
```

**Comment by trunqhieu14** [comment]
> @trunqhieu14Tăng đột biến miễn phí bạn sử dụng đường dẫn được ghi trên repo chính trang
> 
> ```
> https://raw.githubusercontent.com/bigdargon/hostsVN/master/option/hostsVN-surge.conf
> ```
> 
> Và Surge pro sử dụng riêng đường dẫn
> 
> ```
> https://raw.githubusercontent.com/bigdargon/hostsVN/master/option/hostsVN-surge-pro.conf
> ```

![IMG_5658](https://github.com/bigdargon/hostsVN/assets/129641501/b73e4564-ec87-4f40-b3b7-719cf95c64d6)

**Comment by trunqhieu14** [comment]
nó cứ hiện như này ạ

**Comment by bigdargon** [comment]
@trunqhieu14 đã fix
