### ISSUE TITLE
Lỗi không thể load video khi bật host và mở ứng dụng YouTube 

### ISSUE THREAD

**Issue by Tiennvhc** [bigdargon/hostsVN#360]
[//]: # (***Vui lòng nhập thông tin phía dưới dòng có dấu "[//]:" các dòng này sẽ bị ẩn khi đăng bài. Xin cám ơn!)

***Địa chỉ trang web/ứng dụng lỗi***:

* **Lỗi khi bật hosts**: 

[//]: # (Thay thế %screenshot_url% bên dưới với địa chỉ hình ảnh báo lỗi. Ngoài ra, bạn có thể dán trực tiếp ảnh từ clipboard, chúng sẽ tự động được thêm vào.)
![IMG_1657](https://github.com/bigdargon/hostsVN/assets/135231664/c52c9247-898f-4521-a166-2349d6e6d6f4)

<details><summary>Ảnh chụp màn hình:</summary>

![image](%screenshot_url%)
</details><br/>

* **Khi không bật hosts**: 

[//]: # (Thay thế %screenshot_url% bên dưới với địa chỉ hình ảnh khi không sử dụng hosts. Nếu cần, hãy cung cấp ảnh chụp màn hình bên dưới, giống như trên)

<details><summary>Ảnh chụp màn hình:</summary>

![image](%url_of_screenshot%)
</details><br/>

***Chi tiết***:

**Comment by bigdargon** [comment]
@Tiennvhc Bạn xem lại các bước hướng dẫn trong Wiki để cài đặt, tin cậy chứng chỉ. Mình đã kiểm tra mọi thứ vẫn hoạt động bình thường 

![image](https://github.com/bigdargon/hostsVN/assets/10969626/6e9857ee-7d34-4fbf-9803-9aaed11a7e8a)
