### ISSUE TITLE
Lỗi không xem được video khi dùng YouTube premium

### ISSUE THREAD

**Issue by tgiang92** [bigdargon/hostsVN#361]
[//]: # (***Vui lòng nhập thông tin phía dưới dòng có dấu "[//]:" các dòng này sẽ bị ẩn khi đăng bài. Xin cám ơn!)

***Địa chỉ trang web/ứng dụng lỗi***:
 Ứng dụng YouTube 
* **Lỗi khi bật hosts**: 

[//]: # (Thay thế %screenshot_url% bên dưới với địa chỉ hình ảnh báo lỗi. Ngoài ra, bạn có thể dán trực tiếp ảnh từ clipboard, chúng sẽ tự động được thêm vào.)

![image](https://github.com/bigdargon/hostsVN/assets/139442238/24d9d8a3-af10-474e-aa0c-dcdb635a5d98)

* **Khi không bật hosts**: 

[//]: # (Thay thế %screenshot_url% bên dưới với địa chỉ hình ảnh khi không sử dụng hosts. Nếu cần, hãy cung cấp ảnh chụp màn hình bên dưới, giống như trên)

<details><summary>Ảnh chụp màn hình:</summary>
![image](https://github.com/bigdargon/hostsVN/assets/139442238/b8d00903-eff0-4814-8354-a214273a7141)

***Chi tiết***:
Khi sử dụng host mà xem video trên YouTube có premium thì sẽ báo lỗi không xem được.
Tài khoản bình thường thì sẽ lướt qua quảng cáo và xem bình thường.
khi không dùng host xem premium bình thường

**Comment by bigdargon** [comment]
@tgiang92  Premium đã không có quảng cáo, nên chặn qc bằng app proxy không có tác dụng. Bạn cần tắt tính năng rewrite đối với các tên miền `googlevideo.com` để không ảnh hưởng dịch vụ
