### ISSUE TITLE
Nhờ giúp đỡ

### ISSUE THREAD

**Issue by nakheel77** [bigdargon/hostsVN#363]
[//]: # (***Vui lòng nhập thông tin phía dưới dòng có dấu "[//]:" các dòng này sẽ bị ẩn khi đăng bài. Xin cám ơn!)
Làm thế nào để thêm đường dân https://abpvn.com/android/abpvn.txt vào AdAway. Xin cảm ơn!
[//]: # (Hãy nhập nội dung mà bạn muốn thảo luận, rất cám ơn mọi ý kiến đóng góp của bạn!)

***Nội dung***:

**Comment by bigdargon** [comment]
@nakheel77 bạn vào phần cài đặt của app Adaway sẽ có chỗ thêm nguồn mới vào, sử dụng bản adaway mới nhất sẽ có giao diện như bên dưới

https://f-droid.org/packages/org.adaway/

https://github.com/AdAway/AdAway

![host_sources](https://github.com/bigdargon/hostsVN/assets/10969626/25d1f681-2cd9-4c6c-b2d8-3cb1daf1a4f2)

**Comment by nakheel77** [comment]
Xin chân thành cảm ơn ban quản trị đã trả lời!

Mình có vào lại Adaway nhưng của mình không thấy phần setting và có dấu
cộng để thêm vào như của admin ạ.

**Comment by bigdargon** [comment]
@nakheel77 bạn chụp màn hình chính của adaway mình xem

**Comment by nakheel77** [comment]
> @nakheel77 bạn chụp màn hình chính của adaway mình xem



> @nakheel77 bạn chụp màn hình chính của adaway mình xem

Xin cảm ơn ban quản trị rất nhiều, mình đã cập nhật phiên bản mới và đã thêm add host được rồi nha! Mà ban quản trị cho mình hỏi tại sao không thể block quảng cáo trong một số phần mềm như facebook được ạ.

Xin chân thành cảm ơn!

**Comment by bigdargon** [comment]
@nakheel77 Các app như facebook, instagram, youtube, twitter, reddit,.. các quảng cáo được chèn vào tên miền của app đó luôn, gọi là quảng cáo bên thứ nhất (1st). Các hình thức chặn qc kiểu hosts, DNS đều k có tác dụng với dạng qc này. Nên bạn chỉ có 1 cách duy nhất là cài đặt app mod đã xóa qc thôi!
