### ISSUE TITLE
New advertising / tracking domains

### ISSUE THREAD

**Issue by antiadvs** [bigdargon/hostsVN#365]
[//]: # (***Vui lòng nhập thông tin phía dưới dòng có dấu "[//]:" các dòng này sẽ bị ẩn khi đăng bài. Xin cám ơn!)

[//]: # (Nếu bạn muốn thêm tên miền mới, vui lòng đưa tên miền vào thẻ bên dưới.)

***Tên miền***:
```
ad-nex.com
img.ad-nex.com
i2ad.jp
brightadnetwork.com
puppyderisiverear.com
a.pemsrv.com
hananokai.tv
creative.live.javmix.tv
srv1.aaacompany.net
cdn-apac.onetrust.com
spicy-effect.com
ec-optimizer.com
s.yjtag.jp
adm.shinobi.jp
media.assistads.net
d2ezz24t9nm0vu.cloudfront.net
```

**Comment by bigdargon** [comment]
Updated in commit https://github.com/bigdargon/hostsVN/commit/4eefb4074b88f60c28412a0ad47f9f8ae63b4e3c Thanks @antiadvs
