### ISSUE TITLE
New gambling sites

### ISSUE THREAD

**Issue by antiadvs** [bigdargon/hostsVN#366]
[//]: # (***Vui lòng nhập thông tin phía dưới dòng có dấu "[//]:" các dòng này sẽ bị ẩn khi đăng bài. Xin cám ơn!)

[//]: # (Nếu bạn muốn thêm tên miền mới, vui lòng đưa tên miền vào thẻ bên dưới.)

***Tên miền***:
```
uw88vnn.com
uw88vnn1.com
uw88vnn2.com
uw88vnn3.com
uw88vnn4.com
```

**Comment by bigdargon** [comment]
Updated in commit https://github.com/bigdargon/hostsVN/commit/4eefb4074b88f60c28412a0ad47f9f8ae63b4e3c Thanks @antiadvs
