### ISSUE TITLE
Lỗi khi dùng Microsoft store

### ISSUE THREAD

**Issue by sattheptonghop** [bigdargon/hostsVN#368]
[//]: # (***Vui lòng nhập thông tin phía dưới dòng có dấu "[//]:" các dòng này sẽ bị ẩn khi đăng bài. Xin cám ơn!)

***Địa chỉ trang web/ứng dụng lỗi***:
Microsoft store
* **Lỗi khi bật hosts**: 

[//]: # (Thay thế %screenshot_url% bên dưới với địa chỉ hình ảnh báo lỗi. Ngoài ra, bạn có thể dán trực tiếp ảnh từ clipboard, chúng sẽ tự động được thêm vào.)
Không thể tải ứng dụng trên Microsoft store

<details><summary>Ảnh chụp màn hình:</summary>
![image](https://github.com/bigdargon/hostsVN/assets/20010645/026d5bfd-141c-488f-92ca-98751e9afd74)
</details><br/>

* **Khi không bật hosts**: 

[//]: # (Thay thế %screenshot_url% bên dưới với địa chỉ hình ảnh khi không sử dụng hosts. Nếu cần, hãy cung cấp ảnh chụp màn hình bên dưới, giống như trên)

<details><summary>Ảnh chụp màn hình:</summary>

![image](%url_of_screenshot%)
</details><br/>

***Chi tiết***:

**Comment by bigdargon** [comment]
@sattheptonghop Mình xem trong ảnh đính kèm của bạn nhiều app đã được cập nhật vài giây trước, còn PDF X đó bạn kiểm tra lại ứng dụng có trả phí hay k? Hoặc thử khởi động lại máy tính/modem mạng rồi thử lại.

Hiện tại, hostsVN không chặn những gì liên quan đến Store. Mình đang sử dụng NextDNS trên máy tính và mọi thứ vẫn tải được bình thường!

**Comment by sattheptonghop** [comment]
Lỗi này mình bị từ khi cập nhập lên win11. Ảnh kia là sau khi xoá hosts thì lại tải được. Mình vừa thử sử dụng lại hosts lại được. Xác nhận hosts không chặn Store nhé.
