### ISSUE TITLE
Request - Hosts chặn các game online phổ biến hiện tại

### ISSUE THREAD

**Issue by thiendt2k1** [bigdargon/hostsVN#369]
[//]: # (***Vui lòng nhập thông tin phía dưới dòng có dấu "[//]:" các dòng này sẽ bị ẩn khi đăng bài. Xin cám ơn!)

[//]: # (Nếu bạn muốn thêm tên miền mới, vui lòng đưa tên miền vào thẻ bên dưới.)

Như tiêu đề ạ, nhờ ad tạo 1 file hosts online gaming phổ biến hiện tại(cả mobile và pc) để em add adguard home/nextdns ạ, hiện giờ em cần Liên Minh, Liên Quân, Free Fire, Genshin ạ.
Bên nextdns nó có online gaming mà internalized mất rồi em tìm không được :(

**Comment by bigdargon** [comment]
@thiendt2k1 Chào bạn! Hiện tại mình không có chơi nhiều game ở trên nên không thể kiểm tra cho từng game để làm bộ lọc theo yêu cầu của bạn. Hầu hết các dịch vụ DNS đều cung cấp tính năng chặn game/app nên ít có blocklist dạng này.

Nếu đang sử dụng NextDNS muốn chặn game, ngoài Categories cung cấp Online Gaming trong Parental Control. Khi mở app/game, bạn theo dõi các tên miền truy vấn DNS và thêm vào Denylist để chặn thủ công.
