### ISSUE TITLE
Chứng chỉ hết hạn

### ISSUE THREAD

**Issue by hoangvangiang** [bigdargon/hostsVN#371]
[//]: # (***Vui lòng nhập thông tin phía dưới dòng có dấu "[//]:" các dòng này sẽ bị ẩn khi đăng bài. Xin cám ơn!)

[//]: # (Hãy nhập nội dung mà bạn muốn thảo luận, rất cám ơn mọi ý kiến đóng góp của bạn!)

***Nội dung***:
Mình có thể tự tạo mới hay phải dùng default theo file ạ?

**Comment by bigdargon** [comment]
@hoangvangiang Chứng chỉ mới trong các app proxy như Surge, Quantumult X, Shadowrocket,... khi hết hạn bạn bấm tạo chứng chỉ mới trong app, tải và tin cậy chứng chỉ là được. Chứng chỉ tự tạo bằng app không tốn phí.
