### ISSUE TITLE
[Add request] List of suggestions for sources of hosts data Gambling

### ISSUE THREAD

**Issue by alsyundawy** [bigdargon/hostsVN#378]
Which domain(s) should be blocked?

List of suggestions for sources of hosts data Gambling (Indonesia)

https://github.com/alsyundawy/TrustPositif/raw/main/gambling_indonesia.txt

Why should these domain(s) be blocked?
indonesia gambling site

**Comment by bigdargon** [comment]
@alsyundawy Thanks for the suggestion!

My repo is an upstream source, you should suggest other downstream sources or suggest adding the repo source to DNS blocking services will be more effective.
