### ISSUE TITLE
phimtronbo.pro

### ISSUE THREAD

**Issue by bui-lang** [bigdargon/hostsVN#380]
[//]: # (***Vui lòng nhập thông tin phía dưới dòng có dấu "[//]:" các dòng này sẽ bị ẩn khi đăng bài. Xin cám ơn!)

[//]: # (Nếu bạn muốn thêm tên miền mới, vui lòng đưa tên miền vào thẻ bên dưới.)

***Tên miền***:
```
phimtronbo.pro
```
Trang web này không có nội dung và tự chuyển hướng `shope.ee`

**Comment by bui-lang** [comment]
Bác @bigdargon cho em hỏi là: 3 bộ lọc **Threat** bên dưới có sự khác biệt về số lượng tên miền vậy ạ?
- ### 3.998 domains 
https://raw.githubusercontent.com/bigdargon/hostsVN/master/extensions/source/threat-VN.txt
- ### 3.994 hosts
https://raw.githubusercontent.com/bigdargon/hostsVN/master/extensions/threat/hosts-VN
- ### 3.943 rules
https://raw.githubusercontent.com/bigdargon/hostsVN/master/extensions/threat/filter-VN.txt

**Comment by bigdargon** [comment]
@bui-lang
- File `/source/threat-VN.txt` có số lượng tên miền = với file `/threat/hosts-VN`, có thể bạn đã đếm luôn các dòng có dấu `#`. 
- File `/theart/filter-VN.txt` loại trừ các tên miền con dạng `www.`, vì định dạng rule chặn tên miền `abc.com` sẽ chặn luôn tên miền con `www.abc.com`

**Comment by bui-lang** [comment]
@bigdargon 
> * File `/source/threat-VN.txt` có số lượng tên miền = với file `/threat/hosts-VN`, có thể bạn đã đếm luôn các dòng có dấu #.

Em dùng uBlock để đo tên miền của 2 file này ạ.
![IMG_20240505_221659](https://github.com/bigdargon/hostsVN/assets/74956696/d65f85e6-192c-42e6-bc18-6a46046ab683)

Vì thấy số lượng khác nhau nên em đang phân vân không biết nên dùng bộ lọc nào trong 3 cái. Nếu là **Cloudflare Zero Trust** thì nên dùng file domains, còn uBlock thì dùng file rules phải không ạ? Em cảm ơn!

**Comment by bigdargon** [comment]
@bui-lang uBlock thì nên dùng cái filter, còn cái hosts thì dùng cho Pi-hole. Cái `/source/threat-VN.txt` là nguồn để mình chạy script tạo ra các file sử dụng nên k có header, nên bạn k cần đến nó.

Đối với Cloudflare Zero Trust thì bạn xem script thêm blocklist có hỗ trợ chặn wildcard k? Nếu có thì dạng link filter, còn k thì xài dạng hosts.
