### ISSUE TITLE
Trang giả mạo google play, phân phối apk dùng trong lừa đảo

### ISSUE THREAD

**Issue by nhubaotruong** [bigdargon/hostsVN#383]
[//]: # (***Vui lòng nhập thông tin phía dưới dòng có dấu "[//]:" các dòng này sẽ bị ẩn khi đăng bài. Xin cám ơn!)

[//]: # (Nếu bạn muốn thêm tên miền mới, vui lòng đưa tên miền vào thẻ bên dưới.)

***Tên miền***:
```
dichvucong.thongtindancu.org
thongtindancu.org
dichvucong.dinhdanhcutru.com
dinhdanhcutru.com
```
Trang giả mạo google play, phân phối apk dùng trong lừa đảo

**Comment by bigdargon** [comment]
Thanks @nhubaotruong
