### ISSUE TITLE
thecounter.com blocked

### ISSUE THREAD

**Issue by raylu** [bigdargon/hostsVN#386]
https://github.com/bigdargon/hostsVN/blob/d47a637b263c07589c8e33ac0700ba7cb330190f/source/hosts.txt#L6462 is blocking thecounter.com, which is a burger restaurant

**Comment by bigdargon** [comment]
@raylu Thanks for your feedback! This domain was previously blocked by Disconnect.me, perhaps the store has purchased this domain and is using it.
