### ISSUE TITLE
NSFW Addition

### ISSUE THREAD

**Issue by IDKwhattoputhere** [bigdargon/hostsVN#387]
Bunkr seems like a porn hoster.

They host NSFW images and videos exclusively as you can see on their albums page.
`https://bunkr-albums.io/`

They even outright prohibit Movies and
TV Shows.
`https://bunkr.fi/faq`

They have a lot of domains. Here is what I found:
```
bunkr-albums.io
bunkr-cache.se
bunkr.fi
bunkrr.su
bunkr.si
bunkr.pk
bunkr.ru
bunkr.sk
bunkrrr.org
bunkr.ax
bunkr.ph
```

**Comment by bigdargon** [comment]
@IDKwhattoputhere Thanks for your suggestion! I checked and found that this domain provides a hosting service that allows users to upload files, not an adult content site. So it should not be added to the adult domain block list. Currently, I do not have a block list to block hosting service domains.
