### ISSUE TITLE
File wildcard.txt dành cho Adblock trên ios bị xóa

### ISSUE THREAD

**Issue by hd00842** [bigdargon/hostsVN#388]
Ad ơi file wildcard.txt dành cho Adblock trên iOS bị xóa rồi mong ad update lại. Cảm ơn ad nhiều

**Comment by bigdargon** [comment]
@hd00842 Chào bạn! Tập tin `wildcard.txt` trước đây sử dụng cho `dnscrypt-proxy` nên giờ mình đã đổi tên lại. Mình đã cập nhật lại Wiki và README, ứng dụng Adblock bây giờ sử dụng đường dẫn https://raw.githubusercontent.com/bigdargon/hostsVN/master/option/domain.txt

P/s: Kể từ iOS 14, Apple đã tích hợp DNS hệ thống sử dụng profile không còn dùng VPN để chặn gây lãng phí tài khuyên thiết bị nữa. Thay vào đó, sử dụng DNS hệ thống sẽ kết nối trực tiếp máy chủ DNS có bộ lọc chặn qc, vượt qua DNS nhà mạng và không bật thêm tiến trình VPN để lọc DNS nữa. Bạn tham khảo sử dụng NextDNS (đã có máy chủ ở VN) để tối ưu hơn https://github.com/bigdargon/hostsVN/wiki/NextDNS
