### ISSUE TITLE
thuekhachsan.com.vn

### ISSUE THREAD

**Issue by johndo100** [bigdargon/hostsVN#391]
[//]: # (***Vui lòng nhập thông tin phía dưới dòng có dấu "[//]:" các dòng này sẽ bị ẩn khi đăng bài. Xin cám ơn!)

[//]: # (Nếu bạn muốn thêm tên miền mới, vui lòng đưa tên miền vào thẻ bên dưới.)

***Tên miền***:
```
thuekhachsan.com.vn
```
Shopee Affiliate universal link.

**Comment by bigdargon** [comment]
Thanks @johndo100
