### ISSUE TITLE
Về hosts dạng domain và góp ý về việc chỉ nên chuyên biệt VN

### ISSUE THREAD

**Issue by nmhung1985** [bigdargon/hostsVN#66]
Chào bạn, lại thêm 1 nỗ lực chặn quảng cáo cho VN, hình như cũng lâu mà hôm qua mình mới biết. Thấy bạn làm có vẻ khá chuẩn nên xin gửi đôi lời cải tiến, ko phải issue nhưng do ko thấy chỗ để gửi feedback nên đành tạo ở đây vậy.

1. Loại hosts chỉ có domain, bạn đưa link tải lên thêm các nơi dễ biết một chút (trang chủ, wiki). Mình tình cờ đọc cái issue đầu tiên nên mới thấy link, ko là ko hề biết luôn. Khá nhiều app dùng loại hosts này đấy, như mình trên Samsung Galaxy Note 8 dùng Adhell.

2. Ko thấy bạn ghi chi tiết, cũng như chưa đủ trình để so, nhưng khi mình add vào app của mình thì báo rằng:
- bộ lọc nước ngoài sẵn có là 10792 domain
- bộ lọc của bạn là 10791 domain
App tổng hợp và lọc các bộ lọc trùng lặp thì còn 18666. 

Về cách dùng bộ lọc thì trước giờ mình thấy bắt nguồn từ logic/tiêu chuẩn của trình chặn quảng cáo nổi tiếng thời đầu là Adblock Plus, thì khi cài app chặn quảng cáo thường có sẵn bộ lọc tiếng Anh, cũng như hiện tại có một số link bộ lọc nổi tiếng toàn cầu để xử lý các trang tiếng Anh. Do đó, thường là khi tạo bộ lọc để chặn các trang của 1 vùng khác/1 ngôn ngữ khác, người ta khuyên chỉ nên tạo bộ lọc **bổ sung** để dùng với bộ lọc đi kèm app/bộ lọc nổi tiếng toàn cầu, ko nên dùng lại các rule đã có sẵn của các bộ lọc nổi tiếng kia.

Ở đây, với app của mình cho thấy của bạn có khoảng 8000 trong số 10791 domain là ko bị trùng. Vậy cũng là rất ổn, nhưng nếu tối ưu thêm chắc sẽ tốt hơn nữa.

**Comment by bigdargon** [comment]
Chào bạn @nmhung1985 ! Rất cám ơn bạn đã để tâm và góp ý github của mình! Vì github không hẳn là code nên bạn cứ đăng bài như diễn đàn, khi xong mình sẽ close lại. Vấn đề của bạn mình trả lời như sau:

> 1. Loại hosts chỉ có domain, bạn đưa link tải lên thêm các nơi dễ biết một chút (trang chủ, wiki). Mình tình cờ đọc cái issue đầu tiên nên mới thấy link, ko là ko hề biết luôn. Khá nhiều app dùng loại hosts này đấy, như mình trên Samsung Galaxy Note 8 dùng Adhell.

- Wiki ban đầu của mình viết có ghi địa chỉ, sau này mình thấy hơi dài và nhiều link cảm thấy không gọn nên mình đã thay đổi wiki như hiện tại (wiki trước đây bạn tham khảo [ở đây](https://github.com/bigdargon/hostsVN/wiki/Home/8905d629ac4c832e182cd9ee3cf642056614fb66). Về phần trang chủ mình sẽ edit lại sau theo ý tưởng mà bạn đề xuất, do mình chưa biết ghi cái gì nên chỉ ghi đơn giản như vậy.

- Vấn đề apps chặn qc bên android thật sự có rất rất nhiều apps tương tự! Mình cũng đã có bài wiki hướng dẫn 3 trong số các apps mà mình biết https://github.com/bigdargon/hostsVN/wiki/Android

 > Do đó, thường là khi tạo bộ lọc để chặn các trang của 1 vùng khác/1 ngôn ngữ khác, người ta khuyên chỉ nên tạo bộ lọc bổ sung để dùng với bộ lọc đi kèm app/bộ lọc nổi tiếng toàn cầu, ko nên dùng lại các rule đã có sẵn của các bộ lọc nổi tiếng kia.

Vì mình tạo hosts này để dùng chung cho cả ios lẫn android, vấn đề hosts chỉ chặn qc vn thì gặp tình huống trớ trêu bên ios là có những apps chỉ cho chọn 1 file cấu hình duy nhất để lọc như Surge hay Shadowrocket. Do đó mình phải gom lại thành 1 file để có thể dùng chung cho mọi hệ điều hành, nhưng mình đã tối ưu không copy vô tội vạ rồi thêm vào! 

Mạng nội bộ của mình sử dụng Pihole để làm dns chặn qc, khi mình truy cập dựa trên log chặn mà pihole tạo ra, từ đó mình sắp xếp vào bộ lọc của mình, nghĩa là bộ lọc của mình dựa trên những tên miền mà ở vn truy cập phổ biến. Mục tiêu của mình là dùng tất cả trong 1 để đơn giản k cần thêm nhiều hosts khác để mất thời gian chọn lựa.

Bên ABPVN cũng đã hợp nhất list của mình vào để làm nguồn chặn qc trên android bạn có thể tham khảo https://abpvn.com/android

Phần cấu trúc nội dung hosts mình đã puplic nên bạn sẽ thấy, mình phân loại theo group bao gồm những tên miền có nhiều hơn 4 tên miền, những tên miền vn mà ít tên miền mình nhóm vào 1 chỗ và phía dưới là những tên miền nước ngoài.

**Comment by nmhung1985** [comment]
Bạn nói Pihole, rồi lọc từ log Pihole để tạo bộ lọc là biết pro rồi. Nếu vậy thì có cách này chắc là bạn có thể làm được dễ dàng chăng?! (Nãy định viết trong post đầu mà thấy dài quá nên thôi chờ bạn trả lời xem sao).

Đó là tạo duy trì thêm 1 bộ lọc chỉ chuyên biệt chặn web VN. Cái này thực chất cũng như bên Adblock Plus, họ có bộ lọc mặc định là EasyList, vd khi hỗ trợ VN họ duy trì cả 2 link:
- Bộ lọc riêng cho VN (cài bổ sung thêm với EasyList)
- Bộ lọc đã trộn VN+EasyList (chỉ cần cài duy nhất bộ này và xoá cái mặc định đi)

Mình thấy bạn tạo nhiều file đồng thời nên chắc thêm 1 cái nữa ko khó phải ko nhỉ? (Sorry nếu mình nói ko đúng. Mình ko biết về code kiếc này nọ, quan sát thì suy ra vậy thôi).

**Comment by bigdargon** [comment]
Về phần tạo bộ lọc qc, sau khi mình tạo hosts chặn qc, có 1 số bạn trên diễn đàn cũng đề xuất làm bộ lọc riêng phát triển cho người Việt. Nhưng mình tìm thấy hiện tại có 2 bộ lọc đã và đang phát triển bộ lọc dạng như bạn nói nên mình tập trung làm files hosts sẽ tốt hơn vì mỗi bên mỗi công việc! 2 bộ lọc mình nhắc đến:
- http://nmtrung.com/fmsf-2
- https://abpvn.com

**Comment by nmhung1985** [comment]
À, hiểu nhầm rồi, dùng thuật ngữ tiếng Anh là biết ngay mà cứ dùng tiếng Việt hơi lộn xộn :) Ý mình là tương tự như Adblock Plus duy trì 2 loại filters list, thì đề xuất bạn cũng duy trì 2 loại hosts được ko:
- Link 1: hosts như hiện tại bạn đang làm (bao gồm VN+hosts thu thập tham khảo từ các hosts nước ngoài)
- Link 2: hosts **chuyên trị web tiếng Việt/ở Việt Nam** (tức loại **bổ sung** dành cho những ai có nhu cầu chỉ cài bổ sung thêm để dùng song song với hosts quốc tế)

**Comment by bigdargon** [comment]
Mình hiểu ý bạn rồi! Mình sẽ làm thêm 1 hosts chỉ tên miền VN trong đợt update kế tiếp!

**Comment by nmhung1985** [comment]
Hoan hô! :D Sợ từ đang nói ko chuẩn nên xin nói lại lần cuối cho chuẩn nhé. Ko chỉ tên miền .vn mà cho cả:
- web thuộc ở Việt Nam (vd vnexpress.net ko phải tên miền .vn :D)
- web tiếng Việt
- nói chung web người Việt hay vào (mà tất nhiên là chưa có trong hosts quốc tế)

**Comment by nmhung1985** [comment]
Ừm, chỉ là vài gợi ý, như hồi trước mình thử làm bộ lọc thì vào Alexa check các site được truy cập nhiều nhất từ VN.
Mấy trang dân mình vào nhiều như đánh bạc, xem thể thao, xxx thì ko phải .vn nhưng các domain ad nhúng ở mấy trang đó có .vn ko nhỉ?

**Comment by bigdargon** [comment]
Thường thì ở VN chủ yếu là banner sang trang đánh bạc chứ k nhà qc ở vn dám chạy đánh bạc! Ở VN mấy nhà qc k nhiều lắm, hầu như mình đã chặn sạch rồi :rofl:

**Comment by nmhung1985** [comment]
Ồ, ngon rồi! :D Nhờ bạn tạo thêm loại domain luôn nhé 👍 

Còn viết thì gì đâu, dân IT ko chuyên trình bày thì chỉ cần thêm vài ba dòng :D Ý là hồi đầu tại vì ngẫu nhiên mình đọc issue 1 (là loại closed rồi, bình thường chẳng ai mò vào) thì mới thấy báo là có loại domain.txt, chứ ở wiki hay trang chủ đều ko nhắc tới. Thành ra chỉ đơn giản thêm mục "Các loại file khác" rồi list từng cái và mô tả là xong.
