### ISSUE TITLE
[Lỗi] Chặn nhầm CDN

### ISSUE THREAD

**Issue by S-a-l-a-d** [bigdargon/hostsVN#79]
***Thông tin***:

* **Lỗi khi bật hosts**: 

<details><summary>Ảnh chụp màn hình:</summary>

![image](https://puu.sh/CaAIe/ff394228ce.png)
</details><br/>

* **Khi không bật hosts**: 

<details><summary>Ảnh chụp màn hình:</summary>

![image](https://puu.sh/CaAK6/7ec823d827.png)
</details><br/>

Website: <https://spiderum.com/>

**Comment by bigdargon** [comment]
Đã ghi nhận chặn nhầm tên miền `s3-ap-southeast-1.amazonaws.com` tối mình sẽ fix!
