### ISSUE TITLE
Wiki - Bài hướng dẫn Adhell 3 cho máy Samsung

### ISSUE THREAD

**Issue by nmhung1985** [bigdargon/hostsVN#88]
Thực ra cách cài app chặn quảng cáo trên Samsung cũng hơi phức tạp (do Samsung không thích nên phải thêm mấy bước để né). Do đó với nhiều bước thực hiện mà chụp hình từng bước một thì hơi loãng, nên mình nghĩ là viết chủ yếu là text (các bước mình đều check lại khá kỹ) và sẽ up vài hình giao diện demo cho mọi người tham khảo. Nội dung bài viết ở dưới nhé, có gì thì bàn thêm rồi trao đổi cho hoàn thiện trước khi close issue.

___________________

### Adhell 3 - App chặn quảng cáo hiệu quả nhất cho riêng dòng máy Samsung
Riêng đối với Samsung, hãng này có tích hợp module Knox trong các dòng máy của họ để thực hiện các tính năng bảo mật đặc biệt độc quyền, trong đó có tính năng tường lửa. Tận dụng module này, các nhà phát triển đã viết app Adhell 3 để hỗ trợ chặn quảng cáo trên máy Samsung với các ưu điểm sau:
- **KHÔNG CẦN** root
- cực kỳ nhanh và hiệu quả do dùng sẵn module tường lửa chính hãng tích hợp sẵn
- nhờ lý do trên nên app không cần chạy nền, giúp tối ưu dung lượng pin
- vô hiệu hóa thành phần của app (vd một số app đòi nhiều quyền truy cập danh bạ, hình ảnh không cần thiết)
- vô hiệu hóa các app ít dùng

### Thông tin về cách cài đặt
- Samsung không thích các loại app này. Nên app này sẽ không bao giờ có bản public chính thức hoặc trên Play Store vì Samsung có thể chặn id của app để không hoạt động được. Do đó, **mỗi người sẽ tự làm 2 thao tác sau**: a) sửa id của app, b) lấy key cài đặt.
- Để tránh bị Samsung kiện tụng, bản thân tác giả chính không build sẵn app để chúng ta tải về. Tuy nhiên, trong cộng đồng có một người khác (CitizenXVIL) hỗ trợ build và đưa lên Mediafire. Nên cơ bản mà nói, ở phía chúng ta sẽ không có gì khác biệt, mà đây chỉ là thông tin thêm cho các bạn rõ.

### Tải về
[MediaFire](https://www.mediafire.com/folder/sb37c6gmhqgbn/AdHell+3)

Các bạn sẽ tải 2 file:
1. App để sửa id của apk: apkEditorPro
2. App Adhell 3:
- Bản thông thường phù hợp đa số (hỗ trợ Knox 2.6 trở lên): ah3_v3.**1.1**.xxx
- Bản cho Knox 2.5 trở xuống: ah3_v3.0.0.xxx
- (Để biết phiên bản Knox máy mình là gì, bạn vào `Settings> About Phone> Software Information (Cài đặt> Về điện thoại> Thông tin phần mềm)` )

### Lấy key Knox
1. Vào đây tạo tài khoản Samsung và đăng ký là nhà phát triển: https://seap.samsung.com/enrollment
2. Sau đó, vào link sau để tạo key KPE (Knox Platform for Enterprise): https://seap.samsung.com/license-keys/generate
- Hệ thống đăng nhập của Samsung hình như hơi lỗi nên có thể bạn sẽ phải đăng nhập 2-3 lần.
- Vẫn để loại key là "Development Key".
- KHÔNG CHỌN "Recommended: Generate a backwards compatible key". (Nhưng nếu máy bạn là Knox 2.7.1 trở xuống và bạn muốn thì có thể thử)
- "Add key alias": ý nghĩa là ghi bí danh cho key để nhớ là mình tạo key cho mục đích gì, ghi ngắn ngắn vài kí tự là hợp lý (không khoảng trắng hay kí tự đặc biệt).
- Nhấn "Get License Key" và chọn Agree ở khung thông báo thỏa thuận.

3. Bạn sẽ được cấp key bắt đầu bằng KLM, dài 35 kí tự bao gồm cả dấu gạch ngang. Key này có hiệu lực trong 3 tháng. Hết 3 tháng, bạn vào lại trang Samsung để tạo key mới.

### Đổi tên và cài đặt Adhell 3
1. Cài apkEditorPro và chạy app này.
2. Chọn "Select an APK File" rồi tìm đến file apk của Adhell
3. Chọn "Common Edit"> đổi tên ở phần "Package name".
- **Lưu ý cho Note 9 và/hoặc Pie**: Có thể cách hiệu quả hơn là chọn "XML File Edit"> chọn file "AndroidManifest.xml", ngay dòng thứ 6 sẽ có đoạn `package=`
4. Đổi tên sao cho khác biệt nhưng dễ nhớ với bạn 
- Tên mặc định Adhell là "com.frontend.adblocker", tốt nhất đổi vẫn nên giữ nguyên độ dài là 3.8.9 kí tự
- Sau này với các bản Adhell mới, nếu bạn vẫn đổi theo tên này thì bạn sẽ cập nhật được Adhell. (Nếu dùng tên khác thì sẽ thành cài bản mới, máy sẽ hiện 2 bản Adhell!)
Vd: Bạn tên Hải người yêu tên Hương thì có thể đổi thành "com.**hai**ntend.**huong**cker".
5. Ngay khi bắt đầu sửa tên bằng Common Edit, giao diện APK Editor Pro sẽ hiện thêm thiết lập, hãy để ý và chắc chắn là "Rename the package name in resources.arsc" vẫn phải được chọn.
- **Lưu ý cho Note 9 và/hoặc Pie**: Nếu vẫn đang dùng cách _Common Edit_, ở phần "Minimum SDK Version" bạn điền **14**.
6. Tìm và nhấn các nút/biểu tượng có ý nghĩa là "Save" (Lưu)
7. Nhấn "Install" để cài đặt Adhell 3.

### Khởi chạy, cấu hình và sử dụng Adhell 3
1. Mở Adhell 3. Lần đầu tiên chạy:
- app sẽ đề nghị kích hoạt chức năng Admin, chọn "Enable Admin permission"> "Activate"
- điền key Knox vào rồi Submit/Activate License. Kể từ bây giờ Adhell 3 sẽ chạy bình thường.
2. Vào Domains> Providers, thêm hostsVN-dạng-domain theo link sau:
https://raw.githubusercontent.com/bigdargon/hostsVN/master/option/domain.txt
3. Vào Domains> Blacklist, tạo thêm các rule sau:
`com.android.chrome|*|53`
Lưu ý cho Note 9 và/hoặc Pie: thêm `com.sec.android.app.sbrowser|*|53`
4. Về Home, gạt để kích hoạt Domain rules và Firewall rules.
5. Do Google tích hợp thêm khả năng cho phép Chrome tự bỏ qua DNS trên máy để dùng trực tiếp 8.8.8.8, khiến bộ lọc có thể không còn tác dụng. Khi đó, bạn có thể tắt tính năng này bằng cách sau:
- Trong Chrome, mở link "chrome://flags"
- Ở ô tìm kiếm, gõ "async", bạn sẽ thấy "Async DNS Resolver". Chọn Disable tính năng này.

### Khắc phục một số vấn đề
1. Nếu bạn cần gỡ bỏ Adhell 3 thì nhớ hủy quyền hạn quản trị viên bằng cách vào `Cài đặt> Màn hình khóa và bảo mật> Cài đặt bảo mật khác> Ứng dụng quản trị thiết bị` (Settings> Lock screen and security> Other security settings> Device admin apps).
2. Nếu không kích hoạt được Adhell 3 thì bạn hãy thử lần lượt hoặc kết hợp các bước sau:
- Tạo và cài với tên khác
- Revoke key cũ và tạo key mới
- KHÔNG đổi tên, KHÔNG dùng APK Editor làm gì, cài luôn bản gốc tải từ Mediafire!

Như vậy là đã hoàn thành. Chúc mừng bạn đã chịu khó làm theo hướng dẫn của chúng tôi. Hãy thử trải nghiệm nhé, đảm bảo bạn sẽ thấy cách chặn quảng cáo trên Samsung hiệu quả hơn rất nhiều trên các máy Android khác và bên iOS.

Hình ảnh:
http://imgur.com/gallery/aKhDQvu

**Comment by nmhung1985** [comment]
À không, cũng chỉ là chặn host như các app khác thôi mà, có là mình đã list trong đoạn ưu điểm rồi :D

**Comment by bigdargon** [comment]
Ok bác! Đã cmt bên diễn đàn mời ae trong thớt test cùng vì mình k có máy Samsung!

**Comment by nmhung1985** [comment]
Ừm, chắc chỉ có mấy anh em test, chứ nó hơi nhiều bước thế này nghĩ chắc đa số sẽ khá ngại. Nhưng thui kệ, quan trọng là nó chất lượng thật, nên cứ viết để giúp ích cho người khác :D

**Comment by bigdargon** [comment]
Đã cập nhật bài viết wiki, cám ơn bạn rất nhiều!
https://github.com/bigdargon/hostsVN/wiki/Android#adhell

**Comment by bigdargon** [comment]
Đã update wiki!

**Comment by the-phuctran** [comment]
Mình có vấn đề là không thế gạt được nút domain, firewall mỗi lần gạt là lại popup ra text view thay vì các list

**Comment by nmhung1985** [comment]
Ko rõ ý bạn lắm. Bạn chụp hình hoặc quay màn hình rồi post lên để mình xem thử nhé.

**Comment by bigdargon** [comment]
@the-phuctran Nếu gặp lỗi bạn tạo issues mới kèm theo video hay hình ảnh càng tốt nhé! Thanks!

**Comment by nmhung1985** [comment]
À, biết cách fix lỗi của wiki Github rồi @bigdargon . Nếu xuống dòng thì gõ **_2-3 khoảng trắng trở lên_ rồi enter xuống dòng** thì wiki sẽ hiển thị đúng.

**Comment by the-phuctran** [comment]
https://i.imgur.com/oO0FZTH.png mình add rule rồi nha mà nó k nhận

**Comment by nmhung1985** [comment]
> https://i.imgur.com/oO0FZTH.png mình add rule rồi nha mà nó k nhận

Máy bạn là model gì? Knox bao nhiêu? Bạn cài Adhell version bao nhiêu? Chắc là bạn đổi tên theo cách Common Edit?

**Comment by the-phuctran** [comment]
Mình dùng note 3, knox 2.3, adhell ver 3.0 mới nhất, common edit

**Comment by nmhung1985** [comment]
Knox 2.3 chắc android cũ lắm nhỉ. Bạn có thể thử thêm:
1. Vào thư mục "Old builds (3.0.0)" tải bản 131 (đây là bản mình từng cài ok)
2. Tạo key dành cho 3.0.0 (cái này mình lại quên update) bằng link đúng sau: https://seap.samsung.com/license-keys/generate/edu
3. Edit đặt tên khác với bản đang lỗi rồi cài thử.

Còn bản đang lỗi, theo kiến thức hạn hẹp của mình thì có vẻ lỗi ở module nào đó. Mình đã hỏi bên forum của tác giả rồi, chờ xem họ nói gì.

**Comment by nmhung1985** [comment]
> Mình dùng note 3, knox 2.3, adhell ver 3.0 mới nhất, common edit

Trên nhóm tác giả trả lời là _trên lý thuyết_ thì chạy được bản cũ (và có vẻ bằng chứng là bạn cài được) nhưng quả thật họ ko có máy để test, cũng như Knox của bạn quá cũ nên lỗi bên trong app như vậy họ cũng không rõ là thế nào. Bạn có thể thử cài lại với bản 131 và key dạng ELM như bài post trước của mình. Nếu ko đc nữa thì đành vậy. Bạn có thể dùng các app khác như hướng dẫn bên wiki Android cũng ok đó. Chúc bạn có thể nâng cấp lên đời mới hơn :D

**Comment by the-phuctran** [comment]
Đen thay build mới cũng vô vọng rồi bác ơi, knox mình chắc sida quá rồi. Cám ơn bác đã bỏ công đi hỏi giúp.

**Comment by nmhung1985** [comment]
Ko thấy bạn nói thêm việc đã tạo lại đúng loại key và dùng bản 131 chưa. Dù sao thì nếu vẫn sẵn sàng test thì nếu bên nhóm tác giả có bổ sung gì nữa mình sẽ báo bạn.

**Comment by frankenstein0403** [comment]
Bác ơi làm thế nào để add key mới cho adhell ạ.

**Comment by nmhung1985** [comment]
> Bác ơi làm thế nào để add key mới cho adhell ạ.

App hỏi key hay là ý bạn muốn tự đổi key? Đầu tiên bạn vào hủy (revoke) key cũ như trong đoạn "Khắc phục một số vấn đề" hướng dẫn rồi tạo key mới như bthg.

**Comment by frankenstein0403** [comment]
key của mình sắp hết hạn, Mình đã hủy key cũ, vào adhell thì không thấy yêu cầu cập nhật key mới.

**Comment by nmhung1985** [comment]
À cứ thong thả, họ cảnh báo để mình chuẩn bị, còn có khi vài tuần Samsung mới thật sự cho key hết hạn. Nchung bạn cứ dùng bthg, khi nào app hỏi key mới thì bạn điền.

**Comment by frankenstein0403** [comment]
Thanks bác, mình hỏi thêm cái hosts không tự update hả bác, như của mình cùng 1 link hosts đấy thì bản mình cài hồi tháng 1 là 11770 và bản mình mới update là 12163.

**Comment by nmhung1985** [comment]
Đúng rồi, app này dev vẫn chưa làm tính năng tự động update cho hosts. Lâu lâu nhớ hoặc gặp ads thì chịu khó mở app rồi update :D

**Comment by frankenstein0403** [comment]
Bác ơi nmhung1985 cho e hỏi với, e cứ bật adhell là nó tự động dừng ứng dụng là sao ạ, và trước khi dừng nó yêu cầu active licence, active xong vào đến giao diện chính thì tự động out ra.

**Comment by nmhung1985** [comment]
> Bác ơi nmhung1985 cho e hỏi với, e cứ bật adhell là nó tự động dừng ứng dụng là sao ạ, và trước khi dừng nó yêu cầu active licence, active xong vào đến giao diện chính thì tự động out ra.

Cái đó là do xung đột phần mềm với nhau, nguyên nhân thì nhiều lắm, bị mấy trường hợp này thì mình cũng hên xui: do bản thân adhell bị lỗi thì chờ bản mới rồi cài update; còn nếu do phần mềm nào khác bị xung đột với adhell thì đành chịu, cách test duy nhất là máy reset sạch sẽ, rồi cài lần lượt từng phần mềm xem cái nào ko tương thích adhell.

**Comment by frankenstein0403** [comment]
Em vừa cài adhell bản mới hơn thì bị lỗi error code 201, tìm trên reddit họ bảo cái này phải dùng key khác, 256 kí tự chứ không phải key như bản cũ. Key này yêu cầu là partner, đăng kí partner rồi vẫn chưa có mail báo về. Bác check thử xem có cách nào lấy key không.
https://www.reddit.com/r/Adhell/comments/ah4pp3/failed_to_validate_product_key_error_201/

**Comment by nmhung1985** [comment]
> Em vừa cài adhell bản mới hơn thì bị lỗi error code 201, tìm trên reddit họ bảo cái này phải dùng key khác, 256 kí tự chứ không phải key như bản cũ. Key này yêu cầu là partner, đăng kí partner rồi vẫn chưa có mail báo về. Bác check thử xem có cách nào lấy key không.
> https://www.reddit.com/r/Adhell/comments/ah4pp3/failed_to_validate_product_key_error_201/

Do của mình vẫn chưa hết hạn nên ko biết vụ này. Nhưng vừa dạo loanh quanh và Discord của tác giả thì đúng là có thông báo mới hôm 20/4 là Samsung đang càng làm khó vụ tạo key (rất khó xin làm partner). Nếu đang có Adhell key hết hạn nhưng vẫn đang dùng được; hoặc key còn hạn thì cứ dùng đến ngày nào hay ngày đó, đừng uninstall. Còn hiện thời cài mới thì ko có cách nào kích hoạt key. Họ đang xem có cách nào ko.

**Comment by nmhung1985** [comment]
> Em vừa cài adhell bản mới hơn thì bị lỗi error code 201, tìm trên reddit họ bảo cái này phải dùng key khác, 256 kí tự chứ không phải key như bản cũ. Key này yêu cầu là partner, đăng kí partner rồi vẫn chưa có mail báo về. Bác check thử xem có cách nào lấy key không.

@frankenstein0403 Bên nhóm tác giả có cách để share/bán key rồi đấy. Bạn vào đọc hướng dẫn chỗ mua key mình mới update ở đây.
@bigdargon đang bận nên để sau, khi nào qua "cơn bão" thì chúng ta sẽ update lại mấy bài viết, link nhỉ :D

**Comment by frankenstein0403** [comment]
Em chưa dùng discord bao giờ nên không hiểu cách làm, bác hướng dẫn cách mua key với ạ.
Key này có vẻ như vẫn chưa chính thức, cách tham gia nhóm mua như nào ạ.

**Comment by nmhung1985** [comment]
> Em chưa dùng discord bao giờ nên không hiểu cách làm, bác hướng dẫn cách mua key với ạ.
> Key này có vẻ như vẫn chưa chính thức, cách tham gia nhóm mua như nào ạ.
Key này hoàn toàn chính thức và hợp lệ (nên mới dùng được, vì Samsung check key trực tiếp thông qua server của họ). Đại loại là Samsung hiện giờ chỉ cấp key cho partner (tức là một doanh nghiệp). Thì có ng tình nguyện hỗ trợ nhóm tác giả đăng ký làm partner với Samsung, nên giờ họ có thể tạo key được.
Nếu bạn thấy như vậy ok thì cố gắng chịu khó tạo Discord. Cần thì cũng có thể chat để mình gthich thêm cho nhanh. Có [chat trực tiếp trên web](https://discordapp.com/channels/@me) mà ko cần phải down về cài. Join group Discord chính thức của [Adhell ](https://discord.gg/prqxx5D )và [HostsVN](https://discord.gg/shPKfxG), và check nick mình bắt đầu là "Hung1985".

**Comment by frankenstein0403** [comment]
ok bác, vậy chờ khi nào có key chính thức nhờ bác hướng dẫn cách mua ạ.

**Comment by nmhung1985** [comment]
> ok bác, vậy chờ khi nào có key chính thức nhờ bác hướng dẫn cách mua ạ.

Nếu ý bạn là tác giả đăng công khai bán key trên trang chủ thì ko có đâu. Samsung ko bao giờ bán key mà chỉ CẤP PHÉP cho partner (đối tác) tạo key, nhóm tác giả cũng giữ danh tính cho người đã hỗ trợ nên họ sẽ luôn để trạng thái beta test. Mình cũng tôn trọng nên ko ghi hết tất tần tật trong bài hướng dẫn (ý chat để giải thích kỹ hơn là vậy), nhưng chắc sẽ update thêm một chút vậy.

**Comment by frankenstein0403** [comment]
Vâng, vậy nhờ bác chỉ cách mua với ạ. Bác có thể viết rõ hơn trong bài
hướng dẫn hoặc nói trong mail luôn được không ạ.

Vào 22:18, T.6, 2 Th8, 2019 nmhung1985 <notifications@github.com> đã viết:

**Comment by nmhung1985** [comment]
Cái mail mà bạn đang trả lời là một cách tiện lợi để post lên cái Issue trên Github này, ko phải email riêng. Hôm trước thấy bạn trên Discord, mình có chào mà chắc bạn chưa đăng nhập lại. Về cơ bản, mình đã cập nhật bài viết chỗ "Thông tin cách cài đặt" và "Cách mua key". Bạn có thể xem lại để biết mình cần chuẩn bị gì.

**Comment by toihoihan22** [comment]
Sao mình lấy được key mà mỗi lần add key active thành công là adhell 3 lập tức FC vậy nhỉ

**Comment by nmhung1985** [comment]
> Sao mình lấy được key mà mỗi lần add key active thành công là adhell 3 lập tức FC vậy nhỉ
Bạn làm theo bài cũ tự lấy key hay là bài mới mua key beta? Ngoài ra bạn cho biết thêm mấy thông tin:
- Dòng máy đang dùng
- Phiên bản Adhell (chắc là bản tải từ Mediafire?)

**Comment by nmhung1985** [comment]
> Sao mình lấy được key mà mỗi lần add key active thành công là adhell 3 lập tức FC vậy nhỉ

Bạn làm theo bài cũ tự lấy key hay là bài mới mua key beta? Ngoài ra bạn cho biết thêm mấy thông tin:
- Dòng máy đang dùng
- Phiên bản Adhell (chắc là bản tải từ Mediafire?)

**Comment by toihoihan22** [comment]
> > Sao mình lấy được key mà mỗi lần add key active thành công là adhell 3 lập tức FC vậy nhỉ
> 
> Bạn làm theo bài cũ tự lấy key hay là bài mới mua key beta? Ngoài ra bạn cho biết thêm mấy thông tin:
> 
> * Dòng máy đang dùng
> * Phiên bản Adhell (chắc là bản tải từ Mediafire?)

Mình đang xài S8 Android 9.0, Key tự lấy tời thời adhell 1. Phiên bản 3.12 beta 9. Cứ active key thành công. Vào được giao diện bên trong app tầm 1s là văng ra. Vào lại là bắt kích hoạt key lại. Vào tầm 1s là văng ra tiếp

**Comment by nmhung1985** [comment]
> Mình đang xài S8 Android 9.0, Key mình tự lấy trên web từ thời adhell 1. Phiên bản mình sử dụng là 3.12 beta 9. Cứ active key thành công. Vào được giao diện bên trong app tầm 1s là văng ra. Vào lại là bắt kích hoạt key lại. Vào tầm 1s là văng ra tiếp

Ừm, cách tự lấy key không còn kích hoạt được nữa bạn ạ. Giờ chỉ còn cách mua key từ nhóm tác giả thôi. Nếu chưa đọc thì bạn có thể đọc thông tin cập nhật ở bài hướng dẫn mới, mục "Thông tin cách cài đặt" và "Cách mua key":
https://github.com/nmhung1985/Tuyen-ngon-Chan-Quang-Cao-Against-All-Ads-Manifesto/blob/master/Adhell3.md

**Comment by toihoihan22** [comment]
> > Mình đang xài S8 Android 9.0, Key mình tự lấy trên web từ thời adhell 1. Phiên bản mình sử dụng là 3.12 beta 9. Cứ active key thành công. Vào được giao diện bên trong app tầm 1s là văng ra. Vào lại là bắt kích hoạt key lại. Vào tầm 1s là văng ra tiếp
> 
> Ừm, cách tự lấy key không còn kích hoạt được nữa bạn ạ. Giờ chỉ còn cách mua key từ nhóm tác giả thôi. Nếu chưa đọc thì bạn có thể đọc thông tin cập nhật ở bài hướng dẫn mới, mục "Thông tin cách cài đặt" và "Cách mua key":
> https://github.com/nmhung1985/Tuyen-ngon-Chan-Quang-Cao-Against-All-Ads-Manifesto/blob/master/Adhell3.md

Cám ơn bạn nhiều :D

**Comment by DNcouples** [comment]
Bạn ơi mình vào discord nhưng BOT báo hết key gì đó thì ko còn cách nào nữa hả bạn. 
"Adhell3 is no longer developed due to the inability to generate a key for non-partners."

**Comment by nmhung1985** [comment]
> Bạn ơi mình vào discord nhưng BOT báo hết key gì đó thì ko còn cách nào nữa hả bạn.
> "Adhell3 is no longer developed due to the inability to generate a key for non-partners."

Bài hướng dẫn mình đã viết rồi mà, kệ con bot đi (kiểu như nhóm tác giả làm vậy để đánh lạc hướng :D ). Bạn cứ pm trực tiếp cho cái nick B.O.S.S, nếu cần thì nói thêm là bạn của **Hung1985#6986**. Đó là nick mình trên Discord, có gì thì bạn cũng pm luôn cho nhanh.

**Comment by DNcouples** [comment]
> > Bạn ơi mình vào discord nhưng BOT báo hết key gì đó thì ko còn cách nào nữa hả bạn.
> > "Adhell3 is no longer developed due to the inability to generate a key for non-partners."
> 
> Bài hướng dẫn mình đã viết rồi mà, kệ con bot đi (kiểu như nhóm tác giả làm vậy để đánh lạc hướng :D ). Bạn cứ pm trực tiếp cho cái nick B.O.S.S, nếu cần thì nói thêm là bạn của **Hung1985#6986**. Đó là nick mình trên Discord, có gì thì bạn cũng pm luôn cho nhanh.

Haha đúng r, dốt tiếng anh nên khổ quá ạ :D

**Comment by DNcouples** [comment]
Ví dụ mình flash rom khác cho máy thì key đó còn sử dụng đc cho máy đó ko bạn :( hiện mình cũng đang xài rom cook, ko biết có chạy đc ko. Hỏi ông BOSS thì ổng cũng ko biết.

**Comment by nmhung1985** [comment]
Theo mình hiểu và **nhớ ko nhầm** thì đọc chat thì có ng nói họ đổi rom vẫn bthg. Vì giống như đợt lấy key miễn phí (nếu bạn đã từng cài trước đây), thì key đi theo máy chứ ko theo rom. Ơ nhưng mà, root với dùng rom cook rồi thì có cái Adaway miễn phí mà cũng tốt đó?

**Comment by DNcouples** [comment]
Vì mình có xài mấy app ngân hàng nên sợ root rồi nó phát hiện không cho xài nữa mất công chạy rom lại :D với lại nghe danh adhell này dành riêng cho samsung nên cũng ham.

**Comment by nmhung1985** [comment]
Tức bây giờ máy vẫn đang rom stock và chưa root đúng ko, vậy mà cứ tưởng đã root rồi.
Stock, chưa root, dùng app NH: lời khuyên là đừng nên root hay rom này nọ, và chọn adhell.
Còn chọn con đường root: thì trước khi root cài adhell và dùng key. Sau khi root, như nói ở trên thì key vẫn dùng lại được, chỉ trhop xấu nhất thì còn app AdAway. Rồi, nếu app NH ko chạy thì quay về rom stock - do đã kích hoạt trên rom stock rồi nên chắc chắn bây giờ key lại hoạt động bthg.
