### ISSUE TITLE
quảng cáo trong spotify++

### ISSUE THREAD

**Issue by tmtwin** [bigdargon/hostsVN#90]
***Link ads***:

`api.zcoup.com`

***Hình ảnh***:
![48384682_597831653978827_357529905400905728_n](https://user-images.githubusercontent.com/35215038/50050244-302bb080-0128-11e9-97ee-04f4c527609f.jpg)

![48350099_337882666796563_222481530725859328_n](https://user-images.githubusercontent.com/35215038/50050290-2b1b3100-0129-11e9-9674-b7a53175f982.jpg)

**Comment by bigdargon** [comment]
Cũng vừa phát hiện tên miền này! Thanks bạn! Sẽ sớm update vào conf!
